### ISSUE TITLE
macos unable connect vpn server running on vps 

### ISSUE THREAD

**Issue by lncan** [hwdsl2/docker-ipsec-vpn-server#100]
Hi guys, I followed this tutorial to run libreswan ipsec vpn server on google cloud. But when i cannot connect to server. Here is my log:
![screen shot 2018-11-19 at 17 42 31](https://user-images.githubusercontent.com/40355589/48702118-a4a32a80-ec22-11e8-95a6-679a1dc0046b.png)
![screen shot 2018-11-19 at 17 43 07](https://user-images.githubusercontent.com/40355589/48702119-a53bc100-ec22-11e8-8612-e8af91b1d9e5.png)
I tried to connect, but this error always occur everytime:
![screen shot 2018-11-19 at 17 45 46](https://user-images.githubusercontent.com/40355589/48702268-17140a80-ec23-11e8-88cd-488ded881023.png)
![screen shot 2018-11-19 at 17 46 06](https://user-images.githubusercontent.com/40355589/48702269-17140a80-ec23-11e8-952c-fb5079eb83fc.png)
While I can ping this ip normally:
![screen shot 2018-11-19 at 17 47 57](https://user-images.githubusercontent.com/40355589/48702350-49256c80-ec23-11e8-837c-8e8c25b8ae85.png)
I sure that i do all step correctly. I searched and tried to fix it but no successful. i don't know where error from? Anybody has solution about that and please let me know details that how can i correct this error? Thank you.

**Comment by hwdsl2** [comment]
@lncan Hello! You’ll need to open UDP ports 500 and 4500 for the VPN in your Google Cloud firewall settings for this server. Search Google for how to open the two ports. Before doing that, make sure to delete and re-create the Docker container with a new secure IPsec PSK and password (you posted those in the screenshot)
