### ISSUE TITLE
Unable to set own dns (pihole) server

### ISSUE THREAD

**Issue by L3rchal** [hwdsl2/docker-ipsec-vpn-server#102]
I am running docker container _ipsec-vpn-server_ latest version. I am also running _pihole_ in other docker container. 

What I am trying to achieve is to set dns server as the _pihole_. Both suppose to run on same machine but different container. 

I tried to it via config `vpn.env` : 
```
...
VPN_DNS_SRV1=localhost
VPN_DNS_SRV2=1.1.1.1
```
But it's not working due I am still getting ads when I am connected via VPN. 
Any advise what could help or be wrong? Thanks

**Comment by hwdsl2** [comment]
@L3rchal Hello! I am not familiar with pihole. Does it expose any port (e.g. UDP 53) on your Docker host? If it does, trying setting `VPN_DNS_SRV1` to your Docker host’s public (or if behind NAT, private) IP. You’ll need to recreate the Docker container after modifying `vpn.env`.

If that doesn’t work try setting it to the private IP of the pihole Docker container.

**Comment by L3rchal** [comment]
Ok solved. I solved issue by adding paramter `--net=host`. With this way I am able to cooperated with the other container running pihole. I also had to setup to **private address** to make this work. 

On the other hand when running new container **this way** there is this line: `WARNING: Published ports are discarded when using host network mode`
...
Should be this my concern? 

Anyway it's working now, feel free to close this.

**Comment by hwdsl2** [comment]
@L3rchal Glad to hear you got it working! It looks like that the warning message is saying that although the Docker container exposes (publishes) UDP ports 500 and 4500 (in the Dockerfile), they are "discarded" because using `--net=host` already "exposes" all ports on the host to the Docker container.

**Comment by hadalin** [comment]
I also had issues with this. What worked for me was changing a setting via Pi-Hole web interface: `Settings` > `DNS` > `Interface listening behavior` > `Listen on all interfaces`.

**Comment by michaeldavie** [comment]
@axeII or @hadalin, would you be willing to share your configs for this setup? I'm trying to do the same thing, but I'm stuck. I see the queries reaching the Pi-Hole, but the responses don't seem to be making it back to the device connecting through the VPN. Thanks for your help.

**Comment by axeII** [comment]
@michaeldavie  Hmm did you set vpn-dns ip to private ip address of your pihole machine instead of `localhost`?  I remember that `localhost` wasn't working for me. Hence my config as my pihole machine ip is `10.0.0.120`

```text
VPN_IPSEC_PSK=your_ipsec_pre_shared_key
VPN_USER=your_vpn_username
VPN_PASSWORD=your_vpn_password
VPN_DNS_SRV1=10.0.0.120
VPN_DNS_SRV2=10.0.0.120
```

**Comment by michaeldavie** [comment]
Thanks. The DNS server setting is making it through to the client, and the queries are reaching the Pi-Hole, but the responses don't seem to be making it back. Did you have to make any changes to the `iptables` configuration to get this to work?
