### ISSUE TITLE
--env-file存在bug

### ISSUE THREAD

**Issue by digizhou** [hwdsl2/docker-ipsec-vpn-server#105]
这个设计很不合理，，vpn.env只能创建时才有效，，启动vpn后中途修改添加其他用户，没有效果、、。。。新添加的用户不生效

**Comment by hwdsl2** [comment]
@digizhou 你好！由于 Docker 的设计，env文件只在创建容器时被读取。如果你需要更改用户，必须重新创建 Docker 容器。详见 README。目前并没有更好的方案。
