### ISSUE TITLE
有做限速吗

### ISSUE THREAD

**Issue by liuguojun** [hwdsl2/docker-ipsec-vpn-server#107]
测试时发现docker搭的ipsec比纯ss慢很多，大概是 10M  vs 50M 的样子，同一个测速点

**Comment by hwdsl2** [comment]
@liuguojun 你好！没有做限速。这个是正常的，因为 IPsec 的额外开销。参见 [1]。

[1] https://libreswan.org/wiki/Benchmarking_and_Performance_testing
