### ISSUE TITLE
为何要挂载系统盘的 /lib/modules

### ISSUE THREAD

**Issue by v7lin** [hwdsl2/docker-ipsec-vpn-server#111]
这似乎有点问题，docker镜像是基于debian，而安装docker镜像的系统可以是mac os、centos等非debian系统。可以不挂载系统盘的 /lib/modules 吗？

**Comment by hwdsl2** [comment]
@v7lin 你好！不支持在非 Linux 系统上使用这个 Docker 镜像。关于你的问题，如果你在 Docker host 上运行了 `sudo modprobe af_key`，则可以不挂载 `/lib/modules` 目录。挂载它是为了在 Ubuntu/Debian 系统上省去这一步而从容器内部载入该模块。
