### ISSUE TITLE
请问这个支持多用户吗

### ISSUE THREAD

**Issue by wangc0727** [hwdsl2/docker-ipsec-vpn-server#115]
这个连接过程中会掉线，如何解决啊

**Comment by wangc0727** [comment]
还有多用户同时在线的情况下会有问题吗

**Comment by hwdsl2** [comment]
@wangc0727 你好！请参见自述文档的重要提示一节。同一个 VPN 账户可以在你的多个设备上使用。但是由于 IPsec/L2TP 的局限性，如果需要同时连接在同一个 NAT （比如家用路由器）后面的多个设备到 VPN 服务器，你必须仅使用 IPsec/XAuth 模式。

**Comment by wangc0727** [comment]
你必须仅使用 IPsec/XAuth 模式。  这个如何使用这个模式啊，需要如何设置呢

**Comment by hwdsl2** [comment]
@wangc0727 请参见：
 https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth-zh.md

**Comment by wangc0727** [comment]
<img width="889" alt="aaa" src="https://user-images.githubusercontent.com/33690615/51161302-dc4dec00-18cc-11e9-9a9b-9f72edffb86c.png">
看图

**Comment by wangc0727** [comment]
我的是mac系统
