### ISSUE TITLE
How to allow clients to connect to each other?

### ISSUE THREAD

**Issue by 013231** [hwdsl2/docker-ipsec-vpn-server#12]
I've set up a vpn server and now every client is connected to the server. The connections between clients and server is perfect, but these clients can't communicate with each other. How to solve this problem?

**Comment by hwdsl2** [comment]
@013231 If the VPN clients are connected to the server via IPsec/L2TP, they should be assigned IPs within the VPN subnet. For example, the VPN server is at 192.168.42.1, and VPN clients are at 192.168.42.10, 192.168.42.11, 192.168.42.12, etc. In the default configuration, VPN clients can communicate with each other using the IP addresses as mentioned above.

**Comment by 013231** [comment]
@hwdsl2 Thanks. I know the subnet ips, but these clients really cannot communicate with each other.
`ping 192.168.42.1`(ping server from client0):

> PING 192.168.42.1 (192.168.42.1) 56(84) bytes of data.
> 64 bytes from 192.168.42.1: icmp_seq=1 ttl=64 time=6.75 ms
> 64 bytes from 192.168.42.1: icmp_seq=2 ttl=64 time=6.21 ms

`ping 192.168.42.1`(ping server from client1):

> PING 192.168.42.1 (192.168.42.1) 56(84) bytes of data.
> 64 bytes from 192.168.42.1: icmp_seq=1 ttl=64 time=6.59 ms
> 64 bytes from 192.168.42.1: icmp_seq=2 ttl=64 time=6.34 ms

`ping 192.168.42.10`(ping client0 from server):

> PING 192.168.42.10 (192.168.42.10): 56 data bytes
> 64 bytes from 192.168.42.10: icmp_seq=0 ttl=64 time=8.417 ms
> 64 bytes from 192.168.42.10: icmp_seq=1 ttl=64 time=6.512 ms

`ping 192.168.42.11`(ping client1 from server):

> PING 192.168.42.11 (192.168.42.11): 56 data bytes
> 64 bytes from 192.168.42.11: icmp_seq=0 ttl=64 time=7.997 ms
> 64 bytes from 192.168.42.11: icmp_seq=1 ttl=64 time=6.219 ms

`ping 192.168.42.11`(ping client1 from client0):

> PING 192.168.42.11 (192.168.42.11) 56(84) bytes of data.
> 7 packets transmitted, 0 received, 100% packet loss, time 5999ms

And I found the solution: 
http://unix.stackexchange.com/questions/110436/pptp-allow-remote-clients-to-communicate-with-each-other

**Comment by hwdsl2** [comment]
@013231 Thanks for the update, and happy to hear you got it working. I still think that the IPTables rules in run.sh should take care of this. See [run.sh#L210-L224](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/run.sh#L210-L224)

**Comment by 013231** [comment]
@hwdsl2 Sorry, I use an old image without [run.sh#L216](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/run.sh#L216) 😓

**Comment by hwdsl2** [comment]
@013231 Ah I see where the problem is. I suggest that you update to the latest image using `docker pull hwdsl2/ipsec-vpn-server`, and deploy a new container using instructions from the README. You may need to stop or destroy the old container before this step.
