### ISSUE TITLE
Set the subnet range

### ISSUE THREAD

**Issue by geiseri** [hwdsl2/docker-ipsec-vpn-server#121]
Right now I have a home network that is `10.10.1.0/24` and my office subnet is `10.0.5.0/24`.  Right now if I connect to the VPN I can no longer communicate with the office systems because it is trying to route through my home network.  Is there a way to tell the VPN to only allow `10.10.1.0/24` traffic to go over the VPN itself and leave the other routes untouched?

**Comment by hwdsl2** [comment]
@geiseri Hello! If I understand it correctly, you have set up a VPN server within your home network. For your use case, please refer to [1] and read all comments. Clone this Git repo, edit `run.sh` and change `leftsubnet` value to `10.10.1.0/24`. You'll then need to build the Docker image yourself [2] with these customizations, and finally, re-create the container.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/issues/514
[2] https://github.com/hwdsl2/docker-ipsec-vpn-server#build-from-source-code

**Comment by geiseri** [comment]
This is what I did now.  I just didn't want to run something special, since a) your docker is very well done, and b) I don't want to chase you :)

If I made a PR that made this a tunable with something `VPN_L2TP_NET`, `VPN_L2TP_LOCAL`, and `VPN_L2TP_POOL`, etc... would that be acceptable?

**Comment by hwdsl2** [comment]
@geiseri Thank you for offering to do a PR. However since this is not a common use case we'll probably look into this in the future (not now).

**Comment by geiseri** [comment]
Okay, I will fork and make a branch.  Are you okay with a PR sitting in your queue?  Either way, other than this small issue, your docker is a slick solution for me, and I am grateful for your work!
