### ISSUE TITLE
length of ISAKMP Identification Payload is larger than can fit

### ISSUE THREAD

**Issue by rs-development** [hwdsl2/docker-ipsec-vpn-server#123]
i am trying to connect from ubuntu 18.10 to the vpn server running on debian strech
```

Jan 31 22:59:58 c730329001dc pluto[2288]: "l2tp-psk"[3] 12.34.56.78 #5: responding to Main Mode from unknown peer 12.34.56.78 on port 55332
Jan 31 22:59:58 c730329001dc pluto[2288]: "l2tp-psk"[3] 12.34.56.78 #5: STATE_MAIN_R1: sent MR1, expecting MI2
Jan 31 22:59:59 c730329001dc pluto[2288]: "l2tp-psk"[3] 12.34.56.78 #4: STATE_MAIN_R2: retransmission; will wait 32 seconds for response
Jan 31 23:00:02 c730329001dc pluto[2288]: "l2tp-psk"[3] 12.34.56.78 #5: retransmitting in response to duplicate packet; already STATE_MAIN_R1
Jan 31 23:00:02 c730329001dc pluto[2288]: "l2tp-psk"[3] 12.34.56.78 #5: STATE_MAIN_R2: sent MR2, expecting MI3
Jan 31 23:00:02 c730329001dc pluto[2288]: "l2tp-psk"[3] 12.34.56.78 #5: byte at offset 1 (29) of 'ISAKMP Identification Payload'.'?reserved?' is 0xb3 but should have been zero (ignored)
Jan 31 23:00:02 c730329001dc pluto[2288]: "l2tp-psk"[3] 12.34.56.78 #5: length of ISAKMP Identification Payload is larger than can fit
Jan 31 23:00:02 c730329001dc pluto[2288]: "l2tp-psk"[3] 12.34.56.78 #5: probable authentication failure (mismatch of preshared secrets?): malformed payload in packet
Jan 31 23:00:02 c730329001dc pluto[2288]: "l2tp-psk"[3] 12.34.56.78 #5: STATE_MAIN_R2: retransmission; will wait 0.5 seconds for response
Jan 31 23:00:03 c730329001dc pluto[2288]: "l2tp-psk"[3] 12.34.56.78 #5: STATE_MAIN_R2: retransmission; will wait 1 seconds for response
Jan 31 23:00:04 c730329001dc pluto[2288]: "l2tp-psk"[3] 12.34.56.78 #5: STATE_MAIN_R2: retransmission; will wait 2 seconds for response
Jan 31 23:00:06 c730329001dc pluto[2288]: "l2tp-psk"[3] 12.34.56.78 #5: STATE_MAIN_R2: retransmission; will wait 4 seconds for response
Jan 31 23:00:06 c730329001dc pluto[2288]: "l2tp-psk"[3] 12.34.56.78 #5: byte at offset 1 (29) of 'ISAKMP Identification Payload'.'?reserved?' is 0xb3 but should have been zero (ignored)
Jan 31 23:00:06 c730329001dc pluto[2288]: "l2tp-psk"[3] 12.34.56.78 #5: length of ISAKMP Identification Payload is larger than can fit
Jan 31 23:00:06 c730329001dc pluto[2288]: "l2tp-psk"[3] 12.34.56.78 #5: probable authentication failure (mismatch of preshared secrets?): malformed payload in packet
Jan 31 23:00:10 c730329001dc pluto[2288]: "l2tp-psk"[3] 12.34.56.78 #5: STATE_MAIN_R2: retransmission; will wait 8 seconds for response
Jan 31 23:00:10 c730329001dc pluto[2288]: "l2tp-psk"[3] 12.34.56.78 #5: ERROR: asynchronous network error report on eth0 (sport=500) for message to 12.34.56.78 port 55332, complainant 12.34.56.78: Connection refused [errno 111, origin ICMP type 3 code 3 (not authenticated)]
Jan 31 23:00:18 c730329001dc pluto[2288]: "l2tp-psk"[3] 12.34.56.78 #5: STATE_MAIN_R2: retransmission; will wait 16 seconds for response
Jan 31 23:00:18 c730329001dc pluto[2288]: "l2tp-psk"[3] 12.34.56.78 #5: ERROR: asynchronous network error report on eth0 (sport=500) for message to 12.34.56.78 port 55332, complainant 12.34.56.78: Connection refused [errno 111, origin ICMP type 3 code 3 (not authenticated)]

```

**Comment by hwdsl2** [comment]
@rs-development Your IPsec pre-shared key entered on your VPN client does not match that on the VPN server (in `/etc/ipsec.secrets`). Re-enter your PSK and check for typos.

**Comment by rs-development** [comment]
Thank you for the fast reply!

I also saw this in the log and checked the psk twice, i also changed the key and tried again but no success. Is there any other option?

**Comment by hwdsl2** [comment]
@rs-development How did you set up the VPN client? Using the GUI or the command line? That error usually means your PSK does not match that on the server. So the only option is to double check the PSK.

**Comment by hwdsl2** [comment]
@rs-development The error means the PSK does not match. Try changing to a
secure alphanumeric PSK in /etc/ipsec.secrets on the server, then enter it
in the client. You must restart the IPsec service after changing the PSK to
take effect.

**Comment by rs-development** [comment]
Are there any special considerations for the PSK?
I tried a key that was to short in the beginning this error is now gone. I am sure the PSK is exactly the same on the client as on the server.

**Comment by hwdsl2** [comment]
@rs-development Glad to hear it works. The PSK should not contain these
special characters: “ ' \

If the key is too short Libreswan might show a warning but AFAIK it may
still work.

**Comment by rs-development** [comment]
Ahh i was unclear. The error still exists, at first i was using a short one, after i made the key longer the error described above occured

**Comment by hwdsl2** [comment]
@rs-development I see. Not really sure what happened. Make sure that the
PSK match and that you restart the IPsec service on the server after
changing the PSK.

**Comment by rs-development** [comment]
I removed the container and created a new one with a new key, after startup i used the PSK from `docker logs -f ipsec-vpn-server` to connect to the vpn server

**Comment by felangga** [comment]
I have the same problem too, actually it works from yesterday morning, but suddenly it won't connect and show the same error. The PSK key is correct.

**Comment by ZbigniewRA** [comment]
I have the same issue. PSK is 100% correct, retried it many, many times.
