### ISSUE TITLE
Checking that pluto is running                          [FAILED]

### ISSUE THREAD

**Issue by antpnz** [hwdsl2/docker-ipsec-vpn-server#127]
Hey. Everything worked well for a long time. Can't connect to server now.
I executed the command "ipsec verify".
ITS result "Checking that pluto is running                          [FAILED]"
Of course ipsec don't run.
Please tell me where to look for the problem.
My OS Ubuntu server 16.04

**Comment by hwdsl2** [comment]
@antpnz Hello! Enable and then check Libreswan logs for errors [1]. Connect your VPN client and check the logs again.

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#enable-libreswan-logs

**Comment by antpnz** [comment]
Thanks for responding. I'm wrong with the section, I don't have a docker. I just updated Libreswan, and it all worked. Thank you for your work!
