### ISSUE TITLE
amozon ec2  ubuntu16.04 docker方式  看日志好像是内核不支持  请问该怎么解决呢？

### ISSUE THREAD

**Issue by xgbyl** [hwdsl2/docker-ipsec-vpn-server#128]
Redirecting to: /etc/init.d/ipsec start
Starting pluto IKE daemon for IPsec: .
xl2tpd[1]: Not looking for kernel SAref support.
xl2tpd[1]: L2TP kernel support not detected (try modprobing l2tp_ppp and pppol2tp)
xl2tpd[1]: xl2tpd version xl2tpd-1.3.12 started on e0e4434be224 PID:1
xl2tpd[1]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
xl2tpd[1]: Forked by Scott Balmos and David Stipp, (C) 2001
xl2tpd[1]: Inherited by Jeff McAdams, (C) 2002
xl2tpd[1]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016
xl2tpd[1]: Listening on IP address 0.0.0.0, port 1701

**Comment by hwdsl2** [comment]
@xgbyl 你好！该信息可以忽略（不影响使用）。使用内核支持有助于提高 IPsec/L2TP 性能，在 Ubuntu 16.04 上需要安装 linux-modules-extra-$(uname -r) 软件包，然后重启服务器。

**Comment by xgbyl** [comment]
> 
> 
> @xgbyl 你好！该信息可以忽略（不影响使用）。使用内核支持有助于提高 IPsec/L2TP 性能，在 Ubuntu 16.04 上需要安装 `linux-modules-extra-$(uname -r)` 软件包，然后重启服务器。

但是我现在使用iphone进行配置连接不上  账户、密码、服务器以及密钥配置检查多，没有问题 ，但就是无法连接，提示“VPN服务器并为相应”   有可能是什么原因呢  该怎么去排查？

**Comment by hwdsl2** [comment]
@xgbyl Amazon EC2 服务器的安全组必须打开 UDP 端口 500 和 4500。另外你可以启用并检查日志。如果尝试连接后没有新的日志，则连接没有到达服务器。

https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#启用-libreswan-日志
