### ISSUE TITLE
Internal subnet IP to other container

### ISSUE THREAD

**Issue by ThePutzy** [hwdsl2/docker-ipsec-vpn-server#13]
Hi, sorry for this (stupid) question, but i'm searching two days for a solution.

I have three containers your IPSec container (vpn1), an openvpn container (vpn2) and one proxy (squid) container.
Now i want to send the traffic from VPN through the proxy.
But i need the internal VPN IP of Client in the Proxy.

With OpenVPN it's ok i've solved it.
But with ipsec it's not so easy.
So i need the 192.168.43.0/24 IP in proxy (forwarded-for).

OpenVPN is started with (--network=host).
Proxy is on default bridge and IPSec too.

Do you have any idea to solve it? 😃 

vpn1 --- \
####### | --- squid --- www
vpn2 --- /

P.S.: Thanks for you work, IPSec setup and IPSec Image are very usefully

**Comment by hwdsl2** [comment]
@ThePutzy You may also run the VPN container with the `--network=host` switch. When connecting via IPsec/L2TP, the VPN clients are assigned IPs starting from 192.168.42.10 up to 192.168.42.250. When connecting via IPsec/XAuth, the VPN clients are assigned IPs starting from 192.168.43.10 up to 192.168.43.250.

Does this answer your question? If not, please give more details on what you are trying to achieve.

**Comment by ThePutzy** [comment]
I want to setup a bridged network (10.0.0.0/8).
e.g. like this:
OpenVPN Server (10.255.0.1)
IPSec Server (10.255.0.2)

The proxys are only over VPN reachable (we have more proxys, for any Unit at our Company one):
Squid01 (10.10.0.1 || unit1@company.com)
Squid02 (10.10.1.1 || unit2@company.com)
Squid03 (10.10.2.1 || unit3@company.com)

One reverse Proxy (10.0.0.2) to send traffic to apaches in SquidContainer (Setup the Squids with webinterface).

Now i want to send the traffic of 10.10.0.0/24 to Squid01, traffic of 10.10.1.0/24 to Squid02 ....

But i want to send the traffic to the proxy with the internal IP of the Client like 192.168.43.11.
at the moment i have only the IPSec Container IP (10.255.0.2) at the Proxy.

> "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "10.0.0.0/8",
                    "Gateway": "10.0.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "07cff904f19f164fb780df1f4fef594f0db3b2a6b8a30acbea6f14fb8da77570": {
                "Name": "vpn01",
                "EndpointID": "2c2c8d516b918c1eee9b2d64a0e05293693b401519477441e4a57f6116f4ade6",
                "MacAddress": "02:42:0a:ff:00:01",
                "IPv4Address": "10.255.0.1/8",
                "IPv6Address": ""
            },
            "6907e0fe2899755c6b65666bb828ca4c257b24c006648b786e95ee6805145306": {
                "Name": "revProxy",
                "EndpointID": "ed1902557d3abe1019b430524588412445d99ca73b57f8ae39b4a25686c87338",
                "MacAddress": "02:42:0a:00:00:02",
                "IPv4Address": "10.0.0.2/8",
                "IPv6Address": ""
            },
            "97c1dafb2f3aed0e1865de2e2ba89e74d5bedb639168da19005d6128593f094f": {
                "Name": "squid01",
                "EndpointID": "c8aa1e4064f7041b4a5a89d1194e99534bbeb164660afa5034106da3c69bbdc1",
                "MacAddress": "02:42:0a:0a:00:01",
                "IPv4Address": "10.10.0.1/8",
                "IPv6Address": ""
            },
            "e903d43584b17f6af7f7cec244a7c641b3d79371e68bbf094adaaad5771e577e": {
                "Name": "vpn02",
                "EndpointID": "1ef81ebcc28054e2c7f52f3ee641f540a1c88e3a6abe85edd9bc6405011608e6",
                "MacAddress": "02:42:0a:ff:00:02",
                "IPv4Address": "10.255.0.2/8",
                "IPv6Address": ""
            }
        },

**Comment by ThePutzy** [comment]
Now i can connect from my device to the vpn if it's started with "--network host".
But i can't ping from host to 192.168.43.11 (device IP).

**Comment by hwdsl2** [comment]
@ThePutzy Thanks for the details. Sorry I am still having a very hard time understanding your setup. Maybe you can try starting the container with the `--privileged` flag instead of `--cap-add=NET_ADMIN`, as suggested in the project README. Honestly I am not sure if it is possible to ping from the host to devices on the VPN, even if the container was started with `--network host`.

I am closing this issue as it is not an problem with this repository, but a question for your particular use case. Unfortunately I don't have the required knowledge to help you further on this. I would suggest that you instead seek help from the Docker community. Good luck!

**Comment by ThePutzy** [comment]
No Problem, thanks for your time :-)

**Comment by kennyparsons** [comment]
@ThePutzy I am a few steps behind you. How do you configure the vpn server to use the squid proxy?
