### ISSUE TITLE
有支持IKEV2的可行性吗？

### ISSUE THREAD

**Issue by haohetao** [hwdsl2/docker-ipsec-vpn-server#131]
IKEv2可以支持移动IP，休眠，切换网络不掉线，对手机有很好的支持
不过我以前测试的IKEv2必须绑定服务器的主机IP或域名，公网IP必须是接口IP才行，不知道有没有解决办法。

**Comment by hwdsl2** [comment]
@haohetao 请参见 [1]。该教程需要你在服务器上直接安装 VPN，而不是使用 Docker。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md
