### ISSUE TITLE
FIx Readme

### ISSUE THREAD

**Issue by Zagrebelsky** [hwdsl2/docker-ipsec-vpn-server#134]
Please, fix Readme,

If you use one addition account it would created, if you use more than one additional account them would not be created. 
```
VPN_ADDL_USERS=additional_username_1 additional_username_2
VPN_ADDL_PASSWORDS=additional_password_1 additional_password_2
```

should be:
```
VPN_ADDL_USERS='additional_username_1 additional_username_2'
VPN_ADDL_PASSWORDS='additional_password_1 additional_password_2'
```
With comma it works.

**Comment by hwdsl2** [comment]
@Zagrebelsky Hello! Docker parses variables in `env` files "literally", with no special handling for single and double quotes (they won't be removed) [1]. Therefore, the original README is correct. Try it yourself and you'll see why.

   > There is no special handling of quotation marks. This means that they are part of the VAL.

[1] https://docs.docker.com/compose/env-file/
