### ISSUE TITLE
TL-WAR1200L 能够建立连接，但无法拨号

### ISSUE THREAD

**Issue by UnoIoU** [hwdsl2/docker-ipsec-vpn-server#139]
我们在国外的一台服务器上建立了IPsec VPN,本地笔记本(macOS)能够连接并建立通道，`ifconfig ppp`能够查看到创建的虚拟网卡，两端能够`tracepath`通。

在路由器上，使用更改后的`ipsec.conf`能够建立连接，但没有创建虚拟网卡，`ifconfig ppp`显示没有发现设备。路由器日志显示`成功建立通道，但无法拨号`。

请问可以在 IPsec 服务器这端解决吗？

下面是截图：
路由器连接时pluto的日志:
![路由器连接时pluto的日志](https://user-images.githubusercontent.com/23488882/56011441-33236000-5d1a-11e9-9631-4f42d9fe619e.png)

路由器日志：
![s2](https://user-images.githubusercontent.com/23488882/56011480-649c2b80-5d1a-11e9-9a5b-c2f036426783.png)

路由器连接时ifconfig ppp 输出
![s3](https://user-images.githubusercontent.com/23488882/56011487-6ebe2a00-5d1a-11e9-8575-7148b0ef1610.png)

ipsec.conf文件内容：
![image](https://user-images.githubusercontent.com/23488882/56011509-8eede900-5d1a-11e9-9618-ec138efbce80.png)

**Comment by hwdsl2** [comment]
@UnoIoU 你好！Libreswan 的日志显示 IPsec 通道建立成功，问题可能出在 `xl2tpd`。试一下再次连接你的路由器，然后查看一下服务器上的 xl2tpd 日志是否有错误：
```
# Ubuntu/Debian
grep xl2tpd /var/log/syslog
# CentOS
grep xl2tpd /var/log/messages
```

另外，服务器上应该查看比如 `ppp0` 而不是 `ppp`。你可以尝试 `ifconfig -a`。
