### ISSUE TITLE
local HTTPS sites not working from VPN

### ISSUE THREAD

**Issue by quinnsam** [hwdsl2/docker-ipsec-vpn-server#14]
After connecting to the VPN (xauth) I am not able to load my local https websites. I am able to connect to regular http websites located by the docker host but not https. While connected to the VPN I am able to ping the docker host with no problems.  I have also added exceptions to the firewall on the host for the  website port as well as 443 for SSL, with no luck. 

I receive the following error: ERR_ADDRESS_UNREACHABLE

I also attempted to use the --net=host but receive error:
xl2tpd[1]: setsockopt recvref[30]: Protocol not available
xl2tpd[1]: This binary does not support kernel L2TP.
  
Is this something that I should change in the Dockerfile or is this a host error?

**Comment by hwdsl2** [comment]
@quinnsam Hello! This output is normal:

```
xl2tpd[1]: setsockopt recvref[30]: Protocol not available
xl2tpd[1]: This binary does not support kernel L2TP.
```

You may use "--net=host" but I don't think it is related to this issue.

Is your VPN client Android 6.0 or 7.0? If so, please see [1]. Also can you try rebooting your VPN client and/or VPN server?

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android-6-and-7

**Comment by quinnsam** [comment]
Unfortunately, in Android 7.1.1 there is no option for

**Comment by quinnsam** [comment]
Unfortunately, in Android 7.1.1 there is no option for "Backwards compatible mode". And the "sha2-truncbug=yes" line was already present. I did solve the issue by switching from XAuth to L2TP.
