### ISSUE TITLE
can't modprobe af_key on GKE Kubernetes

### ISSUE THREAD

**Issue by zegetech** [hwdsl2/docker-ipsec-vpn-server#145]
Does this work on GKE. Trying the ubuntu GKE node image and note getting through to modprobe af_key. 

getting 
```bash
 modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.15.0-1028-gcp/modules.dep.bin'
 modprobe: FATAL: Module af_key not found in directory /lib/modules/4.15.0-1028-gcp 

```

**Comment by hwdsl2** [comment]
@zegetech Hello! Unfortunately, this Docker image has not been tested on GKE. According to your logs, your server's kernel is missing its corresponding kernel modules in `/lib/modules/4.15.0-1028-gcp`. Once you fix that, you'll be able to use `modprobe` to insert the `af_key` module.

**Comment by hwdsl2** [comment]
The `af_key` kernel module is no longer required in the latest version of this Docker image with Libreswan 3.28.

**Comment by zegetech** [comment]
Great. Thanks @hwdsl2 . Had got it work by 
1. Using an `ubuntu` Node image
2. Doing a host mount on the deployment to /lib/modules

Now i can use the GKE default and more secure `cos`  image
