### ISSUE TITLE
Can't connect two devices with same IP simultaneously

### ISSUE THREAD

**Issue by alirezarzna** [hwdsl2/docker-ipsec-vpn-server#147]
When my PC is connected to the VPN server, I can't connect my phone which is on same WiFi, but once I disconnect my PC it connects but then my PC can not get connected.
Am i doing something wrong?

**Comment by hwdsl2** [comment]
@alirezarzna Hello! The IPsec/L2TP mode has limitations that it does not support multiple devices from behind the same NAT. Use only IPsec/XAuth ("Cisco IPsec") mode for this use case. See README.

This issue can also occur when you connect two devices from the same IP using different modes, for example, one using IPsec/L2TP and the other using IPsec/XAuth ("Cisco IPsec") mode. After connecting the first device, the VPN server "remembers" the mode from that IP, and will refuse connections using a different mode. To resolve, use the same mode for all such devices.
