### ISSUE TITLE
ipsec vpn 建立后 客户端流量都走vpn了，如何处理呢？

### ISSUE THREAD

**Issue by cuiketing** [hwdsl2/docker-ipsec-vpn-server#148]
大神你好，我用的是docker 起的 ipsec vpn ，连接也建立了，但是发现客户端所有流量都走了vpn，我只想让客户端访问固定的网段，比如10.10.10.0/24，如何配置呢？我排查了下原因是因为ipsec vpn 建立连接后增加了一条默认路由，且优先级很高，这个有办法在ipsec服务端配置吗？

**Comment by hwdsl2** [comment]
@cuiketing 你好！请参见 #121。
