### ISSUE TITLE
Can connect to VPN on MAC, but no traffic passes though

### ISSUE THREAD

**Issue by directorex** [hwdsl2/docker-ipsec-vpn-server#153]
Hey guys, 
No traffic going through the VPN and no access to censored sites. It's connecting but that's it. 

Any ideas?

Please check out the logs also did a traceroute. FYI server is in HK and the user is in mainland china. 

<img width="540" alt="Screen Shot 2019-07-17 at 14 39 53" src="https://user-images.githubusercontent.com/52991201/61352796-db5c3e00-a8a0-11e9-813d-63af7594b193.png">

================================================

Redirecting to: /etc/init.d/ipsec start
Starting pluto IKE daemon for IPsec: .
xl2tpd[1]: Not looking for kernel SAref support.
xl2tpd[1]: L2TP kernel support not detected (try modprobing l2tp_ppp and pppol2tp)
xl2tpd[1]: xl2tpd version xl2tpd-1.3.12 started on 949230746a9a PID:1
xl2tpd[1]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
xl2tpd[1]: Forked by Scott Balmos and David Stipp, (C) 2001
xl2tpd[1]: Inherited by Jeff McAdams, (C) 2002
xl2tpd[1]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016
xl2tpd[1]: Listening on IP address 0.0.0.0, port 1701
xl2tpd[1]: Connection established to 112.96.248.6, 59395.  Local: 37229, Remote: 12 (ref=0/0).  LNS session is 'default'
xl2tpd[1]: start_pppd: I'm running: 
xl2tpd[1]: "/usr/sbin/pppd" 
xl2tpd[1]: "/dev/pts/0" 
xl2tpd[1]: "passive" 
xl2tpd[1]: "nodetach" 
xl2tpd[1]: "192.168.42.1:192.168.42.10" 
xl2tpd[1]: "refuse-pap" 
xl2tpd[1]: "auth" 
xl2tpd[1]: "require-chap" 
xl2tpd[1]: "name" 
xl2tpd[1]: "l2tpd" 
xl2tpd[1]: "file" 
xl2tpd[1]: "/etc/ppp/options.xl2tpd" 
xl2tpd[1]: Call established with 112.96.248.6, PID: 308, Local: 64535, Remote: 33624, Serial: 1
xl2tpd[1]: Maximum retries exceeded for tunnel 37229.  Closing.
xl2tpd[1]: Terminating pppd: sending TERM signal to pid 308
xl2tpd[1]: Connection 12 closed to 112.96.248.6, port 59395 (Timeout)
xl2tpd[1]: Unable to deliver closing message for tunnel 37229. Destroying anyway.
xl2tpd[1]: control_finish: Peer requested tunnel 13 twice, ignoring second one.
xl2tpd[1]: Connection established to 112.96.240.232, 55186.  Local: 1735, Remote: 13 (ref=0/0).  LNS session is 'default'
xl2tpd[1]: start_pppd: I'm running: 
xl2tpd[1]: "/usr/sbin/pppd" 
xl2tpd[1]: "/dev/pts/0" 
xl2tpd[1]: "passive" 
xl2tpd[1]: "nodetach" 
xl2tpd[1]: "192.168.42.1:192.168.42.10" 
xl2tpd[1]: "refuse-pap" 
xl2tpd[1]: "auth" 
xl2tpd[1]: "require-chap" 
xl2tpd[1]: "name" 
xl2tpd[1]: "l2tpd" 
xl2tpd[1]: "file" 
xl2tpd[1]: "/etc/ppp/options.xl2tpd" 
xl2tpd[1]: Call established with 112.96.240.232, PID: 339, Local: 23682, Remote: 32275, Serial: 1
xl2tpd[1]: Maximum retries exceeded for tunnel 1735.  Closing.
xl2tpd[1]: Terminating pppd: sending TERM signal to pid 339
xl2tpd[1]: Connection 13 closed to 112.96.240.232, port 55186 (Timeout)
xl2tpd[1]: get_call: can't find call 23682 in tunnel 1735
 (ref=0/0)xl2tpd[1]: get_call: can't find call 23682 in tunnel 1735
 (ref=0/0)xl2tpd[1]: result_code_avp: result code endianness fix for buggy Apple client. network=256, le=1
xl2tpd[1]: control_finish: Connection closed to 112.96.240.232, port 55186 (), Local: 1735, Remote: 13
xl2tpd[1]: Connection established to 203.168.23.113, 60475.  Local: 64533, Remote: 15 (ref=0/0).  LNS session is 'default'
xl2tpd[1]: start_pppd: I'm running: 
xl2tpd[1]: "/usr/sbin/pppd" 
xl2tpd[1]: "/dev/pts/0" 
xl2tpd[1]: "passive" 
xl2tpd[1]: "nodetach" 
xl2tpd[1]: "192.168.42.1:192.168.42.10" 
xl2tpd[1]: "refuse-pap" 
xl2tpd[1]: "auth" 
xl2tpd[1]: "require-chap" 
xl2tpd[1]: "name" 
xl2tpd[1]: "l2tpd" 
xl2tpd[1]: "file" 
xl2tpd[1]: "/etc/ppp/options.xl2tpd" 
xl2tpd[1]: Call established with 203.168.23.113, PID: 370, Local: 22685, Remote: 47552, Serial: 1
xl2tpd[1]: check_control: Received out of order control packet on tunnel 15 (got 5, expected 4)
xl2tpd[1]: handle_packet: bad control packet!
xl2tpd[1]: result_code_avp: result code endianness fix for buggy Apple client. network=768, le=3
xl2tpd[1]: control_finish: Connection closed to 203.168.23.113, serial 1 ()
xl2tpd[1]: Terminating pppd: sending TERM signal to pid 370
xl2tpd[1]: Maximum retries exceeded for tunnel 64533.  Closing.
xl2tpd[1]: Connection 15 closed to 203.168.23.113, port 60475 (Timeout)
xl2tpd[1]: Unable to deliver closing message for tunnel 64533. Destroying anyway.
xl2tpd[1]: control_finish: Peer requested tunnel 17 twice, ignoring second one.
xl2tpd[1]: Connection established to 203.168.23.113, 56636.  Local: 54155, Remote: 17 (ref=0/0).  LNS session is 'default'
xl2tpd[1]: start_pppd: I'm running: 
xl2tpd[1]: "/usr/sbin/pppd" 
xl2tpd[1]: "/dev/pts/0" 
xl2tpd[1]: "passive" 
xl2tpd[1]: "nodetach" 
xl2tpd[1]: "192.168.42.1:192.168.42.10" 
xl2tpd[1]: "refuse-pap" 
xl2tpd[1]: "auth" 
xl2tpd[1]: "require-chap" 
xl2tpd[1]: "name" 
xl2tpd[1]: "l2tpd" 
xl2tpd[1]: "file" 
xl2tpd[1]: "/etc/ppp/options.xl2tpd" 
xl2tpd[1]: Call established with 203.168.23.113, PID: 411, Local: 49293, Remote: 65476, Serial: 1
xl2tpd[1]: result_code_avp: result code endianness fix for buggy Apple client. network=768, le=3
xl2tpd[1]: control_finish: Connection closed to 203.168.23.113, serial 1 ()
xl2tpd[1]: Terminating pppd: sending TERM signal to pid 411
xl2tpd[1]: result_code_avp: result code endianness fix for buggy Apple client. network=256, le=1
xl2tpd[1]: control_finish: Connection closed to 203.168.23.113, port 56636 (), Local: 54155, Remote: 17
xl2tpd[1]: control_finish: Peer requested tunnel 18 twice, ignoring second one.
xl2tpd[1]: Connection established to 112.96.241.65, 50808.  Local: 57203, Remote: 18 (ref=0/0).  LNS session is 'default'
xl2tpd[1]: start_pppd: I'm running: 
xl2tpd[1]: "/usr/sbin/pppd" 
xl2tpd[1]: "/dev/pts/0" 
xl2tpd[1]: "passive" 
xl2tpd[1]: "nodetach" 
xl2tpd[1]: "192.168.42.1:192.168.42.10" 
xl2tpd[1]: "refuse-pap" 
xl2tpd[1]: "auth" 
xl2tpd[1]: "require-chap" 
xl2tpd[1]: "name" 
xl2tpd[1]: "l2tpd" 
xl2tpd[1]: "file" 
xl2tpd[1]: "/etc/ppp/options.xl2tpd" 
xl2tpd[1]: Call established with 112.96.241.65, PID: 443, Local: 43112, Remote: 22029, Serial: 1
xl2tpd[1]: Maximum retries exceeded for tunnel 57203.  Closing.
xl2tpd[1]: Terminating pppd: sending TERM signal to pid 443
xl2tpd[1]: Connection 18 closed to 112.96.241.65, port 50808 (Timeout)
xl2tpd[1]: get_call: can't find call 43112 in tunnel 57203
 (ref=0/0)xl2tpd[1]: get_call: can't find call 43112 in tunnel 57203
 (ref=0/0)xl2tpd[1]: get_call: can't find call 43112 in tunnel 57203
 (ref=0/0)xl2tpd[1]: get_call: can't find call 43112 in tunnel 57203
 (ref=0/0)xl2tpd[1]: get_call: can't find call 43112 in tunnel 57203
 (ref=0/0)xl2tpd[1]: get_call: can't find call 43112 in tunnel 57203
 (ref=0/0)xl2tpd[1]: get_call: can't find call 43112 in tunnel 57203
 (ref=0/0)xl2tpd[1]: get_call: can't find call 43112 in tunnel 57203
 (ref=0/0)xl2tpd[1]: get_call: can't find call 43112 in tunnel 57203
 (ref=0/0)xl2tpd[1]: get_call: can't find call 43112 in tunnel 57203
 (ref=0/0)xl2tpd[1]: get_call: can't find call 43112 in tunnel 57203
 (ref=0/0)xl2tpd[1]: result_code_avp: result code endianness fix for buggy Apple client. network=256, le=1
xl2tpd[1]: control_finish: Connection closed to 112.96.241.65, port 50808 (), Local: 57203, Remote: 18
xl2tpd[1]: Connection established to 183.40.29.134, 51413.  Local: 25425, Remote: 19 (ref=0/0).  LNS session is 'default'
xl2tpd[1]: start_pppd: I'm running: 
xl2tpd[1]: "/usr/sbin/pppd" 
xl2tpd[1]: "/dev/pts/0" 
xl2tpd[1]: "passive" 
xl2tpd[1]: "nodetach" 
xl2tpd[1]: "192.168.42.1:192.168.42.10" 
xl2tpd[1]: "refuse-pap" 
xl2tpd[1]: "auth" 
xl2tpd[1]: "require-chap" 
xl2tpd[1]: "name" 
xl2tpd[1]: "l2tpd" 
xl2tpd[1]: "file" 
xl2tpd[1]: "/etc/ppp/options.xl2tpd" 
xl2tpd[1]: Call established with 183.40.29.134, PID: 474, Local: 11389, Remote: 49234, Serial: 1
xl2tpd[1]: Maximum retries exceeded for tunnel 25425.  Closing.
xl2tpd[1]: Terminating pppd: sending TERM signal to pid 474
xl2tpd[1]: Connection 19 closed to 183.40.29.134, port 51413 (Timeout)
xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: get_call: can't find call 11389 in tunnel 25425
 (ref=0/0)xl2tpd[1]: Unable to deliver closing message for tunnel 25425. Destroying anyway.
xl2tpd[1]: Can not find tunnel 25425 (refhim=0)
xl2tpd[1]: network_thread: unable to find call or tunnel to handle packet.  call = 11389, tunnel = 25425 Dumping.
xl2tpd[1]: Can not find tunnel 25425 (refhim=0)
xl2tpd[1]: network_thread: unable to find call or tunnel to handle packet.  call = 11389, tunnel = 25425 Dumping.
xl2tpd[1]: Can not find tunnel 25425 (refhim=0)
xl2tpd[1]: network_thread: unable to find call or tunnel to handle packet.  call = 0, tunnel = 25425 Dumping.
xl2tpd[1]: Connection established to 36.113.8.29, 56831.  Local: 27767, Remote: 21 (ref=0/0).  LNS session is 'default'
xl2tpd[1]: start_pppd: I'm running: 
xl2tpd[1]: "/usr/sbin/pppd" 
xl2tpd[1]: "/dev/pts/0" 
xl2tpd[1]: "passive" 
xl2tpd[1]: "nodetach" 
xl2tpd[1]: "192.168.42.1:192.168.42.10" 
xl2tpd[1]: "refuse-pap" 
xl2tpd[1]: "auth" 
xl2tpd[1]: "require-chap" 
xl2tpd[1]: "name" 
xl2tpd[1]: "l2tpd" 
xl2tpd[1]: "file" 
xl2tpd[1]: "/etc/ppp/options.xl2tpd" 
xl2tpd[1]: Call established with 36.113.8.29, PID: 505, Local: 34548, Remote: 28725, Serial: 1
xl2tpd[1]: result_code_avp: result code endianness fix for buggy Apple client. network=768, le=3
xl2tpd[1]: control_finish: Connection closed to 36.113.8.29, serial 1 ()
xl2tpd[1]: Terminating pppd: sending TERM signal to pid 505
xl2tpd[1]: result_code_avp: result code endianness fix for buggy Apple client. network=256, le=1
xl2tpd[1]: control_finish: Connection closed to 36.113.8.29, port 56831 (), Local: 27767, Remote: 21
xl2tpd[1]: Connection established to 113.115.69.31, 62989.  Local: 22329, Remote: 22 (ref=0/0).  LNS session is 'default'
xl2tpd[1]: start_pppd: I'm running: 
xl2tpd[1]: "/usr/sbin/pppd" 
xl2tpd[1]: "/dev/pts/0" 
xl2tpd[1]: "passive" 
xl2tpd[1]: "nodetach" 
xl2tpd[1]: "192.168.42.1:192.168.42.10" 
xl2tpd[1]: "refuse-pap" 
xl2tpd[1]: "auth" 
xl2tpd[1]: "require-chap" 
xl2tpd[1]: "name" 
xl2tpd[1]: "l2tpd" 
xl2tpd[1]: "file" 
xl2tpd[1]: "/etc/ppp/options.xl2tpd" 
xl2tpd[1]: Call established with 113.115.69.31, PID: 536, Local: 20415, Remote: 36685, Serial: 1
xl2tpd[1]: Maximum retries exceeded for tunnel 22329.  Closing.
xl2tpd[1]: Terminating pppd: sending TERM signal to pid 536
xl2tpd[1]: Connection 22 closed to 113.115.69.31, port 62989 (Timeout)
xl2tpd[1]: get_call: can't find call 20415 in tunnel 22329
 (ref=0/0)xl2tpd[1]: get_call: can't find call 20415 in tunnel 22329
 (ref=0/0)xl2tpd[1]: get_call: can't find call 20415 in tunnel 22329
 (ref=0/0)xl2tpd[1]: get_call: can't find call 20415 in tunnel 22329
 (ref=0/0)xl2tpd[1]: get_call: can't find call 20415 in tunnel 22329
 (ref=0/0)xl2tpd[1]: get_call: can't find call 20415 in tunnel 22329
 (ref=0/0)xl2tpd[1]: get_call: can't find call 20415 in tunnel 22329
 (ref=0/0)xl2tpd[1]: get_call: can't find call 20415 in tunnel 22329
 (ref=0/0)xl2tpd[1]: get_call: can't find call 20415 in tunnel 22329
 (ref=0/0)xl2tpd[1]: get_call: can't find call 20415 in tunnel 22329
 (ref=0/0)xl2tpd[1]: get_call: can't find call 20415 in tunnel 22329
 (ref=0/0)xl2tpd[1]: get_call: can't find call 20415 in tunnel 22329
 (ref=0/0)xl2tpd[1]: get_call: can't find call 20415 in tunnel 22329
 (ref=0/0)xl2tpd[1]: get_call: can't find call 20415 in tunnel 22329
 (ref=0/0)xl2tpd[1]: get_call: can't find call 20415 in tunnel 22329
 (ref=0/0)xl2tpd[1]: get_call: can't find call 20415 in tunnel 22329
 (ref=0/0)xl2tpd[1]: Unable to deliver closing message for tunnel 22329. Destroying anyway.
xl2tpd[1]: Can not find tunnel 22329 (refhim=0)
xl2tpd[1]: network_thread: unable to find call or tunnel to handle packet.  call = 20415, tunnel = 22329 Dumping.
xl2tpd[1]: Can not find tunnel 22329 (refhim=0)
xl2tpd[1]: network_thread: unable to find call or tunnel to handle packet.  call = 20415, tunnel = 22329 Dumping.
xl2tpd[1]: Can not find tunnel 22329 (refhim=0)
xl2tpd[1]: network_thread: unable to find call or tunnel to handle packet.  call = 20415, tunnel = 22329 Dumping.
xl2tpd[1]: Can not find tunnel 22329 (refhim=0)
xl2tpd[1]: network_thread: unable to find call or tunnel to handle packet.  call = 0, tunnel = 22329 Dumping.

**Comment by hwdsl2** [comment]
@directorex Hello! Your logs indicate that the IPsec VPN connection may be blocked by the GFW. I suggest that you try alternative solutions such as Shadowsocks.
