### ISSUE TITLE
I can not ping clients, on the host, out of the container

### ISSUE THREAD

**Issue by raphsilvab** [hwdsl2/docker-ipsec-vpn-server#154]
Guys, I'm sorry for the weak English, I'm Brazilian and I do not know English.

I ran the container, but on my machine I can not ping the clients, who get ip in the 192.168.42.xx range. How do I view them? I am using VPN for the purpose of giving remote support to my clients.

Thanks!

**Comment by hwdsl2** [comment]
@raphsilvab Hello! Due to Docker's network isolation between containers and the host, unfortunately it is difficult to access the VPN clients from the Docker host. Please look into alternative tools for your use case.
