### ISSUE TITLE
Additional user - unable to specify IP address from ENV variable

### ISSUE THREAD

**Issue by wolasss** [hwdsl2/docker-ipsec-vpn-server#159]
First of all, thank you for all the work you do on this!

Currently there is no way to specify a specific-static IP address for the users (In run.sh you have hard-coded * sign). In order to do this, I have to modify insides of the container and edit the `/etc/ppp/chap-secrets` and change '*' to a specific IP address like:

"testuser" l2tpd "testpassword" 192.168.42.2

And that works quite well. But I think one should be able to specify such static IP address from the env variable when you build the container. What do you think?

**Comment by hwdsl2** [comment]
@wolasss Thank you for your suggestion. This is an uncommon use case and it is not easy to support env variables in the case of multiple VPN users. Therefore this feature won’t be added at this time, however you can build your own customized Docket image using build from source instructions from the README.
