### ISSUE TITLE
为什么连接是建立在ipv6上，这正常吗

### ISSUE THREAD

**Issue by tony1016** [hwdsl2/docker-ipsec-vpn-server#16]
运行后感觉日志正常，但是客户端连接不上。netstat的状态显示连接是建立在ipv6上，这正常吗？？

**Comment by hwdsl2** [comment]
@tony1016 你好！在我的服务器上，命令 `netstat -anput` 的输出如下:
```
$ netstat -anput
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
... ...
udp6       0      0 :::4500                 :::*                                1270/docker-proxy
udp6       0      0 :::500                  :::*                                1278/docker-proxy
```

虽然上面的输出看起来是指示连接通过 IPv6 建立，但其实不是。它是通过 IPv4 建立的。如果你的命令输出像上面这样，那么一切都正常。你需要另外查找一下客户端无法连接的其它原因。可以参见 [1]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除

**Comment by tony1016** [comment]
@hwdsl2 非常感谢。我现在很怀疑是当地GFW干的。因为我用nc测试，尽然所有udp端口都是success的，OMG

**Comment by tony1016** [comment]
@hwdsl2 我是指从1-65535

**Comment by hwdsl2** [comment]
@tony1016 嗯，有这个可能。你可以另行尝试一下 Shadowsocks [1] 或 ShadowsocksR [2]。

[1] https://github.com/shadowsocks/shadowsocks-libev
[2] https://github.com/breakwa11/shadowsocks-rss

**Comment by tony1016** [comment]
@hwdsl2 ss没有问题，因为最近苹果地图的一些问题，需要VPN。感谢回复
