### ISSUE TITLE
about ipsec in slow network

### ISSUE THREAD

**Issue by uranio-235** [hwdsl2/docker-ipsec-vpn-server#160]
What you suggest to handle slow network and outages? After network fails, ipsec expend so much time to reconnect because it expected to still connected. What parameters could I tweak? What could I do to improve this situation.

**Comment by hwdsl2** [comment]
@uranio-235 Hello! You can try changing the values of `dpddelay` and/or `dpdtimeout` in `/etc/ipsec.conf` on the VPN server, then run `service ipsec restart`. See [1] for more details. This might help, or alternatively, you can give OpenVPN a try with the "keepalive" parameter.

If you are using the Docker image, you will need to build it from source after changing those parameters. See [2].

[1] https://libreswan.org/man/ipsec.conf.5.html
[2] https://github.com/hwdsl2/docker-ipsec-vpn-server#advanced-usage
