### ISSUE TITLE
IP address for SSH

### ISSUE THREAD

**Issue by AKDub** [hwdsl2/docker-ipsec-vpn-server#161]
I have the docker running on a NAS in my home network - 192.168.1.100.

In the past, I am sure I used to be able to connect to your vpn from work, and ssh into the NAS. Am I mistaken? Currently I cant seem to do this, but nothing has changed recently other than some NAS reboots once in a while.

When I connect to the vpn, I seem to get an IP address of 192.168.42.x. Is this the issue?

**Comment by hwdsl2** [comment]
@AKDub Hello! The `192.168.42.x` IP is the internal VPN IP that the client gets from the VPN server after connecting. Due to Docker's network isolation among containers, it is generally difficult to SSH from one container (which runs your VPN server) into another container after connecting.

**Comment by AKDub** [comment]
So why did this work before? I’m trying to ssh into the NAS itself, not another container if that makes a difference

**Comment by hwdsl2** [comment]
@AKDub I am not familiar with your setup, but you can possibly use the VPN server’s internal address `192.168.42.1` after connecting.

**Comment by AKDub** [comment]
Interestingly after trying with different devices to get this to work, on android and on Linux I can connect and have access to the local network of the VPN. On macOS and iOS it connects and I get web access through the VPN, but no access to the VPN’s local network.

So there must be some setting that stops it from working fully on Apple devices, or maybe it’s how they set up their VPN client software that is causing the problem
