### ISSUE TITLE
reconnect take to long time

### ISSUE THREAD

**Issue by uranio-235** [hwdsl2/docker-ipsec-vpn-server#163]
In slow and fail-always network: What coul I do to improve reconnection? IkeV2 on windows 10 is not an option and this container do not implement it.

**Comment by hwdsl2** [comment]
@uranio-235 Hello! Please refer to #160. You may alternatively try OpenVPN [1] with the “keepalive” option to see if it works better for your use case.

[1] https://github.com/Nyr/openvpn-install
