### ISSUE TITLE
username2 and password2 not found

### ISSUE THREAD

**Issue by WeiWill0605** [hwdsl2/docker-ipsec-vpn-server#165]
Hi, I am trying to deploy a vpn server on ec2. It works when I add one VPN_ADDL_USERS, but fails when I try to add the second VPN_ADDL_USERS. It complains in this way:

Retrieving VPN credentials...
/opt/src/run.sh: 11: /opt/src/vpn.env: additional_username_2: not found
/opt/src/run.sh: 12: /opt/src/vpn.env: additional_password_2: not found

**Comment by hwdsl2** [comment]
@WeiWill0605 Hello! It looks like you tried to bind mount the `env` file [1]. To use this method, you must first edit your `env` file and use single quotes `''` to enclose the values of all variables. See [1] for more information.

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server#bind-mount-the-env-file
