### ISSUE TITLE
Can't connect to anything on the network

### ISSUE THREAD

**Issue by dan9qt** [hwdsl2/docker-ipsec-vpn-server#166]
Setup seems to have gone OK and I can connect to VPN, and web access is fine through the VPN, but I cant access my smb shares

**Comment by hwdsl2** [comment]
@dan9qt Hello! Your use case may require additional IPTables rules, as discussed in [1]. Unfortunately, there is no straightforward way to insert those rules to your Docker container.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#access-vpn-servers-subnet
