### ISSUE TITLE
Sharing VPN connection with other devices

### ISSUE THREAD

**Issue by kernowal** [hwdsl2/docker-ipsec-vpn-server#168]
Hi,

I'm trying to set up internet sharing to create a wireless network from the VPN via my computer so that I can connect to the VPN from other devices on my network that do not have configurable network settings. Everytime I turn internet sharing on, I cannot connect to the VPN and get the error `The L2TP-VPN server did not respond. Try reconnecting. If the problem continues, verify your settings and contact your Administrator.`. How can I configure my VPN connection to allow additional unverified devices to connect through this wireless network?

Thanks!

**Comment by hwdsl2** [comment]
@kernowal Hello! Your use case may require setting up a "hosted network" on using your computer's wireless network adapter. Please see this article [1] for example steps. I have not tested this, use at your own risk.

[1]  https://support.goldenfrog.com/hc/en-us/articles/360004951832-Internet-Connection-Sharing-for-VyprVPN-on-Windows-7-8-10-Wireless-
