### ISSUE TITLE
centos docker

### ISSUE THREAD

**Issue by 2898117012** [hwdsl2/docker-ipsec-vpn-server#17]
This binary does not support kernel L2TP.

**Comment by hwdsl2** [comment]
@2898117012 Hello! The output message you mentioned is normal and can be safely ignored.

**Comment by 2898117012** [comment]
I want to use L2TP.

**Comment by hwdsl2** [comment]
@2898117012 As I mentioned above, this output message is normal and can be ignored. Your VPN server's L2TP is working fine and is not affected by this message. You should be able to use it without problems.
