### ISSUE TITLE
docker搭建的ipsec在ios13和osx catalina上 无法使用

### ISSUE THREAD

**Issue by BENZJ** [hwdsl2/docker-ipsec-vpn-server#170]
我已经查看了[解决方案]( https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E9%A2%9D%E5%A4%96%E7%9A%84%E6%AD%A5%E9%AA%A4)。我使用的是docker搭建的。我修改了docker容器中的/etc/ipsec.conf文件改为sha2-truncbug=no。然后执行了service ipsec restart命令但是仍旧无法正常工作。所以我有尝试了docker restart ipsec-vpn-server。重启容器后看了一下etc/ipsec.conf文件，发现又变回sha2-truncbug=yes了。

**Comment by hwdsl2** [comment]
@BENZJ 你好！最新版的 Docker 镜像已改为 `sha2-truncbug=no` (57fa056)。请按照这些说明 [1] 更新你的 Docker 镜像。

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#%E6%9B%B4%E6%96%B0-docker-%E9%95%9C%E5%83%8F
