### ISSUE TITLE
Access VPN server's subnet

### ISSUE THREAD

**Issue by qy2009** [hwdsl2/docker-ipsec-vpn-server#172]
Hi, 

I saw you have some notes here:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#access-vpn-servers-subnet

So I change the settings inside my vpn docker console? or this is for local install only? 

Thanks!

**Comment by hwdsl2** [comment]
@qy2009 These notes are for local install only. In addition, if you want to build your own customized version of the Docker image, they can be used as a reference on which IPTables rules to add to `run.sh`.
