### ISSUE TITLE
IPSEC-XAUTH disconnects after 10 hours

### ISSUE THREAD

**Issue by majdya** [hwdsl2/docker-ipsec-vpn-server#175]
Hi, 
I am using the always on VPN feature of android,
I'm facing a disconnect after 10 hours, phone sends data, vpn connected on phone, but cant see traffic.
First thought that its DNS related, tried few did not help(google, Cloudflare and FreeDNS), 
apparently its not,so I thought its related to renew the connection/keys - which wired why it stops after 10 hours,
tried to find the config to adjust it, also didn't manage to find it,
any idea on what going on ?

**Comment by majdya** [comment]
I just found the rekey in conn shared - which were set by default to no, changed it to yes, will update you after 11 hours if this solves the problem for me. 
I just found it after posting the issue !!

**Comment by hwdsl2** [comment]
@majdya Glad that you resolved the issue. For the `rekey` option in `/etc/ipsec.conf`, if set to `no`, it just means that the VPN server does not request the renegotiation, but "it does not prevent responding to renegotiation requested from the other end" (see [1]).

[1] https://libreswan.org/man/ipsec.conf.5.html
