### ISSUE TITLE
Unable to test vpn locally on Mac OS X or Linux

### ISSUE THREAD

**Issue by rjurney** [hwdsl2/docker-ipsec-vpn-server#178]
I want to be able to setup an L2TP VPN locally to test this package on. However, the external IP address gets written to /etc/ipsec.conf so when I try to connect it does not respond.

How can I achieve this for testing?

**Comment by hwdsl2** [comment]
@rjurney Hello! You can override the external IP address that gets written by defining `VPN_PUBLIC_IP` in your `vpn.env` [1].

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/run.sh#L135
