### ISSUE TITLE
can this image support containerd?

### ISSUE THREAD

**Issue by zhipengzuo** [hwdsl2/docker-ipsec-vpn-server#182]
Hi when i run  fcojean/l2tp-ipsec-vpn-server with containerd,some error occurs:
This script should ONLY be run in a Docker container! Aborting.

Could this image can support containerd? thanks.

**Comment by zhipengzuo** [comment]
when i remove   exiterr "This script ONLY runs in a Docker container." this line in run.sh and rebuild this image ,it's ok to run in containerd  in test env .

**Comment by hwdsl2** [comment]
@zhipengzuo Hello! Thank you for the suggestion. There is not an easy way to identify containerd from inside a container. I would suggest that you continue to work around this by building your customized version [1] of the Docker image, as you mentioned.

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server#build-from-source-code

**Comment by zhipengzuo** [comment]
> @zhipengzuo Hello! Thank you for the suggestion. There is not an easy way to identify containerd from inside a container. I would suggest that you continue to work around this by building your customized version [1] of the Docker image, as you mentioned.
> 
> [1] https://github.com/hwdsl2/docker-ipsec-vpn-server#build-from-source-code

Sure.Thanks.
