### ISSUE TITLE
VPN access to docker host -> get home network IP

### ISSUE THREAD

**Issue by LukasVlcek** [hwdsl2/docker-ipsec-vpn-server#183]
Hi,
first of all I would like to thank you for this docker image.
I have a server with a public IPv4: 173.xxx.xxx.xxx and a home network with a public IPv4: 89.xxx.xxx.xxx.
After connecting in VPN I get: 173.xxx.xxx.xxx. 
However, if I access a website hosted on my server via VPN, I see that I am accessing from home IP 89.xxx.xxx.xxx.
Can this behavior be modified to have an IP server - 173.xxx.xxx.xxx?
Thank you for answer.

**Comment by hwdsl2** [comment]
@LukasVlcek Hello! It looks like you are trying to access a website hosted in another Docker container on your Docker host which also hosts the IPsec VPN container. Due to Docker's isolation and routing between containers, I am not sure about your use case.
