### ISSUE TITLE
Use image tag versions

### ISSUE THREAD

**Issue by Shagrat2** [hwdsl2/docker-ipsec-vpn-server#186]
Yesterday updated image VPN stopped working
I wanted to roll back to the old version but you only have the latest

**Comment by hwdsl2** [comment]
@Shagrat2 Thanks for the report. Do you know why the new version stopped working? You can view xl2tpd logs using `docker logs ipsec-vpn-server`, and Libreswan logs using this method [1].

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server#enable-libreswan-logs

**Comment by hwdsl2** [comment]
An image built based on Libreswan 3.29 (previous version in this repo) has been pushed with tag `3.29`. Please try it, then let us know if it works for you.
```
docker pull hwdsl2/ipsec-vpn-server:3.29
```

When using `docker run`, replace `hwdsl2/ipsec-vpn-server` with `hwdsl2/ipsec-vpn-server:3.29`.

**Comment by Shagrat2** [comment]
Perhaps the reason is different
The connection itself works and the server responds to the internal address. But the route does not work

2 days ago everything worked fine

```
,
Trying to auto discover IP of this server...,
,
================================================,
,
IPsec VPN server is now ready for use!,
,
Connect to your new VPN with these details:,
,
Server IP: 5.59.x.x,
IPsec PSK: ?????,
Username: ??,
Password: ???,
,
Write these down. You'll need them to connect!,
,
Important notes:   https://git.io/vpnnotes2,
Setup VPN clients: https://git.io/vpnclients,
,
================================================,
,
Redirecting to: /etc/init.d/ipsec start,
Starting pluto IKE daemon for IPsec: Initializing NSS database,
,
# Warning: iptables-legacy tables present, use iptables-legacy to see them,
.,
xl2tpd[1]: Not looking for kernel SAref support.,
xl2tpd[1]: Using l2tp kernel support.,
xl2tpd[1]: xl2tpd version xl2tpd-1.3.12 started on bc2727090a35 PID:1,
xl2tpd[1]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.,
xl2tpd[1]: Forked by Scott Balmos and David Stipp, (C) 2001,
xl2tpd[1]: Inherited by Jeff McAdams, (C) 2002,
xl2tpd[1]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016,
xl2tpd[1]: Listening on IP address 0.0.0.0, port 1701,
xl2tpd[1]: Connection established to 46.39.x.x, 53076.  Local: 34628, Remote: 4 (ref=0/0).  LNS session is 'default',
xl2tpd[1]: start_pppd: I'm running: ,
xl2tpd[1]: "/usr/sbin/pppd" ,
xl2tpd[1]: "plugin" ,
xl2tpd[1]: "pppol2tp.so" ,
xl2tpd[1]: "pppol2tp" ,
xl2tpd[1]: "7" ,
xl2tpd[1]: "pppol2tp_lns_mode" ,
xl2tpd[1]: "pppol2tp_tunnel_id" ,
xl2tpd[1]: "34628" ,
xl2tpd[1]: "pppol2tp_session_id" ,
xl2tpd[1]: "54500" ,
xl2tpd[1]: "passive" ,
xl2tpd[1]: "nodetach" ,
xl2tpd[1]: "192.168.42.1:192.168.42.10" ,
xl2tpd[1]: "refuse-pap" ,
xl2tpd[1]: "auth" ,
xl2tpd[1]: "require-chap" ,
xl2tpd[1]: "name" ,
xl2tpd[1]: "l2tpd" ,
xl2tpd[1]: "file" ,
xl2tpd[1]: "/etc/ppp/options.xl2tpd" ,
xl2tpd[1]: Call established with 46.39.xx.xx, PID: 295, Local: 54500, Remote: 13202, Serial: 1,
```

Route for MacOS: route -p ADD 172.20.0.0 MASK 255.255.0.0 192.168.42.1

```
> traceroute 172.20.0.5
traceroute to 172.20.0.5 (172.20.0.5), 64 hops max, 52 byte packets
 1  192.168.42.1 (192.168.42.1)  18.865 ms  17.953 ms *
 2  *^C
```

**Comment by hwdsl2** [comment]
This may be related: https://github.com/moby/libnetwork/issues/2331. Is your Docker host running Debian 10 (Buster)? Try the workaround mentioned in that issue, then reboot and re-connect the VPN.

Let us know if it works. If it does not, I can try to push a version with Debian 9 (stretch) for the Docker image (it was upgraded to Debian 10 yesterday).

**Comment by Shagrat2** [comment]
$ hostnamectl
   Static hostname: vr
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 2b287b99126e4096b42b24c5d019bcb0
           Boot ID: 3ffb1a59d0604f35993d58c7598d4e08
    Virtualization: qemu
  Operating System: Debian GNU/Linux 9 (stretch)
            Kernel: Linux 4.9.0-12-amd64
      Architecture: x86-64

**Comment by hwdsl2** [comment]
@Shagrat2 Thanks for the details. I could not reproduce this issue on a fully updated Debian 9 system with same kernel and Docker version `19.03.8`.

More specifically, I don't see this line in the `docker logs ipsec-vpn-server` output:
```
# Warning: iptables-legacy tables present, use iptables-legacy to see them,
```

What was the command that you used to start the Docker container? Did you add `--network=host` (not recommended)? And what is your Docker version? The error above indicates that something is wrong with the IPTables rules in the Docker container (i.e. both `nftables` and "legacy" iptables rules are present).

**Comment by hwdsl2** [comment]
@Shagrat2 Try the Debian 9 based Docker image. You can build it like this:
```
git clone https://github.com/hwdsl2/docker-ipsec-vpn-server.git
cd docker-ipsec-vpn-server
git checkout bd156c4
docker build -t hwdsl2/ipsec-vpn-server:3.31-debian9 .
```
When finished, re-create the Docker container. At the `docker run` step, use the image you just built, e.g. `hwdsl2/ipsec-vpn-server:3.31-debian9`.

Let us know if this works. If so, it would be great if you can provide more information on your setup, to see why the Debian 10 based image does not work.

Since the new Libreswan version is not the root cause for your issue, I plan to remove the `3.29` tag from Docker Hub.

**Comment by Shagrat2** [comment]
> @Shagrat2 Thanks for the details. I could not reproduce this issue on a fully updated Debian 9 system with same kernel and Docker version `19.03.8`.
> 
> More specifically, I don't see this line in the `docker logs ipsec-vpn-server` output:
> 
> ```
> # Warning: iptables-legacy tables present, use iptables-legacy to see them,
> ```
> 
> What was the command that you used to start the Docker container? Did you add `--network=host` (not recommended)? And what is your Docker version? The error above indicates that something is wrong with the IPTables rules in the Docker container (i.e. both `nftables` and "legacy" iptables rules are present).

3.29 Logs - Route not work

```
$ iptables-legacy
bash: iptables-legacy: command not found

$ docker -v
Docker version 19.03.8, build afacb8b7f0
```

```
services:
  ipsec-vpn-server:
    image: hwdsl2/ipsec-vpn-server:3.31-debian9
    container_name: ?_vpn
    restart: always
    privileged: true
    env_file:
      - ./vpn.env
    environment:
      - /lib/modules:/lib/modules
    ports:
      - 500:500/udp
      - 4500:4500/udp
    networks: 
      vpn:
        ipv4_address: 172.20.0.205

networks:
  vr-net:
    driver: bridge
    name: vr-net
  vpn:
    driver: bridge
    name: vpn
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.210/16
```

```
===============================================,
,
IPsec VPN server is now ready for use!,
,
Connect to your new VPN with these details:,
,
Server IP: 5.59.x.x,
IPsec PSK: ?,
Username: ?,
Password: ?,
,
Write these down. You'll need them to connect!,
,
Important notes:   https://git.io/vpnnotes2,
Setup VPN clients: https://git.io/vpnclients,
,
================================================,
,
Redirecting to: /etc/init.d/ipsec start,
# Warning: iptables-legacy tables present, use iptables-legacy to see them,
Starting pluto IKE daemon for IPsec: .,
xl2tpd[1]: Not looking for kernel SAref support.,
xl2tpd[1]: Using l2tp kernel support.,
xl2tpd[1]: xl2tpd version xl2tpd-1.3.12 started on bc2727090a35 PID:1,
xl2tpd[1]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.,
xl2tpd[1]: Forked by Scott Balmos and David Stipp, (C) 2001,
xl2tpd[1]: Inherited by Jeff McAdams, (C) 2002,
xl2tpd[1]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016,
xl2tpd[1]: Listening on IP address 0.0.0.0, port 1701,
xl2tpd[1]: Connection established to 46.39.x.x, 55238.  Local: 12582, Remote: 5 (ref=0/0).  LNS session is 'default',
xl2tpd[1]: start_pppd: I'm running: ,
xl2tpd[1]: "/usr/sbin/pppd" ,
xl2tpd[1]: "plugin" ,
xl2tpd[1]: "pppol2tp.so" ,
xl2tpd[1]: "pppol2tp" ,
xl2tpd[1]: "7" ,
xl2tpd[1]: "pppol2tp_lns_mode" ,
xl2tpd[1]: "pppol2tp_tunnel_id" ,
xl2tpd[1]: "12582" ,
xl2tpd[1]: "pppol2tp_session_id" ,
xl2tpd[1]: "33314" ,
xl2tpd[1]: "passive" ,
xl2tpd[1]: "nodetach" ,
xl2tpd[1]: "192.168.42.1:192.168.42.10" ,
xl2tpd[1]: "refuse-pap" ,
xl2tpd[1]: "auth" ,
xl2tpd[1]: "require-chap" ,
xl2tpd[1]: "name" ,
xl2tpd[1]: "l2tpd" ,
xl2tpd[1]: "file" ,
xl2tpd[1]: "/etc/ppp/options.xl2tpd" ,
xl2tpd[1]: Call established with 46.39.x.x, PID: 291, Local: 33314, Remote: 20381, Serial: 1,
```

**Comment by Shagrat2** [comment]
hwdsl2/ipsec-vpn-server:3.31-debian9 - work OK!

,
Trying to auto discover IP of this server...,
,
================================================,
,
IPsec VPN server is now ready for use!,
,
Connect to your new VPN with these details:,
,
Server IP: 5.59.x.x,
IPsec PSK: ?,
Username: ?,
Password: ?,
,
Write these down. You'll need them to connect!,
,
Important notes:   https://git.io/vpnnotes2,
Setup VPN clients: https://git.io/vpnclients,
,
================================================,
,
Redirecting to: /etc/init.d/ipsec start,
Starting pluto IKE daemon for IPsec: Initializing NSS database,
,
.,
xl2tpd[1]: Not looking for kernel SAref support.,
xl2tpd[1]: Using l2tp kernel support.,
xl2tpd[1]: xl2tpd version xl2tpd-1.3.12 started on 67e4d0c5a781 PID:1,
xl2tpd[1]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.,
xl2tpd[1]: Forked by Scott Balmos and David Stipp, (C) 2001,
xl2tpd[1]: Inherited by Jeff McAdams, (C) 2002,
xl2tpd[1]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016,
xl2tpd[1]: Listening on IP address 0.0.0.0, port 1701,
xl2tpd[1]: Connection established to 46.39.x.x, 51987.  Local: 64410, Remote: 6 (ref=0/0).  LNS session is 'default',
xl2tpd[1]: start_pppd: I'm running: ,
xl2tpd[1]: "/usr/sbin/pppd" ,
xl2tpd[1]: "plugin" ,
xl2tpd[1]: "pppol2tp.so" ,
xl2tpd[1]: "pppol2tp" ,
xl2tpd[1]: "7" ,
xl2tpd[1]: "pppol2tp_lns_mode" ,
xl2tpd[1]: "pppol2tp_tunnel_id" ,
xl2tpd[1]: "64410" ,
xl2tpd[1]: "pppol2tp_session_id" ,
xl2tpd[1]: "14670" ,
xl2tpd[1]: "passive" ,
xl2tpd[1]: "nodetach" ,
xl2tpd[1]: "192.168.42.1:192.168.42.10" ,
xl2tpd[1]: "refuse-pap" ,
xl2tpd[1]: "auth" ,
xl2tpd[1]: "require-chap" ,
xl2tpd[1]: "name" ,
xl2tpd[1]: "l2tpd" ,
xl2tpd[1]: "file" ,
xl2tpd[1]: "/etc/ppp/options.xl2tpd" ,
xl2tpd[1]: Call established with 46.39.x.x, PID: 304, Local: 14670, Remote: 47491, Serial: 1,
