### ISSUE TITLE
大兄弟、大佬，能指导下关闭PSK吗

### ISSUE THREAD

**Issue by cdoer** [hwdsl2/docker-ipsec-vpn-server#188]
我的路由器不支持PSK，我尝试修改run.sh这个文件 ，改一些参数，比如authby=nerver,
删掉配置
cat > /etc/ipsec.secrets <<EOF
$PUBLIC_IP  %any  : PSK "$VPN_IPSEC_PSK"
EOF

能正常运行，但是无法连接

**Comment by hwdsl2** [comment]
@cdoer 你好！不支持关闭L2TP的预共享秘钥，因为不带 IPsec 的 L2TP 模式没有任何加密，使用 VPN 也就失去了意义。

**Comment by cdoer** [comment]
@hwdsl2    感谢回复，不为加密，只为组网。  翻了其它的issues ，看到不少同样的问题，那只能放弃了。

**Comment by TomLiu-GitHub** [comment]
同样的问题!
华为路由器不支持PSK
![image](https://user-images.githubusercontent.com/32833966/120316329-e347ee80-c30f-11eb-8807-8be1ce345c71.png)
