### ISSUE TITLE
FATAL ERROR using docker image

### ISSUE THREAD

**Issue by joanbono** [hwdsl2/docker-ipsec-vpn-server#19]
Some messages:

~~~~
pluto[2619]: FATAL ERROR: Failed to bind bcast socket in init_netlink() - Perhaps kernel was not compiled with CONFIG_XFRM. Errno 1: Operation not permitted

pluto[3576]: FATAL ERROR: Failed to bind bcast socket in init_netlink() - Perhaps kernel was not compiled with CONFIG_XFRM. Errno 1: Operation not permitted

pluto[3895]: FATAL ERROR: Failed to bind bcast socket in init_netlink() - Perhaps kernel was not compiled with CONFIG_XFRM. Errno 1: Operation not permitted

pluto[5171]: FATAL ERROR: Failed to bind bcast socket in init_netlink() - Perhaps kernel was not compiled with CONFIG_XFRM. Errno 1: Operation not permitted
~~~~ 

Docker versio:

~~~~
$ docker -v
Docker version 1.12.5, build 7392c3b
~~~~

**Comment by hwdsl2** [comment]
@joanbono Hello! What is your host OS version (e.g. Ubuntu 14.04) and kernel version (`uname -a`)? What command did you use to start the docker container? It looks like your server's kernel is missing some support for IPsec XFRM (see: [1] [2]).

[1] https://lists.openswan.org/pipermail/users/2009-February/016168.html
[2] https://lists.openswan.org/pipermail/users/2007-November/013480.html

**Comment by joanbono** [comment]
Maybe that's the problem... I'm using a Mac OS X 10.11.6 x86_64.

The program works fine (the script), running on a Debian 8.6, by the way.

If you're not going to solve that, no problem, will use docker for Debian inside a VM.

**Comment by hwdsl2** [comment]
@joanbono Thanks for the update. The VPN container was only designed for use with Linux as the Docker host. Therefore please use the alternative approach you mentioned (docker for Debian inside a VM).

**Comment by wahbigbig** [comment]
having the same issue when trying to run the installation script inside a container in resin/rpi-raspbian in Pi3

**Comment by hwdsl2** [comment]
@joanbono Hello there! The VPN setup scripts are not designed to be used in your scenario (inside a container in resin/rpi-raspbian in Pi3). It could work outside the container by installing on the RPi directly.

**Comment by wahbigbig** [comment]
@hwdsl2 yes, i know, just wondering any solution to fix it so i can run it on my Pi container

**Comment by adam-nielsen** [comment]
If anyone else is here from Google, I had to run the Docker container with the `--privileged` flag to fix this problem.
