### ISSUE TITLE
L2TP kernel support not detected

### ISSUE THREAD

**Issue by sahandMg** [hwdsl2/docker-ipsec-vpn-server#196]
Hi. I'm getting this error in container log :
xl2tpd[1]: L2TP kernel support not detected (try modprobing l2tp_ppp and pppol2tp)
Can't connect to vpn.

**Comment by hwdsl2** [comment]
@sahandMg Hello! `L2TP kernel support not detected` means your Docker host does not have IPsec/L2TP kernel support, see [1] for more info. This message can be safely ignored and does not affect the VPN functionality. You may troubleshoot further by enabling the Libreswan (IPsec) logs [2]. If no new logs appear after attempting to connect, then traffic did not reach your VPN server.

[1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes
[2] https://github.com/hwdsl2/docker-ipsec-vpn-server#enable-libreswan-logs
