### ISSUE TITLE
Connection refused [errno 111, origin ICMP type 3 code 3 (not authenticated)]

### ISSUE THREAD

**Issue by sahandMg** [hwdsl2/docker-ipsec-vpn-server#197]
Hi,
I've enabled Libreswan logs and I'm getting this logs :

Jun  2 20:35:09 e77969297517 pluto[1683]: "l2tp-psk"[1] 5.115.57.59 #1: STATE_MAIN_R2: retransmission; will wait 0.5 seconds for response
Jun  2 20:35:09 e77969297517 pluto[1683]: "l2tp-psk"[1] 5.115.57.59 #1: STATE_MAIN_R2: retransmission; will wait 1 seconds for response
Jun  2 20:35:10 e77969297517 pluto[1683]: "l2tp-psk"[1] 5.115.57.59 #1: STATE_MAIN_R2: retransmission; will wait 2 seconds for response
Jun  2 20:35:12 e77969297517 pluto[1683]: "l2tp-psk"[1] 5.115.57.59 #1: STATE_MAIN_R2: retransmission; will wait 4 seconds for response
Jun  2 20:35:16 e77969297517 pluto[1683]: "l2tp-psk"[1] 5.115.57.59 #1: STATE_MAIN_R2: retransmission; will wait 8 seconds for response
Jun  2 20:35:24 e77969297517 pluto[1683]: "l2tp-psk"[1] 5.115.57.59 #1: STATE_MAIN_R2: retransmission; will wait 16 seconds for response
Jun  2 20:35:40 e77969297517 pluto[1683]: "l2tp-psk"[1] 5.115.57.59 #1: STATE_MAIN_R2: retransmission; will wait 32 seconds for response
Jun  2 20:35:40 e77969297517 pluto[1683]: "l2tp-psk"[1] 5.115.57.59 #1: ERROR: asynchronous network error report on eth0 (172.17.0.3:500) for message to 5.115.57.59 port 43808, complainant 5.115.57.59: Connection refused [errno 111, origin ICMP type 3 code 3 (not authenticated)].

still can not connect :(

**Comment by hwdsl2** [comment]
@sahandMg Hello! The retransmission errors typically indicate that there are network issues between your VPN client and VPN server. Try connecting from a different network. You may also want to look into alternative solutions such as OpenVPN [1] or Shadowsocks [2].

[1] https://github.com/Nyr/openvpn-install
[2] https://shadowsocks.org
