### ISSUE TITLE
Hello, I have a question about the VPN_IPSEC_PSK

### ISSUE THREAD

**Issue by yaozhongnan** [hwdsl2/docker-ipsec-vpn-server#198]
I successfully set up this VPN server according to the document.

It can be successfully connected on my Win10.

Now I want my router to connect to it too.

But the router's connection page does not have the VPN_IPSEC_PSK field, win10 have

So I can't connect.

What should I do?

**Comment by hwdsl2** [comment]
@yaozhongnan Hello! If your router does not support IPsec PSK, then it cannot be used with this VPN server. Note that L2TP without IPsec is not supported, because traffic is not encrypted at all in this mode.
