### ISSUE TITLE
Reach another Docker Image through VPN only.

### ISSUE THREAD

**Issue by MaskedUserXYZ** [hwdsl2/docker-ipsec-vpn-server#200]
Hi, I have another Docker Image runs as "mail-server" and I want to make that Image **accessible through VPN only**, in the same while I want to make sure that it sends/receives emails.

in general, if I have an application runs on the VPN server network, can I make it accessible through VPN only?

I think the following could be the solution:
1. runs the Mail Server Image(1) on the same VPN Image(2) network.
2. redirect the traffic of (1) to pass through (2) (by editing the routing table I think).
3. connect to the VPN, use exposed ports to access to (1).

**Comment by hwdsl2** [comment]
@MaskedUserXYZ Hello! Similar questions were asked before in this repo. Due to Docker's network isolation among containers on the same host, unfortunately I am not aware of a working solution for your use case.

**Comment by MaskedUserXYZ** [comment]
No problem, I will do the work by my self.
I'm looking to know, does it possible or not?
Thank you.
