### ISSUE TITLE
功能需求： 官方可以出一个docker-ipsec-vpn-client镜像吗

### ISSUE THREAD

**Issue by ifooth** [hwdsl2/docker-ipsec-vpn-server#201]
找了个client镜像，很久没有更新了，能否官方也出一个对应的client镜像呢？ 谢谢了
https://github.com/emmdim/docker-ipsec-vpn-client

优势：
- 统一下入口
- 可以同步更新client的包版本
- 方便测试VPN效果等

**Comment by hwdsl2** [comment]
@ifooth 感谢你的建议。在 Docker 容器中连接 IPsec VPN 实际用处不大，因为 Docker 的网络隔离，在容器中连接 VPN 之后，Docker 主机并不能通过 VPN 上网。所以创建 client 镜像的意义不大。如果你需要在 Linux 下连接 VPN （也包括使用命令行配置），请参见 [1]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#linux
