### ISSUE TITLE
when i try to connect by macos 10.13

### ISSUE THREAD

**Issue by r6c** [hwdsl2/docker-ipsec-vpn-server#202]
```
xl2tpd[1]: Call established with x.x.x.x, PID: 294, Local: 6948, Remote: 852, Serial: 1
/usr/sbin/pppd: You need to create the /dev/ppp device node by
executing the following command as root:
        mknod /dev/ppp c 108 0
xl2tpd[1]: child_handler : pppd exited for call 852 with code 4
xl2tpd[1]: call_close: Call 6948 to x.x.x.x disconnected
xl2tpd[1]: result_code_avp: result code endianness fix for buggy Apple client. network=768, le=3
xl2tpd[1]: control_finish: Connection closed to x.x.x.x, serial 1 ()
xl2tpd[1]: Terminating pppd: sending TERM signal to pid 294
xl2tpd[1]: result_code_avp: result code endianness fix for buggy Apple client. network=256, le=1
xl2tpd[1]: control_finish: Connection closed to x.x.x.x, port 61294 (), Local: 47339, Remote: 30
```

**Comment by r6c** [comment]
my docker command

```shell
docker run \
    --name vpn \
    --env-file ./vpn.env \
    --restart=always \
    -p 500:500/udp \
    -p 4500:4500/udp \
    -d --privileged \
    hwdsl2/ipsec-vpn-server
```

**Comment by hwdsl2** [comment]
@r6c What is your Docker host's operating system (e.g. Debian 10)? Also can you run this command on your Docker host to check its Linux kernel version?
```
uname -a
```
I suspect that this may be caused by an issue with the "cloud" version of Debian 10 kernel. See:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#debian-10-kernel

**Comment by r6c** [comment]
My Docker host is Debian10

**Comment by hwdsl2** [comment]
@r6c To fix, please switch to the standard Linux kernel on your Docker host, by installing e.g. the `linux-image-amd64` package. Then update the default kernel in GRUB and reboot. See [1].

Alternatively, if you don't want to change to the standard Linux kernel, you can still use IPsec/XAuth ("Cisco IPsec") or IKEv2 modes [1], but not IPsec/L2TP mode.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#debian-10-kernel
[2] https://github.com/hwdsl2/setup-ipsec-vpn#next-steps
