### ISSUE TITLE
你好，请问使用docker部署是否支持在nat环境下部署使用

### ISSUE THREAD

**Issue by cdy668** [hwdsl2/docker-ipsec-vpn-server#203]
服务端：centos7
客户端：windows7
我这边遇到一个问题，在windows7系统上面连接ipsec的时候报告了一个789的错误提示

使用nc命令测试公网映射的udp端口是OK的
nc -vuz xx.xx.xx.xx 500
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to xx.xx.xx.xx:500.
Ncat: UDP packet sent successfully
Ncat: 1 bytes sent, 0 bytes received in 2.07 seconds.

nc -vuz xx.xx.xx.xx 4500
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to xx.xx.xx.xx:4500.
Ncat: UDP packet sent successfully
Ncat: 1 bytes sent, 0 bytes received in 2.02 seconds.

**Comment by hwdsl2** [comment]
@cdy668 你好！可以在 NAT 环境下部署，但要确保服务器的 UDP 500 和 4500 端口可以通过客户端访问。请再次尝试连接 VPN 客户端，然后检查一下服务器日志是否有错误 [1]。另外可以尝试这些解决方案 [2]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%A3%80%E6%9F%A5%E6%97%A5%E5%BF%97%E5%8F%8A-vpn-%E7%8A%B6%E6%80%81
[2] https://documentation.meraki.com/MX/Client_VPN/Troubleshooting_Client_VPN#Windows_Error_789
