### ISSUE TITLE
VPN not working after iOS 14 upgrade

### ISSUE THREAD

**Issue by liweizhi** [hwdsl2/docker-ipsec-vpn-server#205]
refer the issue: https://github.com/hwdsl2/setup-ipsec-vpn/issues/862.
Although it seems I can do a workaround by editing the value sha2-truncbug of file ipsec.conf in the container. But If I create a new container from the image, the original value will be back. So I think it should be solved and reflected in the docker image.

**Comment by Scarecrow928** [comment]
The latest image has already changed the sha2-truncbug to “no”, but my iOS 14 device is still not working with it😅

**Comment by hwdsl2** [comment]
Thanks for reporting this issue. Please refer to my comment in https://github.com/hwdsl2/setup-ipsec-vpn/issues/862#issuecomment-720262079.
