### ISSUE TITLE
How to for WSL

### ISSUE THREAD

**Issue by johnwmail** [hwdsl2/docker-ipsec-vpn-server#206]
Hi, Is this docker work on wsl2/windows docker desktop?
if yes, is there any different to setup?
Thanks.

**Comment by usmcfiredog** [comment]
everything should be the same you will probably have to open up the ports on the windows firewall as well

**Comment by johnwmail** [comment]
![image](https://user-images.githubusercontent.com/1752235/95548958-c8e79a80-0a38-11eb-8c6c-c6da1bd49452.png)

Is this a problem?  no related modules on windows docker desktop.
Thanks.

**Comment by johnwmail** [comment]
root@26625804dcd6:/var/log# ipsec whack --trafficstatus
006 #7: "xauth-psk"[6] 172.17.0.1, username=johnwmail, type=ESP, add_time=1602383327, inBytes=0, outBytes=0, lease=192.168.43.10/32

I can login with android phone, but the phone cannot make any connection via vpn.

-----------------------------
Chain INPUT (policy ACCEPT 6332 packets, 9170K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID
    0     0 ACCEPT     all  --  eth+   ppp+    0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  ppp+   eth+    0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  ppp+   ppp+    192.168.42.0/24      192.168.42.0/24
    0     0 ACCEPT     all  --  eth+   *       0.0.0.0/0            192.168.43.0/24      ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  *      eth+    192.168.43.0/24      0.0.0.0/0
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 3032 packets, 129K bytes)
 pkts bytes target     prot opt in     out     source               destination
---------------------------------------
root@26625804dcd6:/var/log# iptables -t nat -L -nv
Chain PREROUTING (policy ACCEPT 5 packets, 2584 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 5 packets, 2584 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 15 packets, 1004 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 15 packets, 1004 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 MASQUERADE  all  --  *      eth+    192.168.42.0/24      0.0.0.0/0
----------------------------------------------------------------------------------
any idea?
anyone successes host the ipsec-docker on windows(docker desktop)?   
thanks.

**Comment by hwdsl2** [comment]
@johnwmail Hello! This Docker image does not yet support windows Docker desktop/WSL2. The L2TP kernel support message from your screenshot is normal, however. It's not required for the VPN to work.
