### ISSUE TITLE
Using your own certificates for IKEv2

### ISSUE THREAD

**Issue by eggbean** [hwdsl2/docker-ipsec-vpn-server#208]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x] This enhancement request is about the IPsec VPN server Docker image, and not IPsec VPN itself
- [x] I read the [README](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting), [enabled logs](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#enable-libreswan-logs) and checked [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

Has anybody changed the IKEv2 setup script to work with your own self-signed certificates? I want to be able to use the same CA and client certificates as I do for other VPN connections.

There are a lot of forks, so I have been unable to go through them all to see if anybody has already done this.

**Comment by hwdsl2** [comment]
@eggbean Hello! Your use case would require importing your existing CA and client certificate(s) as well as private key(s) into the Libreswan certificate store. I'm not sure about the details, I'd suggest that you ask on the Libreswan users mailing list [1].

[1] https://lists.libreswan.org/mailman/listinfo/swan
