### ISSUE TITLE
Couldn't detect public IP

### ISSUE THREAD

**Issue by attinderdhillon** [hwdsl2/docker-ipsec-vpn-server#210]
It is a ubuntu minimal instance on oracle cloud. 

I have installed dns-utils and can get the public ip with 'dig @resolver1.opendns.com -t A -4 myip.opendns.com +short'

I've also tried defining VPN_PUBLIC_IP in "--env-file ./vpn.env"

```
docker start -a ipsec-vpn-server

Trying to auto discover IP of this server...
dig: couldn't get address for 'resolver1.opendns.com': failure
Error: Cannot detect this server's public IP. Define it in your 'env' file as 'VPN_PUBLIC_IP'.
```

**Comment by hwdsl2** [comment]
@attinderdhillon Hello! This may indicate network access problems from within your Docker container. If you read the source code, the `run.sh` script tries to detect your server's public IP using both DNS and HTTP methods. Can you test using another Docker image that you are able to access the network (including resolving DNS) from within containers?

**Comment by attinderdhillon** [comment]
After recreating instance and installing image It is working perfectly now. Must be an issue at my end.
