### ISSUE TITLE
connection attemp failed--ios13

### ISSUE THREAD

**Issue by meitianjinbu** [hwdsl2/docker-ipsec-vpn-server#214]
deploy it on local pc.
docker-compose run the image.
yml:
version: '3'
services:
  vpn:
    image: hwdsl2/ipsec-vpn-server
    restart: always
    env_file:
      - ./vpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
    network_mode: host

**Comment by hwdsl2** [comment]
@meitianjinbu Hello! Please enable Libreswan logs, try to re-connect the VPN, then check the logs for errors. If no new logs appear after re-connecting, then traffic did not reach your VPN server.

If you deploy on local PC, be sure to set up port forwarding on your (home) router to forward both UDP port 500 and UDP port 4500 to your PC's local IP. Also please consider removing "network_mode: host" from your configuration, as this mode currently has some issues #207.

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server#enable-libreswan-logs
