### ISSUE TITLE
可以默认把IKEV2装进去吗？

### ISSUE THREAD

**Issue by nickelzhang** [hwdsl2/docker-ipsec-vpn-server#224]
高级用法有点麻烦，，，能不能简化一下

**Comment by hwdsl2** [comment]
@nickelzhang 感谢你的建议。默认安装 IKEv2 这个想法很好，但目前短期内没有时间来做这个改进。该方案需要考虑一些问题，比如在运行容器时添加参数以挂载 IKEv2 容器，为 IKEv2 添加额外的 `env` 变量，怎样自动添加 IKEv2 用户，等等。
