### ISSUE TITLE
Verify vpn users via docker logs

### ISSUE THREAD

**Issue by rongliu1029** [hwdsl2/docker-ipsec-vpn-server#229]
Not sure if I missed something. But i cannot find if the login user info is logged.
I want to know if there is any way to check the vpn username in the docker log after the connection is established.
Kindly help when available.
Much appreciate.

**Comment by hwdsl2** [comment]
@rongliu1029 Hello! Libreswan logs are not enabled by default. To enable, see:
https://github.com/hwdsl2/docker-ipsec-vpn-server#enable-libreswan-logs

After enabling you'll see usernames for IPsec/XAuth ("Cisco IPsec") mode in the logs. For IPsec/L2TP, it is not possible to see usernames in Libreswan logs. You can enable debug option for xl2tpd, see: https://github.com/hwdsl2/setup-ipsec-vpn/issues/803
