### ISSUE TITLE
Constant Restarting

### ISSUE THREAD

**Issue by bport95** [hwdsl2/docker-ipsec-vpn-server#23]
I am trying to run this docker image on my Raspberry Pi 3 running Raspbian Pixel. The container seems like it is constantly restarting and not actually running. I am not sure if this is specific to the raspberry pi because I have run this docker image on other machines with no issues at all.

**Comment by hwdsl2** [comment]
@bport95 Hello! Thanks for the report. You can check for any error message generated by the Docker container with:
```
docker logs ipsec-vpn-server
```

Alternatively you can try setting up the VPN server directly on your Raspberry Pi 3, without using Docker. See: https://github.com/hwdsl2/setup-ipsec-vpn
