### ISSUE TITLE
无法连接vpn排查

### ISSUE THREAD

**Issue by wideweide** [hwdsl2/docker-ipsec-vpn-server#231]
**任务列表**

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#下一步)
- [x] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除)，[启用日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#启用-libreswan-日志) 并查看了 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue)
- [x] 这个 bug 是关于 IPsec VPN 服务器 Docker 镜像，而不是 IPsec VPN 本身

**问题描述**
1. 不确定vpn server是否工作正常
2. 无法使用windows远程连接

**重现步骤**
1. docker启动参数删除了，带着我这边启动不了： -v ikev2-vpn-data:/etc/ipsec.d \
2. docker logs ipsec-vpn-server -f 中有些信息看上去有异常
```

Trying to auto discover IP of this server...

================================================

IPsec VPN server is now ready for use!

Connect to your new VPN with these details:

Server IP: *.*.*.*
IPsec PSK: ***
Username: ****
Password: ***

Write these down. You'll need them to connect!

Important notes:   https://git.io/vpnnotes2
Setup VPN clients: https://git.io/vpnclients
IKEv2 guide:       https://git.io/ikev2docker

================================================

Redirecting to: /etc/init.d/ipsec start
Starting pluto IKE daemon for IPsec: Initializing NSS database

.
xl2tpd[1]: Not looking for kernel SAref support.   ----------这里看上去像是有问题
xl2tpd[1]: L2TP kernel support not detected (try modprobing l2tp_ppp and pppol2tp)  --这里。。
xl2tpd[1]: xl2tpd version xl2tpd-1.3.12 started on 07f754400e5f PID:1
xl2tpd[1]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
xl2tpd[1]: Forked by Scott Balmos and David Stipp, (C) 2001
xl2tpd[1]: Inherited by Jeff McAdams, (C) 2002
xl2tpd[1]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016
xl2tpd[1]: Listening on IP address 0.0.0.0, port 1701  ---是否算是正常工作了？

```
3. docker ps |grep ipsec
`07f754400e5f        hwdsl2/ipsec-vpn-server        "/opt/src/run.sh"        41 minutes ago      Up 41 minutes       0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   ipsec-vpn-server`

4. nc -vuz 172.17.0.1 500
```
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 172.17.0.1:500.
Ncat: UDP packet sent successfully
Ncat: 1 bytes sent, 0 bytes received in 2.01 seconds.
```
5. 防火墙端口开放500、4500、1701（貌似并不需要？）
6. 客户端测试500端口nc -vuz 公网ip 500
```
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to IP***:500.
Ncat: UDP packet sent successfully
Ncat: 1 bytes sent, 0 bytes received in 2.03 seconds.
```
**注：测试500端口过程中，docker logs ..中无任何输出**
7. windows新建vpn连接：使用预共享密钥的L2TP/IPSec，只写了ip地址，按照说明改了一些注册表及安全策略

```
无法连接到L2TP
无法建立计算机与VPN服务器之间的网络连接，因为远程服务器未响应。这可能是因为未将计算机与远程服务器之间的某种网络设备(如防火墙、NAT、 路由器等)配置为允许VPN连接。请与管理员或服务提供商联系以确定哪种设备可能产生此问题。
```

**期待的正确结果**
求指点...

**日志**
[启用日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#启用-libreswan-日志)，检查 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)，并且添加错误日志以帮助解释该问题（如果适用）。

**服务器信息（请填写以下信息）**
- Docker 主机操作系统: [Centos8]
- 服务提供商（如果适用）: [阿里云]

**客户端信息（请填写以下信息）**
- 设备: [笔记本]
- 操作系统: [windows10]
- VPN 模式: [IPsec/L2TP]

**其它信息**
添加关于该 bug 的其它信息。

**Comment by wideweide** [comment]
android能连，估计win10问题...

**Comment by hwdsl2** [comment]
@wideweide 你好！请问添加 `-v ikev2-vpn-data:/etc/ipsec.d` 参数无法启动的原因或具体错误是什么？你的Docker容器日志正常。不需要开放1701端口。Windows错误请参见故障排除中的Windows错误809解决方案。

**Comment by wideweide** [comment]
@hwdsl2 

> 添加 `-v ikev2-vpn-data:/etc/ipsec.d` 参数无法启动的原因或具体错误是什么？

**可能是网络原因，也可能是缺乏一点耐心……**

第一次执行的时候卡在 Setting up IKEv2, please wait...
等了一会儿也没有出来，我就强制终止并删除了那行参数

android很顺利的就连上了，win10参考文档修复了注册表等问题后也成功连接上了
在centos7/8上尝试了l2tp/xauth，都没有连上
再次尝试加上-v ikev2-vpn-data:/etc/ipsec.d，这次多等了一会儿就成功了：

IKEv2 setup successful. Details for IKEv2 mode:...

然而貌似并没有linux上如何使用IKEv2的文档说明，准备开个新问题...
