### ISSUE TITLE
why cann't connect to a specific site through vpn?

### ISSUE THREAD

**Issue by shadowhenry** [hwdsl2/docker-ipsec-vpn-server#234]
**Checklist**

- [ ] I read the [README](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md)
- [ ] I read the [Important notes](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#important-notes)
- [ ] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#next-steps)
- [ ] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting), [enabled logs](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#enable-libreswan-logs) and checked [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [ ] I searched existing [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue)
- [ ] This bug is about the IPsec VPN server Docker image, and not IPsec VPN itself

**Describe the issue**

**To Reproduce**

1. ...
2. ...

**Expected behavior**

**Logs**
[Enable logs](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#enable-libreswan-logs), check [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- Docker host OS: [e.g. Ubuntu 20.04]
- Hosting provider (if applicable): [e.g. GCP, AWS]

**Client (please complete the following information)**
- Device: [e.g. iPhone 8]
- OS: [e.g. iOS 13.6]
- VPN mode: [IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") or IKEv2]

**Additional context**

**Comment by hwdsl2** [comment]
@shadowhenry Hello! If you cannot connect to a specific site through VPN, but other sites work fine, it is most likely that the specific site blocks traffic originating from the VPN server. For example, some websites may block traffic from VPN providers, or have country related restrictions. This does not indicate a problem with this Docker image.

**Comment by shadowhenry** [comment]
![image](https://user-images.githubusercontent.com/8598699/111869564-20f8d480-89bb-11eb-9156-a71258ba950c.png)

Well, according to this picture, if you curl a site with referrer, you can get the content. if not, it returns a '403'.  
Does this mean if the vpn server gets the target site content with a referrer in the header, the problem will be solved.
