### ISSUE TITLE
LAN Connection to other client.

### ISSUE THREAD

**Issue by SonerOd** [hwdsl2/docker-ipsec-vpn-server#238]
Hi there,

Can I connect to other computer with this VPN connection ? I've tried but not working. Is there has any method ?

**Comment by hwdsl2** [comment]
@SonerOd Hello! If you want to connect to other VPN client(s) that are connected to the same VPN server, please refer to [1]. If unable to connect, the traffic is most likely blocked (disallowed) by the firewall on the other VPN client.

[1] https://github.com/hwdsl2/setup-ipsec-vpn#internal-vpn-ips
