### ISSUE TITLE
阿里云香港服务器搭建的IPSEC VPN ，使用MAc无法连接

### ISSUE THREAD

**Issue by xiaomiwujiecao** [hwdsl2/docker-ipsec-vpn-server#24]
一直提示服务器没有响应，
然后自己也根据网上的说明配置了文件，
但是还是无法连接上，请问这是真么回事

**Comment by maikebing** [comment]
docker 建的吗？
我的也不行， 不知道为什么！

**Comment by xiaomiwujiecao** [comment]
我觉得阿里云的外网给屏蔽了，docker 和直接在服务器上安装我都试过了

**Comment by hwdsl2** [comment]
@xiaomiwujiecao 你好！感谢反馈。我没有阿里云账户无法测试这个问题。建议你再尝试一下其他的云服务提供商。

**Comment by hwdsl2** [comment]
@xiaomiwujiecao 另外请参见这个 Issue ：
https://github.com/hwdsl2/setup-ipsec-vpn/issues/137#issuecomment-298255493

**Comment by xiaomiwujiecao** [comment]
好的 我试试
