### ISSUE TITLE
Docker for Mac support?

### ISSUE THREAD

**Issue by niksy** [hwdsl2/docker-ipsec-vpn-server#240]
Documentation says:

> Note: This image does not support Docker for Mac or Windows.

I’ve successfully managed to create VPN server on macOS Docker. Is there something else we should know about using this on Docker for Mac or is this old information and it has been resolved in the meantime?

**Comment by hwdsl2** [comment]
@niksy Hello! Thanks for trying this Docker image on macOS. I'm glad that it works fine for you. The note you mentioned may be outdated because recently I have not tested this Docker image on macOS. So this is just old information that needs to be updated.

**Comment by lishuda** [comment]
> Documentation says:
> 
> > Note: This image does not support Docker for Mac or Windows.
> 
> I’ve successfully managed to create VPN server on macOS Docker. Is there something else we should know about using this on Docker for Mac or is this old information and it has been resolved in the meantime?

Hello, could you tell me how to config docker container on mac os? I have googled but nothing found.
