### ISSUE TITLE
helm variant for kubernetes deployment

### ISSUE THREAD

**Issue by pogzie** [hwdsl2/docker-ipsec-vpn-server#243]
**Describe the enhancement request**
I saw that @ChrisPhillips-cminion tried to do a helm version for kubernetes deployment. Unfortunately the last update on that was 2018. Will there be a version of this pushed as a helm chart? 

**Is your enhancement request related to a problem? Please describe.**
No.

**Additional context**
As many people are setting up Kubernetes home servers, I was wondering if it would be worth the time to create an official helm chart for this.

**Comment by hwdsl2** [comment]
@pogzie Thank you for your suggestion! It's a nice to have feature, but currently there is no plan to implement it. For now, you'll need to create a helm chart yourself if your use case requires it.
