### ISSUE TITLE
Fail-safe ikev2

### ISSUE THREAD

**Issue by feelan03** [hwdsl2/docker-ipsec-vpn-server#244]
Hello. I have a question, is it possible to make ikev2 fault-tolerant like it can be done with openvpn. To make openvpn fail-safe, you need to make a complete copy of the finished server, with all the certificates and if you specify the domain from two machines in the certificate, then balancing will work. Is it possible to do this on ikev2?

**Comment by hwdsl2** [comment]
@feelan03 Hello! For IKEv2, there is a feature called "redirect", which sounds similar to your use case. Please refer to:
https://libreswan.org/wiki/RFC_5685_-_Redirect_Mechanism
https://libreswan.org/man/ipsec.conf.5.html

I haven't used this before, you can search the Internet for examples, or ask on the Libreswan users mailing list:
https://lists.libreswan.org/mailman/listinfo/swan
