### ISSUE TITLE
如何使ipsec支持远程dlna及ios的屏幕镜像？

### ISSUE THREAD

**Issue by yyysuo** [hwdsl2/docker-ipsec-vpn-server#248]
主路由：10.10.10.1
docker主机：10.10.10.100
vpn模式：L2TP/ipsec
子网：192.168.42.0/24

现象：因为连接VPN的设备与主路由不属于同一网段，dlna及屏幕镜像时无法搜索到家中局域网设备，阅读使用说明时提到连接VPN设备分配到的IP必须是192.168.42.X。

需求：请问是否能通过配置来实现远程dlna？

**Comment by hwdsl2** [comment]
@yyysuo 你好！你所说的用例（dnla和 iOS 屏幕镜像）我不熟悉。你可以通过在 env 文件中添加以下变量来自定义 IPsec/L2TP 的子网（参见 [1]）。然后必须重新创建 Docker 容器。例如：

```
# L2TP 的子网
VPN_L2TP_NET=10.10.10.0/24
# VPN 服务器的内网地址（IPsec/L2TP 模式下）
VPN_L2TP_LOCAL=10.10.10.200
# VPN 客户端的地址池（IPsec/L2TP 模式下）
VPN_L2TP_POOL=10.10.10.201-10.10.10.254
```

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/run.sh#L239-L243

**Comment by yyysuo** [comment]
非常感谢您的回复，按您的方案试了一下，连接VPN的客户端确实分配到了和主路由同网段的IP，比如10.10.10.201。

但是实际上docker中的10.10.10.X网段应该和主路由中的10.10.10.X网段应该不是一回事，假如手机目前连接公司的wifi网络，分配到的IP是192.168.1.100，连接VPN分配的IP是10.10.10.201，在机上的视频播放软件根据dlna及airplay协议搜索局域网可播放设备的时候，很可能会只搜索192.168.1.X网段，而不去搜索VPN的10.10.10.X网段，所以我的想法应该是实现不了的。
