### ISSUE TITLE
这个不能使用帐号密码登录啊，，，，使用.mobileconfig可以登录成功

### ISSUE THREAD

**Issue by bugfan** [hwdsl2/docker-ipsec-vpn-server#250]

**Comment by hwdsl2** [comment]
@bugfan 你好！IPsec/L2TP 和 IPsec/XAuth ("Cisco IPsec") 模式支持使用密码登录。请参见配置方法：  
https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#%E4%B8%8B%E4%B8%80%E6%AD%A5

**Comment by bugfan** [comment]
好的，知道了，还有个问题。

**Comment by bugfan** [comment]
如何使用自己签发的证书？？
