### ISSUE TITLE
如何使用自己从letsencrypt或者其它组织签发的可信任证书？

### ISSUE THREAD

**Issue by bugfan** [hwdsl2/docker-ipsec-vpn-server#251]
没找到啥api可以做这个事情啊，，

**Comment by hwdsl2** [comment]
@bugfan 你好！该功能目前不支持。

你可以参见这里 [1] 的说明将证书导入到 Libreswan 的 NSS 存储。但是，你仍然需要建立自己的 IKEv2 VPN CA 以生成客户端证书，并且将该 CA 导入到客户端。这是因为 LetsEncrypt 并不能签发你的 VPN 客户端的证书。总之，导入第三方证书的功能对于基于证书的 IKEv2 认证用处不大。对于基于 EAP 的 IKEv2 认证可能有用，但是 Libreswan 目前不支持。

[1] https://libreswan.org/wiki/HOWTO:_Using_NSS_with_libreswan#Importing_third-party_files_into_NSS
