### ISSUE TITLE
ikev2.sh --addclient xxx 每次密码都是一样的？？

### ISSUE THREAD

**Issue by bugfan** [hwdsl2/docker-ipsec-vpn-server#252]
想用ikev2.sh增加用户，发现生成的密码都是一样的～～～

**Comment by hwdsl2** [comment]
@bugfan 你好！是这样的。你所说的密码是用来加密客户端配置文件的，仅在导入配置文件到客户端时需要输入。在客户端连接时并不需要这个密码。
