### ISSUE TITLE
macos无法连接到vpn，故障排除的都试过了，安卓成功链接，macos不行

### ISSUE THREAD

**Issue by aogg** [hwdsl2/docker-ipsec-vpn-server#254]
**任务列表**

- [1 ] 我已阅读 [自述文件](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md)
- [ 1] 我已阅读 [重要提示](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#重要提示)
- [ 1] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#下一步)
- [ 1] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除)，[启用日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#启用-libreswan-日志) 并查看了 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [ 1] 我搜索了已有的 [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue)
- [ 0] 这个 bug 是关于 IPsec VPN 服务器 Docker 镜像，而不是 IPsec VPN 本身

**问题描述**
macos无法连接到vpn，故障排除的都试过了，安卓成功链接，macos不行。
ipsec方式

**重现步骤**
重现该 bug 的步骤：

1. ...
2. ...

**期待的正确结果**
简要地描述你期望的正确结果。

**日志**
[启用日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#启用-libreswan-日志)，检查 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)，并且添加错误日志以帮助解释该问题（如果适用）。

**服务器信息（请填写以下信息）**
- Docker 主机操作系统: [比如 Ubuntu 20.04]
- Docker version 20.10.7, build f0df35096d5f5e6b559b42c7fde6c65a2909f7c5
- 服务提供商（如果适用）: [比如 GCP, AWS]
- 爱快搭建alpine虚拟机

**客户端信息（请填写以下信息）**
- 设备: [比如 iPhone 8]
- 操作系统: [比如 iOS 13.6]
- VPN 模式: [IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") 或 IKEv2]

**其它信息**
添加关于该 bug 的其它信息。

![image](https://user-images.githubusercontent.com/8998031/131248047-bfd210b0-28ae-478c-886c-0406bd7bc5ed.png)

![image](https://user-images.githubusercontent.com/8998031/131247999-827e0b36-b57f-4c6d-b956-045c94537cfb.png)

**Comment by hwdsl2** [comment]
@aogg 你好！macOS Big Sur 在我的测试中可以正常连接。请启用服务器上的 VPN 日志，再次连接客户端，然后检查日志是否有错误 [1] 。另外，同一个 NAT（比如家用路由器）后面的多个设备不可以混合使用 IPsec/L2TP 和 IPsec/XAuth ("Cisco IPsec") 模式，否则可能导致无法连接。请仅使用其中一种模式。

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#%E5%90%AF%E7%94%A8-libreswan-%E6%97%A5%E5%BF%97
