### ISSUE TITLE
通过在 env 文件里定义变量 VPN_PUBLIC_IP 时，仅IPsec PSK的IP改变，IKEv2的IP并没有改变

### ISSUE THREAD

**Issue by Spacelessd** [hwdsl2/docker-ipsec-vpn-server#258]
**任务列表**

- [ ] 我搜索了已有的 [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue)，没有找到类似的改进建议
- [ ] 这个改进建议是关于 IPsec VPN 服务器 Docker 镜像，而不是 IPsec VPN 本身
- [ ] 我已阅读 [自述文件](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md)
- [ ] 我已阅读 [重要提示](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#重要提示)
- [ ] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#下一步)
- [ ] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除)，[启用日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#启用-libreswan-日志) 并查看了 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)

**描述改进建议**
通过在 env 文件里定义变量 VPN_PUBLIC_IP 时，仅IPsec PSK的IP改变，IKEv2的IP并没有改变，请教修改方法

**你的改进建议与遇到的问题有关吗？请描述。**
（如果适用）清楚，简洁地说明问题所在。

**其它信息**
添加关于该改进建议的其它信息。

**Comment by hwdsl2** [comment]
@Spacelessd 你好！如果在 Docker 容器中已经配置了 IKEv2，则 VPN_PUBLIC_IP, VPN_DNS_NAME 和 VPN_CLIENT_NAME 变量无效。你需要删除 Docker 容器，删除 Docker 卷，然后重新创建容器。

**请注意，这将永久删除所有的 VPN 配置信息，包括 IKEv2 证书和密钥。**

```
docker rm -f ipsec-vpn-server
docker volume rm ikev2-vpn-data
```

然后重新创建 Docker 容器。
