### ISSUE TITLE
IKEv2 clients don't connect when `VPN_PUBLIC_IP` is specified

### ISSUE THREAD

**Issue by mkyrilov** [hwdsl2/docker-ipsec-vpn-server#260]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting), [enabled logs](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#enable-libreswan-logs) and checked [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue)
- [ ] This bug is about the IPsec VPN server Docker image, and not IPsec VPN itself `<--- (probably)`

**Describe the issue**
I was looking to specify the server IP address. This doesn't seem to be anywhere in the docs. However I did find an [issue](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues/85) with a solution; specify the `VPN_PUBLIC_IP` environment variable. This gets the job done, and IPsec and L2TP work fine. However the default client for IKEv2, "`vpnclient`", does not work. It's not able to connect. Using the helper script to create another client yields the same result; unable to connect.

To resolve this issue I used the helper script:

- `5) Remove IKEv2`
- then setup again, essentially with the same details

clients created after this are able to connect.

**To Reproduce**

```sh
$ docker run \
  --name ipsec-vpn-server \
  -v ~/Downloads/ikev2-vpn-data:/etc/ipsec.d \
  -p 500:500/udp \
  -p 4500:4500/udp \
  -d --privileged \
  -e VPN_PUBLIC_IP=192.168.1.61 \
  hwdsl2/ipsec-vpn-server
```

`192.168.1.61` is my computers local IP address. You will have to specify your own when testing.

**Expected behavior**
I expect the IKEv2 server and clients to be created with the correct configuration when using the environment variables to control configuration.

**Logs**
[Enable logs](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#enable-libreswan-logs), check [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- Docker host OS: macOS 11.6 + Docker Desktop 4.0.1
- ~~Hosting provider (if applicable): [e.g. GCP, AWS]~~

**Client (please complete the following information)**
- Device: iPhone 12 Pro
- OS: iOS 15.0.2
- VPN mode: IKEv2

**Additional context**
-

**Comment by mkyrilov** [comment]
@hwdsl2 Thank you for the detailed response. I just want to clarify that the issue I described is experienced on the initial creation. That is, I start a new container with this command:

```sh 
$ docker run \
  --name ipsec-vpn-server \
  -v ~/Downloads/ikev2-vpn-data:/etc/ipsec.d \
  -p 500:500/udp \
  -p 4500:4500/udp \
  -d --privileged \
  -e VPN_PUBLIC_IP=192.168.1.61 \
  hwdsl2/ipsec-vpn-server
```
I also make sure that I delete the `~/Downloads/ikev2-vpn-data` directory before I start the container.

The resulting default IKEv2 client `vpnclient ` does not connect.

**Comment by hwdsl2** [comment]
@mkyrilov Thanks for the update. I tested on a Linux server (Debian 11 with Docker) using the command in your comment above, and wasn't able to reproduce this issue. The generated IKEv2 server certificate and client configuration all contain the correct IP `192.168.1.61`, as expected

In addition, I looked at both the IKEv2 setup script and `run.sh`, but didn't see any obvious issues when specifying `VPN_PUBLIC_IP`. Perhaps this issue is specific to Docker on macOS. If you have any additional findings, please share.

**Comment by mkyrilov** [comment]
@hwdsl2 I did some testing too. I created a Linux VM with Ubuntu Server 20.04, installed docker, and run this command:

```sh
$ sudo docker run \
  --name ipsec-vpn-server \
  -v /home/mike/ikev2-vpn-data:/etc/ipsec.d \
  -p 500:500/udp \
  -p 4500:4500/udp \
  -d --privileged \
  -e VPN_PUBLIC_IP=192.168.1.193 \
  hwdsl2/ipsec-vpn-server
```

and the IKEv2 clients work first time as expected. So like you point out, this probably is a Docker for Mac issue.

Thank you for taking the time to look into this, I appreciate it.
