### ISSUE TITLE
No traffic with MacOS and Docker

### ISSUE THREAD

**Issue by daniele2209** [hwdsl2/docker-ipsec-vpn-server#262]
Hello,

first of all, thanks a lot for your work here.

I try to connect my MBP with CISCO VPN to the latest HWDSL-Docker Image.
The MBP connects the VPN.
I can access the DOCKER-Server (Debian) directly by using the IP.
I CANNOT connect to any website through the VPN.
I can ping for instance the next 8.8.8.8 through the VPN.
It looks a little bit if DNS resolution does not works well...
A NSLOOKUP www.google.de fails.
Any ideas?

regards
Daniel

**Comment by hwdsl2** [comment]
@daniele2209 Hello! This usually indicates DNS issues within your Docker container, and may be related to your Docker network configuration. Please check the container logs [1] or errors, you may also try IKEv2 mode [1] (recommended).

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server#configure-and-use-ikev2-vpn
