### ISSUE TITLE
搭建好之后网速特别慢

### ISSUE THREAD

**Issue by YspCoder** [hwdsl2/docker-ipsec-vpn-server#266]
搭建好之后网速特别慢,不知道是不是配置的问题!
节点在华盛顿...

**Comment by hwdsl2** [comment]
@YspCoder 你好！这个是正常的。VPN 的数据加密等需要额外的带宽。参见 [1]。选择一个与客户端所在的区域较近的服务器可能有帮助。

[1] https://libreswan.org/wiki/Benchmarking_and_Performance_testing
