### ISSUE TITLE
Unable to open config file /etc/xl2tpd/xl2tpd.conf or /etc/l2tp/l2tpd.conf

### ISSUE THREAD

**Issue by pogzie** [hwdsl2/docker-ipsec-vpn-server#267]
So, I got myself a new Synology NAS and I want to keep using your Docker container image than manually configure the VPN that Synology has. I just tweaked my currently working config and ran:

```
docker run \
    --name ipsec-vpn-server \
    --env-file /var/services/homes/pogz/vpn.env \
    --restart=always \
    -v /volume1/docker/ipsec-vpn-server-data:/etc/ipsec.d \
    -p 500:500/udp \
    -p 4500:4500/udp \
    -d --privileged \
    hwdsl2/ipsec-vpn-server
```

Im ending up with the following last two error messages: 

```
2021-12-22 12:52:03 | stderr | xl2tpd[1]: init: Unable to load config file
2021-12-22 12:52:03 | stderr | xl2tpd[1]: init_config: Unable to open config file /etc/xl2tpd/xl2tpd.conf or /etc/l2tp/l2tpd.conf
```

Am I missing something here?

**Comment by hwdsl2** [comment]
@pogzie Hello! I'm not familiar with this error message. Perhaps you can try the Debian-based image to see if it works for you. For context, the default image in this repo switched from Debian-based to Alpine-based a while ago.

To try the Debian-based image, replace `hwdsl2/ipsec-vpn-server` with `hwdsl2/ipsec-vpn-server:debian` in your `docker run` command.
