### ISSUE TITLE
docker重启，用户列表丢失

### ISSUE THREAD

**Issue by ryangsun** [hwdsl2/docker-ipsec-vpn-server#269]
搭建方式

docker run \
    --name ipsec-vpn-server \
    --restart=always \
    -v /dockerdata/ipsec-vpn-server/ipsec.d:/etc/ipsec.d \
    -v /dockerdata/ipsec-vpn-server/ppp:/etc/ppp \
    -p 500:500/udp \
    -p 4500:4500/udp \
    -d --privileged \
    hwdsl2/ipsec-vpn-server

实际情况
每次该docker容器重启之后，对应的/etc/ipsec.d/下的 用户名密码文件就变成了最初的样子，后面添加的用户都丢失了。

**Comment by hwdsl2** [comment]
@ryangsun 你好！这个是正常的，目前不支持直接添加 VPN 用户。在使用该镜像时，你需要在一个 `env` 文件中定义所有的 VPN 用户名和密码，然后重新创建 Docker 容器。请参见 [1]。

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E6%9C%AC%E9%95%9C%E5%83%8F
