### ISSUE TITLE
Can't modprobe af_key in OVH gaming server

### ISSUE THREAD

**Issue by BirkhoffLee** [hwdsl2/docker-ipsec-vpn-server#27]
# Server info
* OVH model name: MC-64-OC
* CPU: i7-7700K overclock
* RAM: 64GB
* OS: Ubuntu Server 16.04 "Xenial Xerus" LTS

# Log
```
birkhoff@bhs01:~$ sudo modprobe af_key
modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/4.9.13-mod-std-ipv6-64/modules.builtin.bin'
modprobe: FATAL: Module af_key not found in directory /lib/modules/4.9.13-mod-std-ipv6-64
```

# Additional Info
I didn't check "Install original kernel" while installing the system. Will that be a problem?

**Comment by hwdsl2** [comment]
Hello! Your server is using an OVH provided Linux kernel which may lack
support for IPsec. Please first ignore that error and see if the VPN works
fine. If it does not, you must switch to a standard Linux kernel provided
by your Linux distribution. See [1] for details.

[1]
https://www.kiloroot.com/switch-to-standard-ubuntu-kernel-on-ovh-or-kimsufi-servers/

**Comment by BirkhoffLee** [comment]
Nope.

```
Write these down. You'll need them to connect!

Important notes:   https://git.io/vpnnotes2
Setup VPN clients: https://git.io/vpnclients

================================================

modprobe: ERROR: ../libkmod/libkmod.c:508 kmod_lookup_alias_from_builtin_file() could not open builtin file '/lib/modules/4.9.13-mod-std-ipv6-64/modules.builtin.bin'
modprobe: FATAL: Module af_key not found.
Redirecting to: /etc/init.d/ipsec start
Starting pluto IKE daemon for IPsec: Initializing NSS database

.
xl2tpd[1]: setsockopt recvref[30]: Protocol not available
xl2tpd[1]: This binary does not support kernel L2TP.
xl2tpd[1]: xl2tpd version xl2tpd-1.3.6 started on 909b7de55759 PID:1
xl2tpd[1]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
xl2tpd[1]: Forked by Scott Balmos and David Stipp, (C) 2001
xl2tpd[1]: Inherited by Jeff McAdams, (C) 2002
xl2tpd[1]: Forked again by Xelerance (www.xelerance.com) (C) 2006
xl2tpd[1]: Listening on IP address 0.0.0.0, port 1701
```

**Comment by hwdsl2** [comment]
Your server is running an OVH provided Linux kernel 4.9.13-mod-std-ipv6-64,
which does not support IPsec. You must switch to a distribution-provided
standard Linux kernel. Refer to the link in my previous reply for detailed
steps, or try Google.
