### ISSUE TITLE
同一IP只能有几个活跃连接吗？

### ISSUE THREAD

**Issue by ryangsun** [hwdsl2/docker-ipsec-vpn-server#270]
我们在内部服务器用docker方式安装的
现在发现，相同的外部ip同时只能有一个帐号拨入vpn。不同帐号通过同一ip登录，也只能同时有一个连上。
请问这是怎么个情况？

**Comment by ryangsun** [comment]
同一IP只能有一个活跃连接吗？
我们服务端的网络结构是：光猫---路由器（做端口映射）--- 服务器 ---docker    的方式。
client部分：我们分公司的外网出口是同一个IP。
现在测试发现，外网的同一个ip进来，只能同时有一个客户端连接上。

这个是咱们软件的原因还是我们这个网络结构不合理的原因？

**Comment by hwdsl2** [comment]
@ryangsun 你好！在重要提示里面有说明 [1]：同一个 VPN 账户可以在你的多个设备上使用。但是由于 IPsec/L2TP 的局限性，如果需要同时连接在同一个 NAT（比如家用路由器）后面的多个设备到 VPN 服务器，你必须使用 [IKEv2](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#%E9%85%8D%E7%BD%AE%E5%B9%B6%E4%BD%BF%E7%94%A8-ikev2-vpn) 或者 [IPsec/XAuth](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth-zh.md) 模式。对于 IKEv2 模式，必须为每个客户端生成唯一的证书 [2]，才能同时连接多个客户端。

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#%E9%87%8D%E8%A6%81%E6%8F%90%E7%A4%BA
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E6%B7%BB%E5%8A%A0%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%AF%81%E4%B9%A6
