### ISSUE TITLE
possible potential security threats

### ISSUE THREAD

**Issue by lvelvee** [hwdsl2/docker-ipsec-vpn-server#271]
https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/d305867bccdd70121d079cfa82c8a68c115f469f/run.sh#L638-L659

**Comment by hwdsl2** [comment]
@lvelvee Hello! There is no security threat. This code checks for the latest supported Libreswan version. It only runs once after creating the Docker container, and simply shows a message in the Docker container's output that a newer Libreswan version is available.
