### ISSUE TITLE
Does this docker image support IPv6??

### ISSUE THREAD

**Issue by boboarts** [hwdsl2/docker-ipsec-vpn-server#272]
I cannot run this image on my ipv6 vps.

It reports:
Trying to auto discover IP of this server...
dig: couldn't get address for 'resolver1.opendns.com': failure
Error: Cannot detect this server's public IP. Define it in your 'env' file as 'VPN_PUBLIC_IP'.

But, though I speicfy the var VPN_PUBLIC_IP(of coz ipv6 form), it still reports this issue.
????:<<<<

**Comment by hwdsl2** [comment]
@boboarts Hello! IPv6 is not currently supported.
