### ISSUE TITLE
公网 IP 变更，VPN_PUBLIC_IP 参数影响。

### ISSUE THREAD

**Issue by zhang-wenchao** [hwdsl2/docker-ipsec-vpn-server#276]
**任务列表**

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#下一步)
- [x] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除)，[启用日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#启用-libreswan-日志) 并查看了 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue)
- [x] 这个 bug 是关于 IPsec VPN 服务器 Docker 镜像，而不是 IPsec VPN 本身

**问题描述**
我的网络环境是家庭宽带有公网 IP，我在内网一台机器搭建了 docker-ipsec-vpn-server。通过路由器转发端口 UDP 500，4500 使用。家庭宽带的 IP 并不是固定 IP，当路由器重新拨号会获取到一个新的 IP。我发现本服务只会在初次启动时设置 VPN_PUBLIC_IP。
请问这种使用场景下固定初次启动的 VPN_PUBLIC_IP 是否会造成不良影响。

**重现步骤**
必现，当启动后公网 IP 发生变更。

**期待的正确结果**
VPN_PUBLIC_IP 可以使用域名，或者检测到公网 IP 变化后重新设置。

**Comment by hwdsl2** [comment]
@zhang-wenchao 你好！对于 IPsec/L2TP 和 IPsec/XAuth ("Cisco IPsec") 模式，服务器的公有 IP 变更并不会影响 VPN。也就是说，VPN_PUBLIC_IP 变量值无影响。
但是，对于 IKEv2 模式，公有 IP 会写入生成的服务器证书。如果服务器的公有 IP 变更，客户端会无法连接。要解决此问题，你必须在创建 Docker 容器时就指定一个域名，使用 VPN_DNS_NAME 变量指定。具体参见本项目的自述文档。
