### ISSUE TITLE
Please help - vpn.env issue when creating container 

### ISSUE THREAD

**Issue by randomranran** [hwdsl2/docker-ipsec-vpn-server#281]
I have created the vpn.env file here

![Screenshot 2022-02-27 at 21 40 06](https://user-images.githubusercontent.com/93680365/155901369-a81bd1f7-048e-4d96-92b9-cb66416a93b0.png)

This is what I've set in the vpn.env (removed my actual details)

![Screenshot 2022-02-27 at 21 40 40](https://user-images.githubusercontent.com/93680365/155901399-27f9db01-e9cf-4dfb-aeec-eedcaf37d2b5.png)

This is my docker-compose 

![Screenshot 2022-02-27 at 21 41 27](https://user-images.githubusercontent.com/93680365/155901412-c53824d8-bc4d-419f-b4d7-dd28dafb029e.png)

but I'm getting this error 

![Screenshot 2022-02-27 at 21 41 03](https://user-images.githubusercontent.com/93680365/155901416-27a15550-c141-4272-9831-62e645407adb.png)

**Comment by hwdsl2** [comment]
@randomranran Hello! This is not an issue with this project, but instead an issue with the particular platform you are using, which appears to be Portainer. Please refer to the following links. It looks like you can enter those variables directly in the Portainer UI.
https://github.com/portainer/portainer/pull/4175
https://github.com/portainer/portainer/issues/6213
https://github.com/portainer/portainer/issues/6310
https://github.com/portainer/portainer/issues/1857

By the way, `VPN_IPSEC_PSK` is required when you define `VPN_USER` and `VPN_PASSWORD`.
