### ISSUE TITLE
不支持ipv6

### ISSUE THREAD

**Issue by youngfisher** [hwdsl2/docker-ipsec-vpn-server#283]
**任务列表**

- [ ] 我搜索了已有的 [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue)，没有找到类似的改进建议
- [ ] 这个改进建议是关于 IPsec VPN 服务器 Docker 镜像，而不是 IPsec VPN 本身
- [ ] 我已阅读 [自述文件](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md)
- [ ] 我已阅读 [重要提示](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#重要提示)
- [ ] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#下一步)
- [ ] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除)，[启用日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#启用-libreswan-日志) 并查看了 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)

**描述改进建议**
尝试部署后发现不支持ipv6，也不支持ipv6 的域名。服务器只有公网ipv6地址

**你的改进建议与遇到的问题有关吗？请描述。**
烦请支持

**Comment by hwdsl2** [comment]
@youngfisher 你好！感谢你的建议。这个项目目前不支持 IPv6。在 Libreswan 上支持 IPv6 目前有一些技术困难，短期内无法解决。建议你换用比如 OpenVPN [1]，对 IPv6 有支持。

[1] https://github.com/Nyr/openvpn-install

**Comment by youngfisher** [comment]
你好

感谢这么快的回复。我其实想要的是，可以通过ipv6连接到vpn服务器，不是要求vpn服务分配的虚拟地址带ipv6
