### ISSUE TITLE
关于公网IP分配问题

### ISSUE THREAD

**Issue by JJZhangxiaobo** [hwdsl2/docker-ipsec-vpn-server#285]
作者您好，感谢您分享的docker镜像，我现在有个场景，我的一台服务器上面有5个公网ip，我想通过你的程序实现，不同的用户拨完vpn之后就是我服务器上的其他公网ip，比如user1 拨上来分配的公网ip是100.100.100.100，user2拨上来的公网ip是100.100.100.101,以此类推，不知道可否实现？我使用了iptables（ iptables -t nat -I POSTROUTING -s 172.17.0.2 ! -o docker0 -j SNAT --to 192.0.2.2。）发现好像不能实现我的需求，求助。。。

**Comment by hwdsl2** [comment]
@JJZhangxiaobo 你好！你描述的功能目前该 Docker 镜像并不支持。
