### ISSUE TITLE
Getting 'CrashLoopBackOff' from Kubernetes pod

### ISSUE THREAD

**Issue by sichokie** [hwdsl2/docker-ipsec-vpn-server#286]
So sorry for not marking down the checklist. But here's what I've got:

- When applying the .yaml file, there is no problem
- But when I'm trying to running kubectl logs to the pod, here's what I've got:
<img width="516" alt="Screen Shot 2022-03-28 at 03 50 24" src="https://user-images.githubusercontent.com/20127624/160298480-163952a5-f713-4b9b-bd11-c12e10623ee0.png">

Also if needed, this is my .yaml file : https://pastebin.com/wuGiXnb6

Did anyone face this problem? Thank you!

**Comment by hwdsl2** [comment]
@sichokie Hello! This Docker image contains a script `run.sh` that first checks that it is running inside a container (e.g. Docker, Podman) [1].

Your logs indicate that this check failed when you run it in Kubernetes. This could mean that this Docker image is not yet compatible with Kubernetes. For now, you can try commenting out the relevant lines [1] and build your own Docker image from source [2].

If you have suggestions on how to make that check work under Kubernetes, let us know.

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/a73c1f14678427f53fbc8e723efbd9af0bb8025e/run.sh#L43-L45
[2] https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#build-from-source-code

**Comment by hwdsl2** [comment]
@sichokie Fixed in df3284f. You can try the latest Docker image.

**Comment by sichokie** [comment]
Hi @hwdsl2 Sorry for bothering again. The image is working as you and I mentioned before. When I try to get the pod log, the IP, user, password and IPsec PSK is shown as well.

But when I try to connect from my local machine, it didn't connect, the IP Address shown in from a node within my cluster, I can ping the IP address, but it doesn't connect.

I'm following a guide from https://shinychang.net/blog/deploy-ipsec-vpn-server-on-kubernetes/  and I'm using the same config as he does.

Can you please help? Thank you!

**Comment by hwdsl2** [comment]
@sichokie Looking at your configuration again, IKEv2 mode may not be enabled in your `vpn-ipsec.yaml`. In this case, it could be due to network or firewall issues between your local machine and your Kubernetes cluster, which prevents VPN connection requests from reaching UDP ports 500 and 4500 on the VPN server node.
