### ISSUE TITLE
如何保持它一直连接着？

### ISSUE THREAD

**Issue by allmors** [hwdsl2/docker-ipsec-vpn-server#288]
作者您好，我刚接触这个ipsec,我使用的是dockker 方式安装，我在使用它的时候屏幕息屏或者不用它就自动断掉，能不能让它一直连接直到人为干预？服务器在国内，不受gfw影响。

**Comment by hwdsl2** [comment]
@allmors 你好！请参见 [iOS/Android 睡眠模式](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#iosandroid-%E7%9D%A1%E7%9C%A0%E6%A8%A1%E5%BC%8F)。如果需要 VPN 在设备唤醒后自动重连，你可以使用 [IKEv2](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md) 模式连接并启用 "VPN On Demand" 功能。
