### ISSUE TITLE
不兼容安卓10以后 系统自带IKEV2的vpn 连接客户端？

### ISSUE THREAD

**Issue by SuperCatss** [hwdsl2/docker-ipsec-vpn-server#293]
**任务列表**

- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue)，没有找到类似的改进建议
- [ ] 这个改进建议是关于 IPsec VPN 服务器 Docker 镜像，而不是 IPsec VPN 本身
- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#下一步)
- [ ] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除)，[启用日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#启用-libreswan-日志) 并查看了 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)

**描述改进建议**
在安卓10以后，手机已经集成了Ikev2 ipsec vpn 连接客户端，截至我现在使用的安卓12 分别有三种鉴权认证模式  分别是 MSCHAPV2 
PSK RAS。我从20年开始使用这个项目的docker 为我创建vpn 服务器，当时手机主要使用 ipsec xauth psk 认证模式。
在升级至安卓12 以后，这种认证模式已经被系统提示为不安全。随即 想着向 ikev2 过渡。使用最新镜像的ikev2 辅助脚本，创建ikev2 ，在使用strongswan 客户端的情况下，正常工作。当时使用自带的vpn 在ikev2 rsa 模式下一直无法连接。
现在还无法定位具体问题是出现在哪里。现在正在找其他的ikev2  架设软件做对比测试。如果可以，作者会考虑定位这个问题吗？个人认为 能使用 自带的vpn 客户端，会比使用第三方软件更方便。

**Comment by SuperCatss** [comment]
> @SuperCatss 你好！最新版的 Libreswan (4.7) 包含了对 Android 客户端的一些修复 [1]，之前的版本我测试过，不能使用 Android 自带客户端的 IKEv2 模式连接。我有空测试一下最新版 4.7。
> 
> [1] https://github.com/libreswan/libreswan/blob/main/CHANGES

谢谢作者的支持与付出

**Comment by xianren78** [comment]
> @SuperCatss 你好！最新版的 Libreswan (4.7) 包含了对 Android 客户端的一些修复 [1]，之前的版本我测试过，不能使用 Android 自带客户端的 IKEv2 模式连接。我有空测试一下最新版 4.7。
> 
> [1] https://github.com/libreswan/libreswan/blob/main/CHANGES

测试4.7已经支持ikev2/ipsec rsa模式
