### ISSUE TITLE
windows10无法连接ikev2服务器

### ISSUE THREAD

**Issue by reformc** [hwdsl2/docker-ipsec-vpn-server#294]
在服务器上用docker部署了一个vpn服务，docker命令如下：
docker run --name vpn --restart=always -p 500:500/udp -p 4500:4500/udp --env-file /opt/ipsec/vpn.env -v ikev2-vpn-data:/etc/ipsec.d -v /lib/modules:/lib/modules:ro -itd --privileged hwdsl2/ipsec-vpn-server

然后复制除p12文件
docker cp vpn:/etc/ipsec.d/vpnclient.p12 ./

将p12文件复制到客户端电脑（windows10）上，然后在客户端电脑同一目录下用管理员运行ikev2_config_import.cmd
服务器IP复制了服务器端docker日志里的VPN server address: 
其他用的默认值。

然后点击vpn的连接，过了许久，提示上下文已过期，我在客户端电脑上用wireshark抓包甚至不能抓到任何发往服务器的数据包。

我的手机和客户端电脑处于同一wifi连接下，手机可以正常连接服务器ikev2.

**Comment by hwdsl2** [comment]
Closing, if the issue persists let us know in this thread.
