### ISSUE TITLE
如何才能让ikev2容器对接mitmproxy透明代理，实现网页抓包呢

### ISSUE THREAD

**Issue by zeyspull** [hwdsl2/docker-ipsec-vpn-server#297]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
A clear and concise description of your enhancement request.

**Is your enhancement request related to a problem? Please describe.**
(If applicable) A clear and concise description of what the problem is.

**Additional context**
Add any other context about the enhancement request here.

**Comment by hwdsl2** [comment]
@zeyspull 你好！这个我也不太懂，所以无法提供有用的建议。你可以到相关的社区问一下？Libreswan 的问题的话，可以到邮件列表提问：
https://lists.libreswan.org/mailman/listinfo/swan

**Comment by aogg** [comment]
+1有解决方案吗
