### ISSUE TITLE
what is /lib/modules folder?

### ISSUE THREAD

**Issue by zfy0701** [hwdsl2/docker-ipsec-vpn-server#3]
I was trying to use this container but haven't succeed yet. One thing I notice is that:
/lib/modules directory is not existed on my ubuntu 14 ec2 image, can you explain what is that?

**Comment by hwdsl2** [comment]
@zfy0701 Can you please post your AMI ID? Go to the EC2 management console, select your instance. The AMI ID can be found in the details.

**Comment by zfy0701** [comment]
@hwdsl2 the ami ID is  ami-9abea4fb

I may just have some client configure error, after fixing that I could connect to vpn correctly.

So it seems that the /lib/modules folder is unnecessary?

**Comment by hwdsl2** [comment]
@zfy0701 Glad to hear the issue has been resolved. I am not sure about this, but if you follow the steps to first run "sudo modprobe af_key" on the host, the "/lib/modules" mapping may become unnecessary.
