### ISSUE TITLE
在没有公网的私网环境下，可以正常部署，但是无法正常连接上vpn服务器，这个怎么办？

### ISSUE THREAD

**Issue by xjllhy** [hwdsl2/docker-ipsec-vpn-server#301]
切换到公网并修改相应IP，再重启主机后，就可以正常使用了，但私网内怎么办？

**Comment by hwdsl2** [comment]
@xjllhy 你好！请参见：
https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E6%8C%87%E5%AE%9A-vpn-%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E5%85%AC%E6%9C%89-ip

在 env 文件中将 VPN_PUBLIC_IP 设置为你的服务器的私有 IP 即可。需要重新创建 Docker 容器。如果已配置 IKEv2，在重新创建之前还需要删除 ikev2-vpn-data Docker 卷（请注意，这将删除所有 IKEv2 配置）。
