### ISSUE TITLE
Can ipsecvpn use TCP ports 4500 and 500？

### ISSUE THREAD

**Issue by suchaoxiao** [hwdsl2/docker-ipsec-vpn-server#304]
**Describe the enhancement request**
A clear and concise description of your enhancement request.
Can you support tcp port mapping to implement ipsecvpn, if so, please tell me where to modify. thanks

**Comment by hwdsl2** [comment]
@suchaoxiao Hello! Currently, using TCP ports 500 and 4500 is not supported in this project.
