### ISSUE TITLE
Windows和iOS连接成功后无法访问网络

### ISSUE THREAD

**Issue by chenyongjie0722** [hwdsl2/docker-ipsec-vpn-server#306]
你好，使用docker搭建的，在Windows、iOS、iPad都是连接成功但无法访问网络，请问有哪些原因可能导致此问题或者有无此种情况的案例

**Comment by hwdsl2** [comment]
@chenyongjie0722 你好！本项目很少收到此类问题报告，应该是你的特定系统的问题。这个有可能是以下几个原因：

1. Docker 容器内的 IPTables 规则不正确。你可以使用 `docker logs ipsec-vpn-server` 查看容器日志是否有错误。或在容器内检查 IPTables 规则。
2. Docker 主机上的 IPTables 规则不正确。
3. Docker 容器的 DNS 配置不正确。你可以尝试访问比如 https://1.1.1.1 看看能否连接。
4. Docker 主机的关于容器的网络配置不正确，导致容器本身无法访问网络。

如果你有更多信息可以继续在这里回复，请说明你的 Docker 主机和容器的 Linux 版本。
