### ISSUE TITLE
client on local network of the server

### ISSUE THREAD

**Issue by diotta88** [hwdsl2/docker-ipsec-vpn-server#308]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x] This enhancement request is about the IPsec VPN server Docker image, and not IPsec VPN itself
- [x] I read the [README](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting), [enabled logs](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#enable-libreswan-logs) and checked [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

Hi,
I’ve been following your documentation to create a server-vpn with docker and it works perfectly,
but I need to know if there is the possibility to give clients the local IP-address of the server network address to easily access the remote interfaces of my remote-hardware from my pcs.

So imagine that I have locally the class 192.168.50.1/24 and the server vpn is at 192.168.50.200 but every client of the vpn take not only a specific vpn-ip like 192.168.42.1/24 but also an IP address from my dhcp server in the class 192.168.50.1/24.

Greatings

**Comment by hwdsl2** [comment]
@diotta88 Hello! The feature you mentioned is not supported. However, you can customize VPN subnet(s) using instructions at:
https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#customize-vpn-subnets

For example, you can specify a custom VPN subnet `192.168.50.0/24` for IPsec/XAuth and IKEv2 VPN clients. Note that this may or may not enable the VPN clients to communicate with other devices on the `192.168.50.0/24` subnet, so it may not be helpful for your use case.
