### ISSUE TITLE
我在本地win7电脑的vm虚拟机上搭建了一个vpn，为什么手机连不上去？

### ISSUE THREAD

**Issue by zouhuigang** [hwdsl2/docker-ipsec-vpn-server#31]
已经把win7的防火墙关了，用的极路由的没有关闭防火墙的选项，请问要怎样才能成功呢？是要开什么端口么？

**Comment by hwdsl2** [comment]
@zouhuigang 你好！首先你的vm虚拟机必须使用bridge networking，不能用 NAT。然后需要在你的路由器上设置端口转发 UDP 500 和 UDP 4500 到你的虚拟机的 IP 地址。建议设置路由器的 DHCP 的 MAC 地址绑定，以保证虚拟机的 IP 不变。最后你的 ISP 必须分配一个公有 IP （不是 carrier-grade NAT)。

**Comment by zouhuigang** [comment]
谢谢！！你真是太厉害啦~~已经成功连接啦！！！
