### ISSUE TITLE
更新docker镜像，手机vpn无法连接

### ISSUE THREAD

**Issue by ynhj123** [hwdsl2/docker-ipsec-vpn-server#311]
**问题描述**
你好，我最近更新了docker镜像，发现手机的vpn无法连接。在镜像中输入ipsec status,发现如下错误
![image](https://user-images.githubusercontent.com/26181404/195008103-030fafc7-06a1-42a6-8062-bb04b1c8da36.png)
我按照文档在env中添加VPN_ENABLE_MODP1024=yes后重新创建，我的手机依然无法链接，ipsec status 如下：
![image](https://user-images.githubusercontent.com/26181404/195012412-ab97bd18-00cf-4c03-8c30-6a8307c8349e.png)

其他：
连接2周前的镜像没有问题，如果可以dockhub是否可以添加多个版本，我现在更新后也无法回滚到之前的版本

**Comment by hwdsl2** [comment]
@ynhj123 你好！启用 Libreswan 日志，然后重新尝试连接。然后检查日志是否有错误？

如果你想尝试 2 周前的镜像：
```
git clone https://github.com/hwdsl2/docker-ipsec-vpn-server
# Make sure you add the dot (.) at the end for this command
cd docker-ipsec-vpn-server
git checkout ef81fc9e425f480aa0659adc4a7dceb22e07e3fb .
# To build Alpine-based image
docker build -t hwdsl2/ipsec-vpn-server .
```

然后重新创建 Docker 容器。

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E5%90%AF%E7%94%A8-libreswan-%E6%97%A5%E5%BF%97

**Comment by ynhj123** [comment]
@hwdsl2 你好，我启动了Libreswan 日志 [1]，并重新链接，新生成如下日志：
![image](https://user-images.githubusercontent.com/26181404/195241987-d0e4b8dd-965a-486e-8ca1-4a1e878e708a.png)

**Comment by hwdsl2** [comment]
@ynhj123 从你的日志来看，很可能是连接被 GFW 屏蔽或干扰了。建议你另外尝试一下比如 Shadowsocks。

**Comment by hwdsl2** [comment]
@ynhj123 你的最新日志中的问题 no acceptable Oakley Transform 是可以通过在 env 文件中添加 VPN_ENABLE_MODP1024=yes 并重新创建 Docker 容器解决的。这是因为最近本项目禁用了安全性低的 modp1024。不推荐启用 modp1024，Android 用户推荐使用更安全的 IKEv2 模式连接。

你的之前日志中的问题可能是 GFW 屏蔽导致的。

**Comment by ynhj123** [comment]
@hwdsl2 非常感谢你的帮助，这个问题得到了解决
