### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by tianrenhyb** [hwdsl2/docker-ipsec-vpn-server#312]
Apple phones can connect, Android phones cannot connect.

**Comment by hwdsl2** [comment]
@tianrenhyb Please see:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android

Android users should instead connect using [IKEv2 mode](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md) (recommended), which is more secure. Android 12+ only supports IKEv2 mode. The native VPN client in Android uses the less secure modp1024 (DH group 2) for the IPsec/L2TP and IPsec/XAuth ("Cisco IPsec") modes.

If you still want to connect using IPsec/L2TP mode, you must add VPN_ENABLE_MODP1024=yes to [your env file](https://github.com/hwdsl2/docker-ipsec-vpn-server#how-to-use-this-image), then re-create the Docker container.

**Comment by tianrenhyb** [comment]
Thanks.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hwdsl2/docker-ipsec-vpn-server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月19日(星期三) 上午6:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hwdsl2/docker-ipsec-vpn-server] Connection problem (Issue #312)





 
@tianrenhyb Please see:
 https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android
 
Android users should instead connect using IKEv2 mode (recommended), which is more secure. Android 12+ only supports IKEv2 mode. The native VPN client in Android uses the less secure modp1024 (DH group 2) for the IPsec/L2TP and IPsec/XAuth ("Cisco IPsec") modes.
 
If you still want to connect using IPsec/L2TP mode, you must add VPN_ENABLE_MODP1024=yes to your env file, then re-create the Docker container.
