### ISSUE TITLE
使用 docker 安装ipsed server 使用 mac 客户端连接后 mac 无法上网

### ISSUE THREAD

**Issue by JokerDevops** [hwdsl2/docker-ipsec-vpn-server#316]
你好，
使用docker 部署的 ipsed server ，mac 客户端连接之后无法上网，可以ping 通vpn内网地址，比如 ping 192.168.42.1 是 ok 的，但是就是没法上网

**Comment by hwdsl2** [comment]
@JokerDevops 你好！在配置 macOS VPN 客户端时，请确保选中 "通过VPN连接发送所有通信" 复选框。参见：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#os-x

推荐使用 [IKEv2 模式](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#%E9%85%8D%E7%BD%AE%E5%B9%B6%E4%BD%BF%E7%94%A8-ikev2-vpn) 连接。

另外你可以[启用并检查日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E5%90%AF%E7%94%A8-libreswan-%E6%97%A5%E5%BF%97)是否有错误。
