### ISSUE TITLE
活跃用户日志监控

### ISSUE THREAD

**Issue by shizezhi** [hwdsl2/docker-ipsec-vpn-server#317]
使用 docker exec ipsec-vpn-server ipsec whack --trafficstatus 后，
日志中为啥xauth-psk中有用户信息（username），而l2tp-psk中没有username信息。
场景：需要知道当前哪些用户在线，最好能打印出使用用户的mac地址。望解答，多谢

**Comment by hwdsl2** [comment]
@shizezhi 你好！这个是因为 L2TP 用户登录是由 xl2tpd 以及 ppp 管理的，所以 Libreswan 的 VPN 状态不显示。如果要记录用户名，你需要启用 ppp 的 debug log。更多信息请参见 #166。

**Comment by shizezhi** [comment]
谢谢


但是我是用容器启的，这个pptpd-monitor.py是在容器中执行吗？容器中如何开启ppp的debug模式呀




石泽智
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hwdsl2/docker-ipsec-vpn-server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月3日(星期四) 下午2:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hwdsl2/docker-ipsec-vpn-server] 活跃用户日志监控 (Issue #317)





 
Closed #317 as completed.

**Comment by hwdsl2** [comment]
@shizezhi 如果使用这个项目的 Docker 镜像的话，因为是基于 Alpine，pptpd-monitor.py 可能不能用。关于开启 debug 模式，你可以[编辑容器内的](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E5%9C%A8%E5%AE%B9%E5%99%A8%E4%B8%AD%E8%BF%90%E8%A1%8C-bash-shell) `/opt/src/run.sh` 并在 `/etc/ppp/options.xl2tpd` 相关部分添加 `debug` 一行。保存文件，退出 Docker 容器并重启容器。

**Comment by hwdsl2** [comment]
@shizezhi 完成后，使用 `docker logs ipsec-vpn-server` 查看日志。
