### ISSUE TITLE
Specifying DNS name does not apply in IKEv2 mode

### ISSUE THREAD

**Issue by SGprooo** [hwdsl2/docker-ipsec-vpn-server#318]
Specifying the environment variable "VPN_DNS_NAME=vpn.example.com" does not apply in IKEv2 mode, although you could manually set a DNS server in the generated configuration profile "vpnclient.mobileconfig", it would be more consistent for "VPN_DNS_NAME" to apply in IKEv2 mode.

**Comment by hwdsl2** [comment]
@SGprooo Hello! The `VPN_DNS_NAME` variable specifies a DNS name (domain name) to be used as the IKEv2 server address, such as `vpn.example.com`. This is NOT to specify a DNS server.

You may instead use `VPN_DNS_SRV1` and/or `VPN_DNS_SRV2` to specify custom DNS servers. See [1] and [2] for more details.

Note that all of these variables have no effect for IKEv2 mode, if IKEv2 is already set up in the Docker container. In this case, you may remove IKEv2 and set it up again using custom options. Refer to [Configure and use IKEv2 VPN](https://github.com/hwdsl2/docker-ipsec-vpn-server#configure-and-use-ikev2-vpn).

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server#how-to-use-this-image
[2] https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/vpn.env.example
