### ISSUE TITLE
Option to configure IKEv2 VPN with a Pre-shared key (PSK)

### ISSUE THREAD

**Issue by SGprooo** [hwdsl2/docker-ipsec-vpn-server#319]
There is currently no option to configure a PSK along IKEv2 mode unless the configuration is manually edited in ipsec.secrets.
It would be feasible to add support to manually specify such config in a docker environment variable.

**Comment by hwdsl2** [comment]
@SGprooo Hello! Thank you for your suggestion. Currently, there is no plan to support IKEv2 with PSK in this project. Certificate-based authentication is used which is more secure.
