### ISSUE TITLE
是否可以更换其他端口号

### ISSUE THREAD

**Issue by dyrilyz** [hwdsl2/docker-ipsec-vpn-server#324]
你好：
通过docker-compose，我在服务器上同时运行了几个vpn服务。我最常用的是IKEv2协议，但是今天忽然断连后无法再次连接。通过```docker exec -it ipsec-vpn-server ipsec trafficstatus```查看容器状态发现客户端已经连接，但实际上客户端长时间未响应最后断开。
通过对其他vpn的调试，我发现某些端口似乎无法使用了。
所以，我想了解，是否可以通过环境变量或其他途径来修改端口号呢？

**Comment by hwdsl2** [comment]
@RilyZhang 你好！IPsec VPN 一般需要使用默认的端口 UDP 500 和 4500。目前本项目不支持修改端口。IPsec VPN 相对来说较容易被屏蔽或干扰，你可以尝试比如 Shadowsocks 等解决方案。
