### ISSUE TITLE
服务器上的其他docker 如何直接访问 连接vpn的用户,实现组网

### ISSUE THREAD

**Issue by k631583871** [hwdsl2/docker-ipsec-vpn-server#326]
我想把服务器和连接vpn的用户进行组网, 用来实现调试微服务应用

**Comment by hwdsl2** [comment]
@k631583871 你好！不支持你所说的功能，因为 Docker 的默认安全性，容器之间的网络无法互通，也无法访问连接 VPN 的用户。

另外，如果不使用 Docker 搭建，你可以参考：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#vpn-%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%BD%91%E6%AE%B5%E8%AE%BF%E9%97%AE-vpn-%E5%AE%A2%E6%88%B7%E7%AB%AF
