### ISSUE TITLE
 IKEv2、L2TP都无法链接

### ISSUE THREAD

**Issue by CBillZhang** [hwdsl2/docker-ipsec-vpn-server#327]
服务器使用docker部署
<img width="708" alt="image" src="https://user-images.githubusercontent.com/12945259/204080793-e0504982-ad9a-4489-954d-ce38e28044e0.png">
<img width="625" alt="image" src="https://user-images.githubusercontent.com/12945259/204080830-c3d31bfd-696a-4a97-b19a-8ddbcca1c4a2.png">

但无法连接
无日志输出
使用七牛云服务器，500和4500udp端口都已打开
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/12945259/204080847-e4a57e22-1ff3-4fd8-9f42-64cb28d591e7.png">

<img width="482" alt="image" src="https://user-images.githubusercontent.com/12945259/204080882-43ca1fae-12a7-407a-9486-7c7a38200807.png">

Mac用ikev2方式、iphone用l2tp方式，都无法正常连接
很奇怪的是docker log无连接日志

**Comment by hwdsl2** [comment]
@CBillZhang 你好！我对这个服务器提供商（七牛云）不熟悉。根据你的描述，可能是防火墙的问题。在你的截图的防火墙配置中，请同时打开入站和出站方向的 UDP 500 和 4500 端口。这可能与阿里云类似 ([#433](https://github.com/hwdsl2/setup-ipsec-vpn/issues/433))。

你可以启用 Libreswan 日志，重新尝试连接，然后检查日志是否有错误：
https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E5%90%AF%E7%94%A8-libreswan-%E6%97%A5%E5%BF%97

另外，你的 Docker 镜像较旧，可以更新镜像和容器：
https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#%E6%9B%B4%E6%96%B0-docker-%E9%95%9C%E5%83%8F

**Comment by CBillZhang** [comment]
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/12945259/204117475-f27730f0-5332-42f5-9553-d1aa44e44076.png">

你好，开启日志后，有链接日志
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/12945259/204117492-0d8fa509-4e9d-4d65-97aa-80dd17670607.png">

同时出方向端口也开了

**Comment by hwdsl2** [comment]
@CBillZhang 你好！不需要打开 UDP 1701 端口。你的日志中的 retransmit 字样说明连接可能被 GFW 屏蔽了。建议你尝试其他解决方案比如 Shadowsocks。

**Comment by mengqingxiang** [comment]
--network=host  可以试试这个，我进入到docker中的时候发现他ping不同任何域名，于是我尝试加了这个以后可以了
