### ISSUE TITLE
Drop certain connection

### ISSUE THREAD

**Issue by Ejz** [hwdsl2/docker-ipsec-vpn-server#33]
Hi. In my case i see that `docker exec -it ipsec-vpn-server ipsec whack --trafficstatus` outputs a list of connections from 1 user from 1 ip (behind NAT). How can i drop a certain connection using whack utlity without dropping another connection?

**Comment by hwdsl2** [comment]
@Ejz Hello! Not sure about whether this is possible. Try the Libreswan
mailing list.

**Comment by Ejz** [comment]
Ok. Anyway thx.
