### ISSUE TITLE
推荐要是可以写个docker-compose的文件就最好了

### ISSUE THREAD

**Issue by hwangkiki** [hwdsl2/docker-ipsec-vpn-server#333]
**任务列表**

- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue)，没有找到类似的改进建议
- [x] 这个改进建议是关于 IPsec VPN 服务器 Docker 镜像，而不是 IPsec VPN 本身
- [ ] 我已阅读 [自述文件](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md)
- [ ] 我已阅读 [重要提示](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#重要提示)
- [ ] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#下一步)
- [ ] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除)，[启用日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#启用-libreswan-日志) 并查看了 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)

**描述改进建议**
使用清楚简明的语言描述你的改进建议。

**你的改进建议与遇到的问题有关吗？请描述。**
（如果适用）清楚，简洁地说明问题所在。

**其它信息**
添加关于该改进建议的其它信息。

**Comment by hwangkiki** [comment]
个人感觉Docker-compose部署比纯 docker命令安装更加的一眼明了，建议可以添加到文档里

**Comment by hwdsl2** [comment]
@hwangkiki 你好！感谢你的建议。本项目已包含一个示例 Docker compose 配置文件，请参见：
https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docker-compose.yml

**Comment by hwangkiki** [comment]
> @hwangkiki 你好！感谢你的建议。本项目已包含一个示例 Docker compose 配置文件，请参见： https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docker-compose.yml

谢谢分享
