### ISSUE TITLE
腾讯云一键部署无法连接

### ISSUE THREAD

**Issue by hwangkiki** [hwdsl2/docker-ipsec-vpn-server#334]
**任务列表**

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#下一步)
- [ ] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#故障排除)，[启用日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#启用-libreswan-日志) 并查看了 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [ ] 我搜索了已有的 [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue)
- [ ] 这个 bug 是关于 IPsec VPN 服务器 Docker 镜像，而不是 IPsec VPN 本身

**问题描述**
首先我的情况是人在国外，弄了一台腾讯云的轻量服务器想做到穿墙回国。
日志上没有报错，脚本部署开放了500和4500端口还是IKEv2协议链接不上，macx,ios都链接不上，这是啥原因呢？

**重现步骤**
重现该 bug 的步骤：

1. ...
2. ...

**期待的正确结果**
简要地描述你期望的正确结果。

**日志**
[启用日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#启用-libreswan-日志)，检查 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)，并且添加错误日志以帮助解释该问题（如果适用）。

**服务器信息（请填写以下信息）**
- Docker 主机操作系统: debian11
- 服务提供商（如果适用）: 腾讯云

**客户端信息（请填写以下信息）**
- 设备: iPhone 13
- 操作系统: ios16.2
- VPN 模式:  IKEv2

**其它信息**
添加关于该 bug 的其它信息。

**Comment by hwdsl2** [comment]
@hwangkiki 你好！请启用 Libreswan 日志，然后重新尝试连接，并检查日志是否有错误：
https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E5%90%AF%E7%94%A8-libreswan-%E6%97%A5%E5%BF%97

如果尝试连接之后没有新的日志出现，说明连接请求没有到达服务器。你可能需要打开该服务器的腾讯云防火墙的 UDP 500 和 4500 端口（出入都许可）。
