### ISSUE TITLE
如何查看 IpSec 使用的加密算法、认证算法、完整性算法等参数

### ISSUE THREAD

**Issue by xieyinglin** [hwdsl2/docker-ipsec-vpn-server#337]
请问使用防火墙配置 IPsec VPN 时，加密算法、认证算法、完整性算法、DH 组，还有 IPSec 这些参数怎么才能查找到呢？

<img width="974" alt="image" src="https://user-images.githubusercontent.com/41858839/209784629-4863b46c-b02f-41ea-8289-f96bed249896.png">

**Comment by hwdsl2** [comment]
@xieyinglin 你好！对于你的截图中的选项：IKEv2 本项目必须使用证书连接，如果不使用证书请选择 v1。加密算法选择 AES128 或者 AES256。认证算法 SHA1，完整性算法 SHA1。DH 组选择 5（1536 bits, [安全性较低](https://www.juniper.net/documentation/us/en/software/junos/vpn-ipsec/topics/ref/statement/security-edit-dh-group.html)）。IPsec 参数图中选项应该可以。如果无法连接的话，可以试试 PFS NONE。

**Comment by xieyinglin** [comment]
非常感谢回复，尝试了下目前还是不行。

<img width="939" alt="image" src="https://user-images.githubusercontent.com/41858839/209916435-17a13cb3-a48b-482b-a2b0-fffe768320c5.png">
