### ISSUE TITLE
电脑使用ikev2连接会导致VPN主机卡死重启

### ISSUE THREAD

**Issue by hqwlcm** [hwdsl2/docker-ipsec-vpn-server#340]
VPN服务是用群晖的docker来部署的，使用l2tp的方式连接没有问题，而使用了ikev2的方式连接的话，就会导致群晖NAS直接卡死重启
机器是威联通的453dmini
系统使用的是黑群晖7.1-42661

**Comment by hwdsl2** [comment]
@hqwlcm 你好！我对群晖 NAS 不熟悉。你所说的情况有可能是该 NAS 系统对 IPsec 的内核支持有问题。你可以尝试启用 Libreswan 日志，然后再次连接客户端。检查日志中是否有错误：
https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E5%90%AF%E7%94%A8-libreswan-%E6%97%A5%E5%BF%97

如果找到具体的错误信息，你可以在网上搜索一下有没有推荐的解决方案。
