### ISSUE TITLE
你好，容器可以建立，也可以运行，但是替换ENV文件一直失败，能不能指教一下。谢谢

### ISSUE THREAD

**Issue by hearting1983** [hwdsl2/docker-ipsec-vpn-server#342]
你好，容器可以建立，也可以运行，但是替换ENV文件一直失败，能不能指教一下。谢谢

**Comment by hwdsl2** [comment]
@hearting1983 你好！如果你修改或替换了 env 文件，必须重新创建 Docker 容器才能生效。请参见：
https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#%E6%9B%B4%E6%96%B0-docker-%E9%95%9C%E5%83%8F

如果你的 env 文件中有 IKEv2 相关的设置，你需要在删除 Docker 容器后移除 IKEv2 卷：`docker volume rm ikev2-vpn-data`，然后重新创建容器以使新的设置生效。请注意，该命令将永久删除当前所有的 IKEv2 配置。
