### ISSUE TITLE
Assign internal IP to VPN Server in IKEv2 mode

### ISSUE THREAD

**Issue by bokiboleboc** [hwdsl2/docker-ipsec-vpn-server#344]
**Checklist**

- [*] I searched existing [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue), and did not find a similar enhancement request
- [*] This enhancement request is about the IPsec VPN server Docker image, and not IPsec VPN itself
- [*] I read the [README](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md)
- [*] I read the [Important notes](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#important-notes)
- [*] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#next-steps)
- [*] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting), [enabled logs](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#enable-libreswan-logs) and checked [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
As the documentation states [here](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#assign-static-ips-to-vpn-clients) in IKEv2 mode the VPN server doesn't get an assigned IP, I would like for it to be possible to assign one
**Is your enhancement request related to a problem? Please describe.**
The problem is I'm mounting an SMB share for a few people to use remotely, sometimes they're on the same network and this makes the other mode not applicable (can't have multiple people behind the same router connecting to the server at the same time)

**Additional context**
Can be an advanced procedure, doesn't have to be an ENV variable or something, would just like to make it work

**Comment by hwdsl2** [comment]
@bokiboleboc Hello! Thank you for your suggestion. As you said, in IKEv2 mode the VPN server does not have an internal IP within the VPN subnet `192.168.43.0/24`. Unfortunately, I don't know a good solution for this use case. Some alternatives you can try include [OpenVPN](https://github.com/hwdsl2/openvpn-install) or [WireGuard](https://github.com/hwdsl2/wireguard-install).
