### ISSUE TITLE
苹果 6s IPSec 无法上网

### ISSUE THREAD

**Issue by ax2009live** [hwdsl2/docker-ipsec-vpn-server#345]
安卓机 L2TP/IPSec PSK 连接，上网正常； IPSec Xauth PSK 连接，上网正常；

苹果 6s 
L2TP 连接失败，无法拨入 VPN，
IKEv2 因需要下载证书，未测试
IPSec 连接成功，ip 192.168.43.10，但无法上网，
只能 ping 通本机的 ip，无法 ping 通外部的 ip，排除了 DNS 问题，说明就是不能连接外网；

**Comment by ax2009live** [comment]
不过上不上都没什么用了，因为服务器的 500 4500 端口很快被 GFW 封了！再不折腾 V-P-N 这个东西了

**Comment by hwdsl2** [comment]
@ax2009live 你好！IPsec VPN 较容易被屏蔽或干扰。对于这个用例，可以另外尝试比如 Shadowsocks。

**Comment by ax2009live** [comment]
![35A21AD7-D3B6-40A6-A8E8-E95F19A6F36E](https://user-images.githubusercontent.com/41521020/218252353-31fbd2e5-907f-4475-a409-c408a06499b8.jpeg)
 连接上去上不了网，iphone ，能提示怎么处理吗？

**Comment by ax2009live** [comment]
VPN_ENABLE_MODP1024=yes
VPN_SHA2_TRUNCBUG=yes

刚才测试了，只要 vpn.env 加上上面两句，iPhone 6s 拨号上去后上不了网；

**Comment by hwdsl2** [comment]
@ax2009live 感谢你的分享。`VPN_SHA2_TRUNCBUG=yes` 一般不需要添加，仅对于安卓版本 6 和 7 有用。
