### ISSUE TITLE
 reroute docker container traffic to ipsec container

### ISSUE THREAD

**Issue by nicholasanthonys** [hwdsl2/docker-ipsec-vpn-server#352]
Do you know how to reroute docker container traffic to ipsec container?  Could you provide the docker compose example that reroutes container traffic to ipsec container?

**Comment by hwdsl2** [comment]
@nicholasanthonys Hello! Unfortunately I am not sure about this use case. Even if you reroute another Docker container's traffic to the IPsec Docker container, it would not go through the VPN.
