### ISSUE TITLE
When I import the user certificate in the .sswan configuration on Android, I need to enter a password, but I don't know what it is

### ISSUE THREAD

**Issue by xiaobfeng** [hwdsl2/docker-ipsec-vpn-server#354]
I've tried the possible passwords in the system, but it still fails。

what is my password！！！

**Comment by xiaobfeng** [comment]
![image](https://user-images.githubusercontent.com/40769896/223736256-ed37427c-3a3c-45e7-a417-5a3b55a62248.png

**Comment by xiaobfeng** [comment]
https://gitee.com/zhu_qifeng/picture/raw/master/md/20230308221627.png

**Comment by xiaobfeng** [comment]
![](https://gitee.com/zhu_qifeng/picture/raw/master/md/20230308221627.png)

**Comment by hwdsl2** [comment]
@xiaobfeng Hello! By default there is no password for client config files, unless you enabled the `VPN_PROTECT_CONFIG=yes` option when running the VPN setup script. In that case, the password should be in the output of the VPN script. Try adding a new IKEv2 client by running `sudo ikev2.sh`, and check the password in the output.

You can also [uninstall the VPN](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/uninstall.md) and set it up again.

**Comment by xiaobfeng** [comment]
Thank you very much, the .sswan I generated again can be used directly, no password required
