### ISSUE TITLE
[Question] How i can forward port from client to server?

### ISSUE THREAD

**Issue by andreypfau** [hwdsl2/docker-ipsec-vpn-server#355]
For example i has VPN server for example ip (33.33.33.33) running using this image, and i have client connected with this VPN.
I wanna forward port (for example 25565) from my client to VPN server (33.33.33.33) for connection 33.33.33.33:25565 redirecting to my client port 25565

**Comment by hwdsl2** [comment]
@andreypfau Hello! If you [set up the VPN server directly](https://github.com/hwdsl2/setup-ipsec-vpn/) without using Docker, refer to [Port forwarding to VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#port-forwarding-to-vpn-clients).

On the other hand, if you are using this Docker image, in the default configuration, the only ports exposed are UDP port 500 and 4500, so the Docker daemon won't forward other ports to the container. Therefore it can be difficult to forward ports. For this use case, you may want to set up the VPN server directly as mentioned above.
