### ISSUE TITLE
IPSec IKEv2 VPN 只允许一台客户端接入vpn服务端

### ISSUE THREAD

**Issue by lishuda** [hwdsl2/docker-ipsec-vpn-server#359]
**问题描述**
使用docker搭建的服务端，但是同时只能有一台设备连接。
A、B手机都是用的各自的证书。
A手机显示已连接，B手机连接时就会提示连接失败。

**服务器信息（请填写以下信息）**
- Docker 主机操作系统: macOS
- VPN模式：IKEv2 only
- 是否分设备生成证书：yes

**客户端信息（请填写以下信息）**
- 设备: 小米手机
- 操作系统: [Android13]
- VPN 模式: [IKEv2 RSA]

**Comment by hwdsl2** [comment]
@lishuda 你好！在某些个别情况下，多个设备同时连接到 IKEv2 可能出现此问题。这也可能与你的 Docker 主机或网络的特定配置有关。

请[启用 Libreswan 日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E5%90%AF%E7%94%A8-libreswan-%E6%97%A5%E5%BF%97)，然后重新尝试连接，最后检查日志是否有错误。

如果你有新的信息可以继续在这里回复。
