### ISSUE TITLE
如何转发端口到设备之一

### ISSUE THREAD

**Issue by huangsen365** [hwdsl2/docker-ipsec-vpn-server#36]
大神您好，
我一直在用您发布的这个容器，想请教一下，我现在有一台服务器已部署此ipsec-vpn-server容器，公网ip地址假如是a.b.c.d，现有一台Windows 7已连接到ipsec-vpn服务器，子网ip是

**Comment by huangsen365** [comment]
续上：win7的子网地址是192.168.42.100, 
我该如何，设置可以实现a.b.c.d:3389转发到192.168.42.100:3389呢？

非常感谢！

**Comment by huangsen365** [comment]
docker run -p 3389:3389 已经实现把公网ip转发到ipsec-vpn容器，
也就是
a.b.c.d:3389 => 192.168.42.1:3389

但是现在不知道如何实现
192.168.42.1:3389 => 192.168.42.100:3389


我的ipsec-vpn容器服务器linux运行在公有云中，ip是a.b.c.d
我主要是想这样来实现把家里其中一台win7客户端通过ipsec链接开放3389端口出去，

这样的话我在外面就可以实现a.b.c.d:3389链接我家里的win7桌面了

**Comment by hwdsl2** [comment]
@huangsen365 你好！据我所知，这样的通过 VPN 的端口转发很难实现。你可以另外尝试 GRE Tunnel （请搜索相关教程），或者直接在你的家用路由器上进行端口转发（如果是动态 IP，可考虑用 Dyn 或 No-IP 等服务）。

**Comment by huangsen365** [comment]
@hwdsl2  用 iptables 可做port forwarding吗？不管怎样，还是谢谢您！

**Comment by hwdsl2** [comment]
@huangsen365 如上所述，这个端口转发我觉得很难实现。还是建议你尝试上面的其它解决方案。

**Comment by huangsen365** [comment]
感谢大神，我会按照您建议去尝试那些方法的！
另外我现在也已经找到workaround，暂时通过ssh turning实现顶着，
https://superuser.com/questions/96489/an-ssh-tunnel-via-multiple-hops
既可以做socks5代理，也可以做端口转发，缺点就是网络性能会相对VPN隧道差一点
还有autossh这个命令，可以自动重连ssh session
