### ISSUE TITLE
请在 READE.md 添加 "Synology NAS doesn't work with this docker image" 之类的字眼

### ISSUE THREAD

**Issue by seemebreakthis** [hwdsl2/docker-ipsec-vpn-server#361]
我相信很多用家已浪费了不少时间尝试在 Synology NAS 内用此 docker.  何不积点福, 不要再叫人浪费宝贵的光阴?

**Comment by hwdsl2** [comment]
@seemebreakthis 你好！感谢你的建议，我将在 README 添加关于 Synology NAS 的信息。
