### ISSUE TITLE
使用env文件创建的ikev2没有mobike特性

### ISSUE THREAD

**Issue by mike1996** [hwdsl2/docker-ipsec-vpn-server#362]
**任务列表**

- [√] 我已阅读 [自述文件](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md)
- [ √] 我已阅读 [重要提示](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#重要提示)
- [ √] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#下一步)
- [ √] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除)，[启用日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#启用-libreswan-日志) 并查看了 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [ √] 我搜索了已有的 [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue)
- [ √] 这个 bug 是关于 IPsec VPN 服务器 Docker 镜像，而不是 IPsec VPN 本身

**问题描述**
使用vpn.env文件创建的ikev2在iPhone14上可以链接，但是mobike无法实现，使用docker exec -it ipsec-vpn-server ikev2.sh脚本删除ikev2并重新配置后无法链接，不使用vpn.env文件创建也无法链接。

**期待的正确结果**
iPhone上切换数据和Wi-Fi时应始终链接VPN

**服务器信息（请填写以下信息）**
- Docker 主机操作系统: openwrt
- 服务提供商（如果适用）: 中国电信

**客户端信息（请填写以下信息）**
- 设备: iPhone 14 Pro
- 操作系统: iOS16.4
- VPN 模式: IKEv2

**其它信息**
添加关于该 bug 的其它信息。

**Comment by hwdsl2** [comment]
@mike1996 你好！请查看 Docker 容器中的 ikev2.conf，是否包含 `mobike=yes` 字样：
```
docker exec -it ipsec-vpn-server cat /etc/ipsec.d/ikev2.conf
```

如果包含 `mobike=yes`，但 MOBIKE 不工作，可能是因为 MOBIKE 的局限性导致的。

另外，如果该文件包含 `mobike=no`，则说明容器启动时检测到你的 Docker 主机可能不支持 MOBIKE，并禁用了该功能。

如果你重新配置 IKEv2，需要将生成的 .mobileconfig 文件重新导入 iPhone 并移除旧配置文件。
