### ISSUE TITLE
想在服务器的乌班图系统上使用docker部署ipsecVpn，容器部署正常，然后在windows系统上连接时报错，请问有解决方法吗

### ISSUE THREAD

**Issue by happyfir** [hwdsl2/docker-ipsec-vpn-server#367]
文件配置
![image](https://user-images.githubusercontent.com/39881443/233239776-ce898d2e-2285-464b-b74a-c68105a97fad.png)

运行日志
![image](https://user-images.githubusercontent.com/39881443/233239704-c39954ea-9065-4c63-8e50-d44523f7ac1e.png)

连接结果
![image](https://user-images.githubusercontent.com/39881443/233239812-c10da878-53b1-4736-8e07-511994d0b6cf.png)

**Comment by hwdsl2** [comment]
@happyfir 你好！要解决此错误，你需要为 IKEv2 启用更强的加密算法，通过修改一次注册表来实现。请参见：

https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E5%8F%82%E6%95%B0%E9%94%99%E8%AF%AF-policy-match-error
