### ISSUE TITLE
配置IKEv2VPN客户端时 PFX密码在哪里找呀  印象中没有配置这个密码

### ISSUE THREAD

**Issue by happyfir** [hwdsl2/docker-ipsec-vpn-server#369]
![image](https://user-images.githubusercontent.com/39881443/233528263-10c6c71d-9bba-4391-8fe5-bd6bb96a2954.png)

**Comment by hwdsl2** [comment]
@happyfir 你好！默认情况下，导入 IKEv2 客户端配置时不需要密码。你可以直接按回车键继续。如果无法导入，可能是因为你的 .p12 文件已损坏，可以尝试重新从服务器传输。

有关使用密码保护客户端配置文件的信息请参见[这里](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E6%9C%AC%E9%95%9C%E5%83%8F)。
