### ISSUE TITLE
在windows上连接vpn 其他过程正常 但就是连不上 

### ISSUE THREAD

**Issue by happyfir** [hwdsl2/docker-ipsec-vpn-server#371]
![image](https://user-images.githubusercontent.com/39881443/233889203-6d34bc4f-dd8a-4694-8926-241ae57e5694.png)
就是现实完成连接后立马就断开了

**Comment by hwdsl2** [comment]
@happyfir 你好！该问题有可能是因为连接被 GFW 屏蔽或干扰了。请[启用 Libreswan 日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E5%90%AF%E7%94%A8-libreswan-%E6%97%A5%E5%BF%97)，重新尝试连接，然后检查日志是否有错误。如果你看到许多 `retransmission` 字样，可能是这个原因。你可以换用比如 Shadowsocks。
