### ISSUE TITLE
容器中service xl2tpd的状态是stopped

### ISSUE THREAD

**Issue by ShoanJ** [hwdsl2/docker-ipsec-vpn-server#372]
换了台宿主机就死活连不上，排查到一个可能原因是xl2tpd的状态是stopped
![image](https://user-images.githubusercontent.com/25113597/233947866-f6bde7e6-c89e-4089-970e-c7920ac70d29.png)

**Comment by hwdsl2** [comment]
@ShoanJ 你好！容器中 service xl2tpd 的状态是 stopped 是正常的。这是因为容器启动 xl2tpd 时是直接运行而不是使用相关服务。应该是其他原因导致连接不上。你可以[启用并查看日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E5%90%AF%E7%94%A8-libreswan-%E6%97%A5%E5%BF%97)。
