### ISSUE TITLE
Maximum retries exceeded for tunnel 5391.  Closing.

### ISSUE THREAD

**Issue by tianwanqiang** [hwdsl2/docker-ipsec-vpn-server#374]
Debain9 The docker log says :
```
Maximum retries exceeded for tunnel 5391.  Closing.
xl2tpd[1]: Connection 1 closed to my_ip, port 1701 (Timeout)
xl2tpd[1]: Unable to deliver closing message for tunnel 5391. Destroying anyway.
```
And the vpn-client can't login

**Comment by hwdsl2** [comment]
@tianwanqiang Hello! This error could mean that there are network issues between the VPN client and server. You may [enable Libreswan logs](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#enable-libreswan-logs), try the VPN connection again, then check the logs for errors. You can also try [IKEv2 mode](https://github.com/hwdsl2/docker-ipsec-vpn-server#configure-and-use-ikev2-vpn), which is recommended over IPsec/L2TP mode.
