### ISSUE TITLE
怎么使用账号密码登陆呀 

### ISSUE THREAD

**Issue by happyfir** [hwdsl2/docker-ipsec-vpn-server#376]
我没有启用ikev2模式 用的默认的IPsec/L2TP 和 IPsec/XAuth ("Cisco IPsec") 模式 启动容器之后 直接在客户端用账号密码登录了  报错了
![image](https://user-images.githubusercontent.com/39881443/236367985-c489e86f-ca3e-45f7-8ef8-5c723ba27e8d.png)
请问该怎么解决

**Comment by hwdsl2** [comment]
@happyfir 你好！请参见 [Windows 错误 809](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#windows-%E9%94%99%E8%AF%AF-809) 中的解决方案。
