### ISSUE TITLE
请问该版本支不支持动态更改用户密码 而不需要重启容器

### ISSUE THREAD

**Issue by happyfir** [hwdsl2/docker-ipsec-vpn-server#379]

**Comment by hwdsl2** [comment]
@happyfir 你好！目前本镜像不支持该功能。你可以[绑定挂载 env 文件](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E7%BB%91%E5%AE%9A%E6%8C%82%E8%BD%BD-env-%E6%96%87%E4%BB%B6)，但任何更改必须重启容器才能生效。
