### ISSUE TITLE
请问这个vpn 能做到同时需要证书 账号 密码 三者才能登录吗 怎么设置？

### ISSUE THREAD

**Issue by happyfir** [hwdsl2/docker-ipsec-vpn-server#383]
目前就是使用ikev2证书登录 或者 账号密码  能设置成三者缺一不可的模式吗

**Comment by hwdsl2** [comment]
@happyfir 你好！本项目目前支持IKEv2证书登录或者IKEv1账号密码登录。不支持同时使用证书账号密码登录。
