### ISSUE TITLE
需要重启: docker restart xxxxxxx

### ISSUE THREAD

**Issue by xuiv** [hwdsl2/docker-ipsec-vpn-server#384]
隔一天就无法再连接上了，需要重启: docker restart xxxxxxx

只要从没连接过，隔几天都能重连上，但是只要这天用过，下一天必然无法连接上。

不像是被干扰的原因。

**Comment by hwdsl2** [comment]
@xuiv 你好！你可以[启用并查看 Libreswan 日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E5%90%AF%E7%94%A8-libreswan-%E6%97%A5%E5%BF%97)，然后尝试重现此问题。如果日志中有 retransmission 字样，则很可能是连接被干扰了。对于此用例，你可以换用比如 Shadowsocks。
