### ISSUE TITLE
ikev2 模式如何设置可以可以指定子网走vpn, 而不是所有流量?

### ISSUE THREAD

**Issue by pangliang** [hwdsl2/docker-ipsec-vpn-server#388]
看了其他issuse,  leftsubnet 各种设置都尝试过; 不太行

**Comment by hwdsl2** [comment]
@pangliang 你好！请参见 [VPN 分流](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#vpn-%E5%88%86%E6%B5%81)。如果你使用本项目的 Docker 镜像，需要首先[在容器中运行 Bash shell](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E5%9C%A8%E5%AE%B9%E5%99%A8%E4%B8%AD%E8%BF%90%E8%A1%8C-bash-shell)，然后进行第一个链接中的更改。完成后重启 Docker 容器：`docker restart ipsec-vpn-server`。
