### ISSUE TITLE
Missing vpn-gen.env File?

### ISSUE THREAD

**Issue by roguewulf** [hwdsl2/docker-ipsec-vpn-server#39]
The command
`docker cp ipsec-vpn-server:/opt/src/vpn-gen.env ./`
returns
`Error response from daemon: Could not find the file /opt/src/vpn-gen.env in container ipsec-vpn-server`

Browsing a snapshot of the image, the only file in `/opt/src` is `run.sh`

**Comment by hwdsl2** [comment]
@roguewulf Hello! This behavior is normal. The `vpn-gen.env` file is only created when you did not specify your own VPN credentials via an `vpn.env` file (in other words, you did not provide the `--env-file` parameter) when creating the container using `docker run`.

There is no point in creating the `vpn-gen.env` file if you already specified your own VPN credentials via an `vpn.env` file, as it would be identical to your `vpn.env` file.
