### ISSUE TITLE
成功安装证书后按照文档在手机配置，手机提示失败、不安全，服务端报错

### ISSUE THREAD

**Issue by Kenny-Ch** [hwdsl2/docker-ipsec-vpn-server#390]
**任务列表**

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] 这个 bug 是关于 VPN 安装脚本，而不是 IPsec VPN 本身

**问题描述**
成功安装证书后按照文档在手机配置，添加vpn后点击连接，手机提示失败、不安全，服务端报错如下
`ISAKMP_v2_IKE_SA_INIT message received on 172.17.0.10:500 but no suitable connection found with IKEv2 policy`
`responding to IKE_SA_INIT (34) message (Message ID 0) with unencrypted notification NO_PROPOSAL_CHOSEN`
![image](https://github.com/hwdsl2/setup-ipsec-vpn/assets/54130213/80bb4147-c2f2-4707-8f39-befa363eb106)

**重现步骤**
重现该 bug 的步骤：

1. 在安卓手机安装证书
2. 添加vpn配置
3. 编辑完成后点击开启vpn按钮

**期待的正确结果**
成功连接服务器

**日志**
![image](https://github.com/hwdsl2/setup-ipsec-vpn/assets/54130213/80bb4147-c2f2-4707-8f39-befa363eb106)

**服务器信息（请填写以下信息）**
- 操作系统: docker
- 服务提供商（如果适用）: [比如 GCP, AWS]

**客户端信息（请填写以下信息）**
- 设备: 小米12
- 操作系统: Android13 MIUI14
- VPN 模式: IKEv2/IPsec RSA

**其它信息**
添加关于该 bug 的其它信息。

**Comment by hwdsl2** [comment]
@Kenny-Ch 你好！该错误信息说明Docker 容器内可能未成功启动 IKEv2 连接。可以使用 `docker exec -it ipsec-vpn-server ipsec status` 命令检查，在输出中应该有包含 `ikev2-cp` 的行。如果没有相关行，则 IKEv2 未成功启动，具体原因可以检查服务端的 Docker 容器中 Libreswan 启动时的相关错误日志。

你也可以尝试移除 ikev2-vpn-data 并重新创建容器。具体步骤请点击[这里](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#%E9%85%8D%E7%BD%AE%E5%B9%B6%E4%BD%BF%E7%94%A8-ikev2-vpn)，展开"移除 IKEv2 并使用自定义选项重新配置"并参见选项 2。
