### ISSUE TITLE
重启机器后无法登录

### ISSUE THREAD

**Issue by ly-druid** [hwdsl2/docker-ipsec-vpn-server#394]
当我执行systemctl restart docker ，或者reboot 后，原本登录过该l2tp的机器无法有效登上来，持续产生以下包：

 l2tp:[TLS](0/0)Ns=0,Nr=0 *MSGTYPE(SCCRQ) *PROTO_VER(1.0) *FRAMING_CAP(S) *BEARER_CAP() FIRM_VER(1) *HOST_NAME(MikroTik) VENDOR_NAME(MikroTik) *ASSND_TUN_ID(6145) *RECV_WIN_SIZE(4)

换台机器能够正常登录，且关闭原机器的自动重拨一段时间也能正常拨，但我需要的是不需要人工干预的自动重拨

**Comment by hwdsl2** [comment]
@ly-druid 你好！我对 MikroTik 系统不熟悉，无法进行测试。你可以另外尝试 IKEv2 模式（推荐），具体步骤请参见：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#routeros

如果是从同一个 NAT 后面使用多种模式连接 VPN 服务器的话（比如 IPsec/L2TP，IPsec/XAuth，IKEv2），服务器可能会暂时记住第一次连接使用的模式，从而拒绝其他设备以不同模式发起的连接。如果是这个原因，你可以尝试让多个设备使用相同模式（比如 IKEv2）连接服务器。

另外你可以试一下 Debian-based image。参见：
https://github.com/hwdsl2/docker-ipsec-vpn-server#image-comparison
