### ISSUE TITLE
IKEv2模式连接不到到 VPN

### ISSUE THREAD

**Issue by mengxueForgoogle** [hwdsl2/docker-ipsec-vpn-server#395]
昨日安装的 ipsec-vpn-server
已经关闭vps与本机防火墙，vps已经开发所有端口
今天上午还可以使用，中午突然就用不了了
查看日志发现并没有抛出异常

已采取措施：
① 切换设备切换系统尝试   （依旧无法使用）
② 尝试重新生成.p12文件      (依旧无法使用)
③ 重新拉取与安装ipsec-vpn-server （依旧无法使用）

**Comment by mengxueForgoogle** [comment]
错误信息 
无法连接到IKEv2 VPN
无法建立计算机与 VPN 服务器之间的网络连接，因为远程服务器未响应，这可能是因为末将计算机与远程服务器之间的某种网络设备(如防火墙NAT、路由器等)配置为允许 VPN 连接。请与管理员或服务提供商联系以确定哪种设备可能产生此问题。

**Comment by hwdsl2** [comment]
@mengxueForgoogle 你好！从你的日志中的 retransmit 字样来看，很可能是连接被 GFW 干扰或屏蔽了。对于此用例，建议换用其他解决方案比如 Shadowsocks。
