### ISSUE TITLE
想请教一下使用vm虚拟机下的试验方案。。

### ISSUE THREAD

**Issue by friendtasy** [hwdsl2/docker-ipsec-vpn-server#397]
**任务列表**

- [ ] 我搜索了已有的 [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue)，没有找到类似的改进建议
- [ ] 这个改进建议是关于 IPsec VPN 服务器 Docker 镜像，而不是 IPsec VPN 本身
- [ ] 我已阅读 [自述文件](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md)
- [ ] 我已阅读 [重要提示](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#重要提示)
- [ ] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#下一步)
- [ ] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除)，[启用日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#启用-libreswan-日志) 并查看了 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)

**描述改进建议**
使用清楚简明的语言描述你的改进建议。

**你的改进建议与遇到的问题有关吗？请描述。**
（如果适用）清楚，简洁地说明问题所在。

**其它信息**
添加关于该改进建议的其它信息。

不知道在哪里问。。
黑群晖6.2.3下 用docker方式部署，无论那种连接均无法连接成功。。。考虑到有路由映射及gwf的情况，
然后使用vm试验。弄两个虚拟机，一个win11,一个ubuntu，ubuntu有两个网卡，一个与实机nat方式，一个独立网与win11相连，然后无论部署脚本还是docker方式，l2tp ikev2均在win11下无法连接。。。

**Comment by hwdsl2** [comment]
@friendtasy 你好！我对 VM 虚拟机下的部署方式不熟悉。你可以[启用 Libreswan 日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E5%90%AF%E7%94%A8-libreswan-%E6%97%A5%E5%BF%97)，再次尝试连接并检查日志。如果没有新的日志，说明连接请求没有到达服务器。IPsec VPN 默认需要打开端口 UDP 500 和 UDP 4500，请确保容器的这两个端口可以收到客户端的连接请求。
