### ISSUE TITLE
不能访问vpn容器加入到其他network下的容器

### ISSUE THREAD

**Issue by Dlinw** [hwdsl2/docker-ipsec-vpn-server#399]
**任务列表**

- [*] 我已阅读 [自述文件](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md)
- [*] 我已阅读 [重要提示](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#重要提示)
- [*] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#下一步)
- [*] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除)，[启用日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#启用-libreswan-日志) 并查看了 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [*] 我搜索了已有的 [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue)
- [*] 这个 bug 是关于 IPsec VPN 服务器 Docker 镜像，而不是 IPsec VPN 本身

**问题描述**
将当前vpn容器加入到另外一个network，访问不到另外一个network中的容器。
但在vpn容器内部可以访问到该network下的其他容器。
客户端连接vpn后只能访问到默认网卡bridge下的容器。

 

**重现步骤**
重现该 bug 的步骤：

1. 根据文档提供的容器运行命令运行后创建vpn容器
2. 将vpn容器加入到loanops network中中
3. 访问loanops network中的其他容器访问不通

**期待的正确结果**
希望可以访问到vpn容器加入到的任意一个network中的其他服务。

**其它信息**
添加关于该 bug 的其它信息。

**Comment by hwdsl2** [comment]
@Dlinw 你好！请参见 “访问 VPN 服务器的网段” 中需要添加的 IPTables 转发规则：

https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#%E8%AE%BF%E9%97%AE-vpn-%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E7%BD%91%E6%AE%B5

以上链接是关于不使用 Docker 直接创建的 VPN 服务器，对于 Docker 容器的用例，首先在容器中运行 Bash shell：

https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E5%9C%A8%E5%AE%B9%E5%99%A8%E4%B8%AD%E8%BF%90%E8%A1%8C-bash-shell

然后在容器内添加以上所述的 IPTables 规则。要在重启后继续有效，你可以将相关命令添加到 /opt/src/run.sh.
