### ISSUE TITLE
Can i setup IPsec tunnel between two pods

### ISSUE THREAD

**Issue by ognjen011** [hwdsl2/docker-ipsec-vpn-server#400]
I am wondering if i setup two pods with using this Dockerfile can turn on IPsec between them? The idea is to run some throughput tests between the pods inside IPsec tunnel.  Or am i going about this the wrong way?

**Comment by hwdsl2** [comment]
@ognjen011 Hello! This is not supported in this project.

You can find some IPsec VPN benchmarks and configuration examples at:
https://libreswan.org/wiki/Benchmarking_and_Performance_testing
https://libreswan.org/wiki/Configuration_examples
