### ISSUE TITLE
Some Linux clients cannot connect

### ISSUE THREAD

**Issue by SJ-Y054** [hwdsl2/docker-ipsec-vpn-server#405]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x] This enhancement request is about the IPsec VPN server Docker image, and not IPsec VPN itself
- [x] I read the [README](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#next-steps)
- [x] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting), [enabled logs](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#enable-libreswan-logs) and checked [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
A clear and concise description of your enhancement request.

When some Linux clients connect this server with IPsec/IKEv2, they can't connect and leaves ANY logs.
I think it is because this: https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#linux
In that link, in order to connect linux clients to this server, the server side `/etc/ipsec.d/ikev2` need to changed: adding `authby=rsa-sha1` in `conn ikev2-cp` section.
But, in docker environment, though I edit the file, the change does not persist after restart of the container.
I think some `env` config is need to change that config.

**Is your enhancement request related to a problem? Please describe.**
(If applicable) A clear and concise description of what the problem is.

**Additional context**
Add any other context about the enhancement request here.

**Comment by hwdsl2** [comment]
@SJ-Y054 Hello! Changes to `/etc/ipsec.d/ikev2.conf` are normally NOT overwritten on container restart. Please [start a Bash shell inside the container](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#bash-shell-inside-container), then follow [instructions](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#linux) to add `authby=rsa-sha1` in `conn ikev2-cp` section of `/etc/ipsec.d/ikev2.conf`. After that you can either restart the container or restart the IPsec service ([reference](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#enable-libreswan-logs)).
