### ISSUE TITLE
Docker vs. Bare Metal Performance

### ISSUE THREAD

**Issue by Dystroxic** [hwdsl2/docker-ipsec-vpn-server#409]
Have any comparisons been done between VPN performance in a Docker container (this repo) vs. the [bare metal host version](https://github.com/hwdsl2/setup-ipsec-vpn)? i.e. what kind of overhead is involved when running the containerized version? Specifically, with IKEv2.

**Comment by hwdsl2** [comment]
@Dystroxic Hello! No, there hasn't been any comparisons for the VPN performance like you mentioned. On the other hand, if you are looking for some benchmarks for the IPsec VPN, refer to [this wiki](https://libreswan.org/wiki/Benchmarking_and_Performance_testing).
