### ISSUE TITLE
exec user process caused "exec format error"

### ISSUE THREAD

**Issue by pabclsn** [hwdsl2/docker-ipsec-vpn-server#41]
Raspbian Stretch

`docker -v`

<img width="289" alt="capture d ecran 2017-11-28 a 10 33 43" src="https://user-images.githubusercontent.com/25625769/33312259-a0b80c10-d427-11e7-847d-c3162e4fe8f2.png">

<img width="254" alt="capture d ecran 2017-11-28 a 10 32 55" src="https://user-images.githubusercontent.com/25625769/33312227-8d7c37ac-d427-11e7-8d8f-cab62eb0a387.png">

`docker run --name ipsec-vpn-server --restart=always -p 500:500/udp -p 4500:4500/udp -v /lib/modules:/lib/modules:ro -d --privileged hwdsl2/ipsec-vpn-server`

<img width="1114" alt="capture d ecran 2017-11-28 a 10 34 10" src="https://user-images.githubusercontent.com/25625769/33312288-b380ab36-d427-11e7-82c3-385b5917eea9.png">

<img width="541" alt="capture d ecran 2017-11-28 a 10 34 34" src="https://user-images.githubusercontent.com/25625769/33312305-bf55fede-d427-11e7-9517-d050ced35849.png">

Can you please help ?

**Comment by hwdsl2** [comment]
@pabclsn Hello! This docker image does not support Raspberry Pis (ARM architecture).

**Comment by L3rchal** [comment]
@pabclsn You need to build image by your self:
```
git clone git@github.com:hwdsl2/docker-ipsec-vpn-server.git
docker build -t hwdsl2/ipsec-vpn-server 
```
I had zero issues building my own image on arm64 cpu architecture.

@hwdsl2 maybe you could consider supporting arm officially 🙏

**Comment by e3ndr** [comment]
you have to build for 32bit linux also
