### ISSUE TITLE
禁止同一个 VPN 账户在多个设备上同时登录

### ISSUE THREAD

**Issue by mjgaga** [hwdsl2/docker-ipsec-vpn-server#410]
**Checklist**

- [x] 我已经阅读Readme
- [x] 我已经阅读重要提示

**Describe the enhancement request**
我不希望 同一个 VPN 账户在多个设备上同时登录使用，如何能够实现？或者能否控制一个VPN账户同时最大在线设备数量？

**Additional context**
我使用的是 L2TP/IPSec

**Comment by hwdsl2** [comment]
@mjgaga 你好！你所说的用例目前本项目不支持。你可以另外尝试一下其他解决方案。
