### ISSUE TITLE
请增加IPV6支持

### ISSUE THREAD

**Issue by yufeiyang2008** [hwdsl2/docker-ipsec-vpn-server#411]
请增加IPV6支持

部署了ipv6的域名，一直显示正在连接

**Comment by hwdsl2** [comment]
@yufeiyang2008 你好！感谢你的建议。本项目近期内没有增加 IPv6 支持的计划。你可以另外尝试其他解决方案。

**Comment by GuoDapeng** [comment]
测试了 macOS Sonoma，使用 IKEv2 的话，如果有域名，域名解析 IPsec VPN Server 物理机的 IPv6。

`vpnclient.mobileconfig`名字的文件，下载到本地机器，
打开`系统设置`->`隐私与安全性`->`描述文件`，双击`vpnclient.mobileconfig`文件即可看见`描述文件`里面出现了`IKEv2`。
双击安装即可看见`系统设置`出现了`VPN`选项。

<img width="827" alt="截屏2023-12-29 00 31 34" src="https://github.com/hwdsl2/docker-ipsec-vpn-server/assets/7477750/121d24de-b0e1-4997-ac9f-8c176e0d526d">
<img width="827" alt="截屏2023-12-29 00 31 38" src="https://github.com/hwdsl2/docker-ipsec-vpn-server/assets/7477750/527009ff-1340-4acb-b303-56aa3fdef274">
