### ISSUE TITLE
How do I generate new password?

### ISSUE THREAD

**Issue by Mathiaszero** [hwdsl2/docker-ipsec-vpn-server#412]
Hello, it looks like my ipsec/ike password to connect to vpn might be compromised; is there a way to generate new random password, and how would that be done? 

For example, if vpn server is already installed, do I run: `wget https://get.vpnsetup.net -O vpn.sh && sudo sh vpn.sh`?

Thanks in advance

**Comment by hwdsl2** [comment]
@Mathiaszero Hello! Yes, you can run the command to reinstall the VPN and generate new random passwords for IPsec/L2TP and IPsec/XAuth ("Cisco IPsec") modes.  On the other hand, if you are using the Docker image, you can remove and recreate the Docker container, see project documentation.
