### ISSUE TITLE
VPN分流在windows11不起作用

### ISSUE THREAD

**Issue by Loukyuu1120** [hwdsl2/docker-ipsec-vpn-server#413]
步骤：
已经参照#388 操作 
1. ipsec ikev2 leftsubnet配置设置为server端的内网网段192.168.50.0/24，重启服务
2. windows11客户端连接上来后，访问server端内网没问题，访问其他网络就不行
3. route print显示是0.0.0.0/0的路由到vpn网卡，而没有192.168.50.0/24的路由

windows应该将sever发送的192.168.50.0/24路由信息记录到路由表，而不是0.0.0.0/0

**Comment by hwdsl2** [comment]
@Loukyuu1120 你好！请参见：
https://caedm.et.byu.edu/wiki/index.php/VPN_Instructions_for_Windows_11

按照第 8 步的说明操作，但是去掉这个选项前面的勾（不选择该项）：
Use default gateway on remote network
中文：在远程网络上使用默认网关
保存修改并重新连接。

请尝试一下是否解决问题。

**Comment by Loukyuu1120** [comment]
你好，没有解决，貌似还需要手动添加路由，Add-VpnConnectionRoute -ConnectionName '%conn_name%' -DestinationPrefix 192.168.50.0/24

**Comment by hwdsl2** [comment]
@Loukyuu1120 好的。手动添加路由之后应该就可以了吧？我有时间测试一下该用例。

**Comment by axdqq** [comment]
> @Loukyuu1120 好的。手动添加路由之后应该就可以了吧？我有时间测试一下该用例。

你好，我设置好了vpn分流，在win11上第一次连接时可用，但断开重新连接后vpn就不可用了，查看路由表发现原来网关是192.168.43.1变成了在链路上，只要删除原来的路由表重新添加就又可以了，问下怎么设置断开重连不用再次删除添加路由表

**Comment by hwdsl2** [comment]
@axdqq 对于你的用例，重新添加路由可能是必要的。请参见 [VPN 分流](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#vpn-%E5%88%86%E6%B5%81)。

**Comment by buqingchua** [comment]
> [@axdqq](https://github.com/axdqq) 对于你的用例，重新添加路由可能是必要的。请参见 [VPN 分流](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#vpn-%E5%88%86%E6%B5%81)。

解决了，重新连接会分配新的子网ip，导致之前添加的路由不可用，只需要添加多个子网ip到永久路由就不用每次连接都重新添加路由了，用了一段时间没发现问题
