### ISSUE TITLE
使用阿里云机器配置代理，服务端显示启动成功，mac和ios连接都显示connecting

### ISSUE THREAD

**Issue by zhangtw1** [hwdsl2/docker-ipsec-vpn-server#415]
1、客户端使用命令行nc -vuz显示可以正常连接
2、服务端正常生成了.mobileconfig文件
3、防火墙配置已经添加允许500，5000的端口访问

**Comment by hwdsl2** [comment]
@zhangtw1 你好！需要允许 UDP 500 和 4500 端口，对于阿里云，需要双向都允许。参见#433。nc 命令可以测试 TCP 端口，但是并不能测试 UDP 端口是否打开，具体请参见网上文档。如果仍然无法连接，你可以考虑换用比如 Shadowsocks。

**Comment by zhangtw1** [comment]
好的，感谢，刚刚咨询过了，出口是默认全部放行的，看上去还有别的问题，但我看docker logs也没有看到报错的信息
