### ISSUE TITLE
关于android使用strong swan连接校验失败的问题

### ISSUE THREAD

**Issue by plus1998** [hwdsl2/docker-ipsec-vpn-server#420]
# 问题
因为IKEv2不支持设置VPN_PUBLIC_IP，默认出来的ip是我的公网ip，但是这个公网ip是不开放端口的。我尝试导入之后修改服务器地址为内网ip： 192.168.2.33。客户端连接显示“核验服务器鉴权失败”

```
[CFG] constraint check failed: certificate does not confirm identity'192.168.2.33'(ID_IPV4_ADDR)
[CFG] selected peer config 'android' unacceptable: constraint checkingfailed
[CFG] no alternative config found
```

# 我的部署步骤
```
vim /home/vpn.env
VPN_IPSEC_PSK=vpn
VPN_USER=vcenter
VPN_PASSWORD=123456
VPN_ENABLE_MODP1024=yes
VPN_PUBLIC_IP=192.168.2.33

docker run \
    --name l2tp-vpn-server \
    --env-file /home/vpn.env \
    -p 500:500/udp \
    -p 4500:4500/udp \
    -v /lib/modules:/lib/modules:ro \
    -v ikev2-vpn-data:/etc/ipsec.d \
    -d --privileged \
    --restart=always \
    hwdsl2/ipsec-vpn-server
```

# 连接报错
![28B0B49AA3B6E586FB4655062D0805DF](https://github.com/hwdsl2/docker-ipsec-vpn-server/assets/44946497/4f4657e0-bc5f-418c-b0f2-5a6eb6bae197)

**Comment by hwdsl2** [comment]
@plus1998 你好！你在 VPN 客户端指定的服务器地址必须与 IKEv2 辅助脚本输出中的服务器地址完全一致，否则客户端可能无法连接。对于你的用例，你可以这样更改 IKEv2 地址：
1. [在容器中运行 Bash shell](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E5%9C%A8%E5%AE%B9%E5%99%A8%E4%B8%AD%E8%BF%90%E8%A1%8C-bash-shell)：
   ```
   docker exec -it l2tp-vpn-server env TERM=xterm bash -l
   ```
2. [更改 IKEv2 服务器地址](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E6%9B%B4%E6%94%B9-ikev2-%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%9C%B0%E5%9D%80)为 192.168.2.33：
   ```
   wget https://get.vpnsetup.net/ikev2addr -O ikev2addr.sh
   bash ikev2addr.sh
   ```
3. 退出并重启容器：
   ```
   exit
   docker restart l2tp-vpn-server
   ```

**Comment by plus1998** [comment]
> @plus1998 你好！你在 VPN 客户端指定的服务器地址必须与 Docker 容器的日志中的 IKEv2 服务器地址完全一致，否则客户端可能无法连接。对于你的用例，你可以这样更改 IKEv2 地址：
> 
> 1. [在容器中运行 Bash shell](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E5%9C%A8%E5%AE%B9%E5%99%A8%E4%B8%AD%E8%BF%90%E8%A1%8C-bash-shell)：
>    ```
>    docker exec -it l2tp-vpn-server env TERM=xterm bash -l
>    ```
> 2. [更改 IKEv2 服务器地址](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E6%9B%B4%E6%94%B9-ikev2-%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%9C%B0%E5%9D%80)为 192.168.2.33：
>    ```
>    wget https://get.vpnsetup.net/ikev2addr -O ikev2addr.sh
>    bash ikev2addr.sh
>    ```
> 3. 退出并重启容器：
>    ```
>    exit
>    docker restart l2tp-vpn-server
>    ```

Good Job
