### ISSUE TITLE
能否增加永久开启日志选项或者新镜像

### ISSUE THREAD

**Issue by Fang-Ben** [hwdsl2/docker-ipsec-vpn-server#425]
非常感谢大神制作的镜像，我已经部署在云VPS上，方便连接到家里内网。现在有个建议，能否增加一个镜像是开启日志功能，这样方便使用fail2ban来拦截恶意攻击。我知道现有镜像可以开启日志，但是每次容器更新或者重启又要手动执行命令。

**Comment by hwdsl2** [comment]
@Fang-Ben 你好！感谢你的建议。目前近期内没有增加该选项的计划。但是你可以[从源代码构建](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E4%BB%8E%E6%BA%90%E4%BB%A3%E7%A0%81%E6%9E%84%E5%BB%BA)你自己版本的 Docker 镜像并[开启日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E5%90%AF%E7%94%A8-libreswan-%E6%97%A5%E5%BF%97)。
