### ISSUE TITLE
您好，极空间的nas赋予ipsec vpn net_admin权限，会导致docker中使用桥接容器内的网络不通，只有改为host模式才可以访问

### ISSUE THREAD

**Issue by 1285246797** [hwdsl2/docker-ipsec-vpn-server#427]
极空间没有终端无法查看docker内部的信息，抱歉。希望大佬可以讲解一下原因，我了解一下为什么会这样

**服务器信息（请填写以下信息）**
- Docker 主机操作系统: 极空间

**客户端信息（请填写以下信息）**
- VPN 模式: IKEv2

**Comment by hwdsl2** [comment]
@1285246797 你好！我对这个用例不太熟悉，这可能是因为 Docker 容器之间的网络隔离导致的。你可以再自己尝试一下。
