### ISSUE TITLE
add functionality to script

### ISSUE THREAD

**Issue by Radmin24** [hwdsl2/docker-ipsec-vpn-server#430]
**Checklist**

- [ x] I searched existing [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue), and did not find a similar enhancement request
- [ x] This enhancement request is about the IPsec VPN server Docker image, and not IPsec VPN itself
- [ x] I read the [README](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md)
- [ x] I read the [Important notes](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#important-notes)
- [ x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#next-steps)
- [ x] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting), [enabled logs](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#enable-libreswan-logs) and checked [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**

There is an excellent command for adding a user with one command
``
docker exec -it {NAME_DOCKER} ikev2.sh --addclient {client_name}
``
It works fine, but creates a user with predefined settings for the certificate period.
It would be great if there was one more parameter `` --certificateexpiration`` which would set the lines of the client’s life

as well as on the team `` --listclients `` would show how long the client’s certificates have until

**Is your enhancement request related to a problem? Please describe.**
(If applicable) A clear and concise description of what the problem is.

**Additional context**
Add any other context about the enhancement request here.

**Comment by hwdsl2** [comment]
@Radmin24 Hello! Thank you for your suggestions. These features are not currently planned in this project. However, you may clone this project, make changes for your use case and [build a customized Docker image from source code](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#build-from-source-code).
