### ISSUE TITLE
是不能直接在局域网内部署吗，必需得连接公网？

### ISSUE THREAD

**Issue by 13265737301** [hwdsl2/docker-ipsec-vpn-server#433]

**Comment by hwdsl2** [comment]
@13265737301 你好！对于你的用例，如果要在局域网内部署，你可以在 `env` 文件中指定变量 `VPN_PUBLIC_IP=容器的 IP 地址`，然后重新创建 Docker 容器。这样会跳过公有 IP 检测。如果容器内已经配置了 IKEv2，你可能还需要在重新创建容器之前删除 `ikev2-vpn-data` 卷。请参见[这一小节](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#%E9%85%8D%E7%BD%AE%E5%B9%B6%E4%BD%BF%E7%94%A8-ikev2-vpn)中的 "移除 IKEv2 并使用自定义选项重新配置" 部分。
