### ISSUE TITLE
Windows10 连接失败

### ISSUE THREAD

**Issue by yeshirow** [hwdsl2/docker-ipsec-vpn-server#438]
在阿里云部署了docker 服务, 并且 执行了 ikev2.sh --auto.
android 客户端可以正常使用, 但 Windows 10 无法连接, 显示 "The context has expired and can no longer be used".
在 Windows 具体建立vpn 步骤:
1. 从 docker 服务 提取了 /etc/ipsec.d/vpnclient.pl2 文件到 Windows 下的 X 目录.
2. 将该站点提供的 ikev2_config_import.cmd 脚本下载到 X 目录, 然后 执行, 成功创建了一个 IKEv2 的 VPN 网络Adapter名为 Y.
3. 点击 Windows 任务栏中的 Y 连接, 一段时间后报 "The context has expired and can no longer be used" 错误.
4. 检查 docker 上服务的日志, Windows 点击后, 服务并没有看到任何消息.
请问这个问题怎么解决, 谢谢

**Comment by hwdsl2** [comment]
@yeshirow 你好！这是第一次收到有关你所说的这个错误的报告。可能是你的 Windows 客户端系统的问题，或者连接受到了干扰。[这里](https://answers.microsoft.com/en-us/windows/forum/all/windows10-vpn-using-ipsecikev2-wont-connect/a081df00-16fd-42eb-bedb-b265004dae70)有一个相关的帖子，但是并没有具体的解决方案。

虽然不清楚具体解决方案，你可以尝试在 Windows 客户端上运行 `certlm.msc` 并检查个人证书目录中是否有多个 IKEv2 证书。如果有多个该服务器签发的 IKEv2 证书，移除它们并重新从服务器导入客户端配置。

关于 Docker 容器的日志请参见[启用 Libreswan 日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E5%90%AF%E7%94%A8-libreswan-%E6%97%A5%E5%BF%97)。
