### ISSUE TITLE
docker 运行一段时间后,就连接不上了,需要重启

### ISSUE THREAD

**Issue by xox-dev** [hwdsl2/docker-ipsec-vpn-server#439]
一段时间不确定是多久,大概第二天就连接不上了

**Comment by hwdsl2** [comment]
@xox-dev 你好！对于你所说的情况，有可能是 VPN 连接被防火墙比如 GFW 干扰或屏蔽了。你可以另外尝试其他解决方案，比如 Shadowsocks。
