### ISSUE TITLE
我把容器500、4500端口分别映射到宿主机4501，4500端口，防火墙开了对应的两个udp端口

### ISSUE THREAD

**Issue by KabourWu** [hwdsl2/docker-ipsec-vpn-server#441]
我把容器500、4500端口分别映射到宿主机4501，4500端口，防火墙开了对应的两个udp端口，在使用IKEv2 VPN客户端连接时，怎么让连接新的4501端口?

**Comment by hwdsl2** [comment]
@KabourWu 你好！目前大部分的 IKEv2 VPN 客户端，比如 Windows，macOS，iOS 等，并不支持自定义端口。你可以另外尝试其他解决方案。
