### ISSUE TITLE
client not accessing remote network

### ISSUE THREAD

**Issue by H4rDBuG** [hwdsl2/docker-ipsec-vpn-server#442]
**Checklist**

- [ x ] I read the [README](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md)
- [ x ] I read the [Important notes](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#important-notes)
- [ x ] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#next-steps)
- [ x ] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting), [enabled logs](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#enable-libreswan-logs) and checked [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [ x ] I searched existing [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue)
- [ ] This bug is about the IPsec VPN server Docker image, and not IPsec VPN itself

**Describe the issue**
Client configured in ikev2, tunnel ok but no connection. My client 192.168.43.13 can ping the container vpn IP (172.255.0.2) but not ping others containers in 172.255.x.x. 

**To Reproduce**

1. install an configure docker and container
2. follow instructions to configure ikev2

**Expected behavior**
access ressources in docker's network (172.255.x.x) and ultimately access ressources in docker's host network (172.16/16)

**Logs**
[Enable logs](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#enable-libreswan-logs), check [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- Docker host OS: Debian 12.5

**Client (please complete the following information)**
- Device: Computer
- OS: Windows 11
- VPN mode: IKEv2

**Additional context**
probably configuration routing missing but don't know where to search and how to link 192.168.13 to my 172.16 :

                    Docker host network (172.16/16)
                                            |
             Docker server                   Others ressources
                        |
              VPN Container (172.255.0.2)              Others containers (172.255.0.x)
                        |                                                                     |
                        |                                                                     x
                        |                                                                     |
                                                Client (192.168.43)

**Comment by hwdsl2** [comment]
@H4rDBuG Hello! Please see [Access other containers on the Docker host](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#access-other-containers-on-the-docker-host). By default, this Docker image does not block outgoing traffic to other containers. I've tested a similar use case before (as described in the link), where VPN clients connected to the Docker container at `172.17.0.2` were able to access services on an Nginx server running in a different container at `172.17.0.3`.

For your use case, it is possible that the traffic may be blocked by IPTables rules on your Docker host, or IPTables rules in other containers you want to access. You'll need to look into those yourself. Note that in this use case, when VPN clients access resources on other containers while connected to the VPN, it may appear that the traffic is from the VPN container `172.255.0.2`, not from the client `192.168.43.x`.
