### ISSUE TITLE
Is it possible to support custom algorithm for generating certificates?

### ISSUE THREAD

**Issue by HX-Technology-LLC** [hwdsl2/docker-ipsec-vpn-server#448]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x] This enhancement request is about the IPsec VPN server Docker image, and not IPsec VPN itself
- [x] I read the [README](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#next-steps)
- [x] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting), [enabled logs](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#enable-libreswan-logs) and checked [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
A clear and concise description of your enhancement request.

Supports generating longer RSA bit certificates, elliptic curve certificates, and hash algorithms used for custom certificate generation

**Is your enhancement request related to a problem? Please describe.**
(If applicable) A clear and concise description of what the problem is.

Improved use of certificates

**Additional context**
Add any other context about the enhancement request here.

First, on Windows, if you use the system's built-in VPN client, the most secure dhgroup is dh14, which is only 2048 bits long. Although this is secure enough for now, we also need to prepare for the future.
Second, RSA and DH are not as efficient as elliptic curves. If you want to use dhgroup of ecp256 or ecp384 on Windows, you must use an elliptic curve certificate. If you use an RSA server certificate and require dhgroup of ecp256 on Windows, Windows will complain that it cannot find a valid certificate.

**Comment by hwdsl2** [comment]
@HX-Technology-LLC Hello! First, thank you for your suggestions, they'll be considered for future improvements in this project. 

Currently, the Docker image defaults to generating RSA certificates with 3072-bit keys. While currently there is no plan to changing the certificate generation algorithms in this project, you are welcome to customize the Docker image for your use case by building from source code:
https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#build-from-source-code
