### ISSUE TITLE
Can psk mode ikev2 connections be supported

### ISSUE THREAD

**Issue by HX-Technology-LLC** [hwdsl2/docker-ipsec-vpn-server#449]
**Checklist**

- [ ] I searched existing [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue), and did not find a similar enhancement request
- [ ] This enhancement request is about the IPsec VPN server Docker image, and not IPsec VPN itself
- [ ] I read the [README](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md)
- [ ] I read the [Important notes](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#important-notes)
- [ ] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#next-steps)
- [ ] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting), [enabled logs](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#enable-libreswan-logs) and checked [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
A clear and concise description of your enhancement request.

Support the psk mode in ikev2 connections

**Is your enhancement request related to a problem? Please describe.**
(If applicable) A clear and concise description of what the problem is.

The current ikev2 connection based on machine certificates is a bit complicated, especially when importing certificates and replacing them. If you use psk you can simply change the key .

**Additional context**
Add any other context about the enhancement request here.

If this is not directly supported, can I manually modify the libreswan config file to enable this functionality.

**Comment by hwdsl2** [comment]
@HX-Technology-LLC Hello! IKEv2 mode with PSK is not currently supported in this project. If you want to explore that functionality yourself, you can learn more about IPsec configuration at:
https://libreswan.org/man/ipsec.conf.5.html
https://libreswan.org/wiki/Configuration_examples

To make changes to the VPN configuration, you can [open a Bash shell inside the container](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#bash-shell-inside-container), then edit `/etc/ipsec.d/ikev2.conf`. When finished, exit the container and restart the Docker container.
