### ISSUE TITLE
修改远程端口问题

### ISSUE THREAD

**Issue by 465108069** [hwdsl2/docker-ipsec-vpn-server#450]
我现在使用docker 版本布置完了一个服务器，工作正常，现在我想用macOS用ikev2连接，所以下载了vpnclient.mobileconfig文件，然后我发现udp4500端口被封锁了，我可以将udp4500端口映射到了其它端口。
我想问一下，是否可以在mobileconfig文件中修改配置修改远程连接的端口。

**Comment by hwdsl2** [comment]
@465108069 你好！据我所知，macOS 和 iOS 系统对于 IPsec VPN 目前不支持自定义端口。默认的端口是 UDP 500 和 4500 两个端口。对于你的用例，建议另外尝试 IPsec VPN 以外的其他解决方案。另外，有关服务器上的可配置参数请参见[这里](https://libreswan.org/man/ipsec.conf.5.html)。
