### ISSUE TITLE
docker搭建的ipsec服务器不是公网IP

### ISSUE THREAD

**Issue by Ocean-TXT** [hwdsl2/docker-ipsec-vpn-server#452]
一键命令搭建出来的Docker服务器ip是内网ip请问如何解决?

**Comment by hwdsl2** [comment]
@Ocean-TXT 你好！对于此用例，请参见高级用法中的[指定 VPN 服务器的公有 IP](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E6%8C%87%E5%AE%9A-vpn-%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E5%85%AC%E6%9C%89-ip)部分。

**Comment by Ocean-TXT** [comment]
谢谢你的耐心回复，情况是这样的，我用的里面的的一键脚本在 软路由中搭建：
docker run
--name ipsec-vpn-server
--restart=always
-v ikev2-vpn-data:/etc/ipsec.d
-v /lib/modules:/lib/modules:ro
-p 500:500/udp
-p 4500:4500/udp
-d --privileged
hwdsl2/ipsec-vpn-server
安装好后用
docker logs ipsec-vpn-server
这个命令查看到了
Server IP: 198.18.8.6
IPsec PSK: GstNVk59o6MFkV9m6GsJ
Username: vpnuser
Password: NPRqYhWUkp8h6Dk3


IP: 198.18.8.6并非我的公网IP，请问 也是参见高级用法中的[指定 VPN 服务器的公有 IP]的方式吗

**Comment by hwdsl2** [comment]
@Ocean-TXT 你好！是的，对于你的用例，可以按照高级用法中的[指定 VPN 服务器的公有 IP](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E6%8C%87%E5%AE%9A-vpn-%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E5%85%AC%E6%9C%89-ip)试一下。在重新创建容器时，你可能需要删除 ikev2-vpn-data 卷以重新配置 IKEv2。请参见[配置并使用 IKEv2 VPN](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#%E9%85%8D%E7%BD%AE%E5%B9%B6%E4%BD%BF%E7%94%A8-ikev2-vpn)中的“移除 IKEv2 并使用自定义选项重新配置” 部分。
