### ISSUE TITLE
iOS won't connect, "The VPN server did not respond.". ipsec seems crashing

### ISSUE THREAD

**Issue by revintec** [hwdsl2/docker-ipsec-vpn-server#453]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#next-steps)
- [x] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting), [enabled logs](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#enable-libreswan-logs) and checked [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue)
- [ ] This bug is about the IPsec VPN server Docker image, and not IPsec VPN itself

**Describe the issue**
iOS won't connect, "The VPN server did not respond.". ipsec seems crashing
how do I further investigate?

**To Reproduce**
setup using the latest docker image and instructions, running on Docker Desktop for MacOS 4.31.0 (153195)
as can be seen from the screenshot, the server started successfully
<img width="622" alt="image" src="https://github.com/user-attachments/assets/b49cbbdc-527d-4024-a52f-9f9d308fc8cf">

port 500 was listened, and the packet reached the service
<img width="305" alt="image" src="https://github.com/user-attachments/assets/edba8c22-1654-4e7b-8cdc-86a50df4cec2">
<img width="652" alt="image" src="https://github.com/user-attachments/assets/e6fbe544-e494-4bcb-b98c-715beb1d43a1">

but no response, and port 500 is not listened anymore
<img width="304" alt="image" src="https://github.com/user-attachments/assets/0a2dd94b-a173-437a-b411-9667544bd6b4">

neither docker log nor `grep pluto /var/log/auth.log`, `grep pluto /var/log/secure`, `grep pluto /var/log/messages` shows any interesting data

**Expected behavior**

**Logs**
[Enable logs](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#enable-libreswan-logs), check [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- Docker host OS: MacOS Ventura 13.5

**Client (please complete the following information)**
- Device: iPhone 12
- OS: iOS 13
- VPN mode: IKEv2 using profile exported from docker

**Additional context**

**Comment by hwdsl2** [comment]
@revintec Hello! Thank you for reporting this issue with details. Currently, as mentioned in the README, this project does not support Docker for Mac, because this platform may be missing some IPsec and/or L2TP support which the container requires. Please instead use Linux as the Docker host OS, or you may try alternative solutions for your use case.
