### ISSUE TITLE
ikev2 模式如何设置指定多个子网走vpn, 多网段。

### ISSUE THREAD

**Issue by alan699** [hwdsl2/docker-ipsec-vpn-server#456]
我编辑了变量，VPN_SPLIT_IKEV2=172.29.208.0/20  容器的ikev2.conf文件里leftsubnet=172.29.208.0/20是对的，但我想添加多个网段怎么弄？我试过了加2个"不行，隔一个空格加网段也不行。

**Comment by hwdsl2** [comment]
@alan699 你好！对于你的用例，请参见以下链接：
https://github.com/hwdsl2/setup-ipsec-vpn/commit/5525c407c503b5b1a15cdd1721697e9e9bae9851
https://github.com/libreswan/libreswan/issues/832
https://libreswan.org/man/ipsec.conf.5.html

之前在 Libreswan 较早版本，leftsubnets 参数不工作，所以项目文档去掉了相关的说明（见第一个链接）。现在 Libreswan 版本更新了，有可能已修复，你可以尝试一下。具体步骤（包括 IKEv2 已配置的情况）请参见 [VPN 分流](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#vpn-%E5%88%86%E6%B5%81)。

**Comment by alan699** [comment]
> @alan699 你好！对于你的用例，请参见以下链接： [hwdsl2/setup-ipsec-vpn@5525c40](https://github.com/hwdsl2/setup-ipsec-vpn/commit/5525c407c503b5b1a15cdd1721697e9e9bae9851) [libreswan/libreswan#832](https://github.com/libreswan/libreswan/issues/832) https://libreswan.org/man/ipsec.conf.5.html
> 
> 之前在 Libreswan 较早版本，leftsubnets 参数不工作，所以项目文档去掉了相关的说明（见第一个链接）。现在 Libreswan 版本更新了，有可能已修复，你可以尝试一下。具体步骤（包括 IKEv2 已配置的情况）请参见 [VPN 分流](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#vpn-%E5%88%86%E6%B5%81)。

我试试，谢谢。

**Comment by alan699** [comment]
> > @alan699 你好！对于你的用例，请参见以下链接： [hwdsl2/setup-ipsec-vpn@5525c40](https://github.com/hwdsl2/setup-ipsec-vpn/commit/5525c407c503b5b1a15cdd1721697e9e9bae9851) [libreswan/libreswan#832](https://github.com/libreswan/libreswan/issues/832) https://libreswan.org/man/ipsec.conf.5.html
> > 之前在 Libreswan 较早版本，leftsubnets 参数不工作，所以项目文档去掉了相关的说明（见第一个链接）。现在 Libreswan 版本更新了，有可能已修复，你可以尝试一下。具体步骤（包括 IKEv2 已配置的情况）请参见 [VPN 分流](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#vpn-%E5%88%86%E6%B5%81)。
> 
> 我试试，谢谢。

补充，分流在安卓的ikev2 生效了，
