### ISSUE TITLE
修改/etc/ipsec.conf 文件，重启docker容器恢复原来配置

### ISSUE THREAD

**Issue by alan699** [hwdsl2/docker-ipsec-vpn-server#458]
大佬，你好，我在/etc/ipsec.conf 文件里修改添加leftsubnet=为多子网的 leftsubnets=后，重启 IPsec 服务： service ipsec restart，
但是重启docker容器，或者重启ubuntu系统会恢复原来配置，不能保存内容，是run.sh脚本？ 

变量：
VPN_L2TP_NET=11.11.11.0/24
VPN_L2TP_LOCAL=11.11.11.1
VPN_L2TP_POOL=11.11.11.150-11.11.11.199
 

VPN_XAUTH_NET=11.11.10.0/24
VPN_XAUTH_POOL=11.11.10.150-11.11.10.199

VPN_DNS_SRV1=223.5.5.5
VPN_DNS_SRV2=119.29.29.29

 VPN_ANDROID_MTU_FIX=yes

ikev2.conf 

conn ikev2-cp
  left=%defaultroute
  leftcert=0.0.0.0/0
  leftsendcert=always

  leftsubnets="172.29.208.0/20,172.24.208.0/20,11.11.10.0/23"
 

  leftrsasigkey=%cert
  right=%any
  rightid=%fromcert
  rightaddresspool=11.11.10.150-11.11.10.199
  rightca=%same
  rightrsasigkey=%cert
  narrowing=yes
  dpddelay=30
  retransmit-timeout=300s
  dpdaction=clear
  auto=add
  ikev2=insist
  rekey=no
  pfs=no
  ike=aes_gcm_c_256-hmac_sha2_256-ecp_256,aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1
  phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes128-sha2,aes256-sha2
  ikelifetime=24h
  salifetime=24h
  encapsulation=yes
  leftid=0.0.0.0/24
  modecfgdns="223.5.5.5 119.29.29.29"
  mobike=no

conn ikev2-shared

  left=%defaultroute
  leftcert=0.0.0.0/24
  leftsendcert=always

  leftsubnets="172.29.208.0/20,172.24.208.0/20,11.11.10.0/23"
 

  leftrsasigkey=%cert
  right=%any

  rightca=%same
  rightrsasigkey=%cert
  narrowing=yes
  dpddelay=30
  retransmit-timeout=300s
  dpdaction=clear

  ikev2=insist
  rekey=no
  pfs=no
  ike=aes_gcm_c_256-hmac_sha2_256-ecp_256,aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1
  phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes128-sha2,aes256-sha2
  ikelifetime=24h
  salifetime=24h
  encapsulation=yes
  leftid=0.0.0.0/24
  modecfgdns="223.5.5.5 119.29.29.29"
  mobike=no

conn alan
  rightid=@alan
  rightaddresspool=11.11.10.10-11.11.10.10
  auto=add
  also=ikev2-shared

**Comment by alan699** [comment]
还有一个问题是IKEv2的多网段分流和静态ip分配可以在安卓13的手机上生效。
但是不能在win10上面生效，win10使用脚本生成vpn连接后，可以ping通vpn服务器（阿里云实例）的内网网段，但是不能ping通223.5.5.5（阿里云dns）和访问互联网。
win10的L2TP连接是正常的。

**Comment by hwdsl2** [comment]
@alan699 你好！感谢你的总结。对于你的用例，如果修改容器内的 `/etc/ipsec.conf` 等 VPN 服务器配置文件，则需要对 `/opt/src/run.sh` 中的相应内容做同样的修改。这样可以确保在重启容器时 run.sh 不会将你的修改还原。另外，如果需要，你也可以在本项目基础上[从源代码构建](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E4%BB%8E%E6%BA%90%E4%BB%A3%E7%A0%81%E6%9E%84%E5%BB%BA)自定义 Docker 镜像。

你的 Docker 主机防火墙规则看起来基本正常。如果不是直接在 Docker 主机上安装 VPN 而是在容器内运行的话，不需要在 ufw-user-input chain 中打开 UDP 500 4500 1701 等端口。

对于同一个局域网的多台win10的静态 IP 分配问题，首先检查是否定义了正确的 rightid 值。参见[VPN 内网 IP 和流量](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#vpn-%E5%86%85%E7%BD%91-ip-%E5%92%8C%E6%B5%81%E9%87%8F)中的说明，"对于 Windows 7/8/10/11 和 RouterOS 客户端，你必须对 rightid= 使用不同的语法..."。

**Comment by alan699** [comment]
> @alan699 你好！感谢你的总结。对于你的用例，如果修改容器内的 `/etc/ipsec.conf` 等 VPN 服务器配置文件，则需要对 `/opt/src/run.sh` 中的相应内容做同样的修改。这样可以确保在重启容器时 run.sh 不会将你的修改还原。另外，如果需要，你也可以在本项目基础上[从源代码构建](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E4%BB%8E%E6%BA%90%E4%BB%A3%E7%A0%81%E6%9E%84%E5%BB%BA)自定义 Docker 镜像。
> 
> 你的 Docker 主机防火墙规则看起来基本正常。如果不是直接在 Docker 主机上安装 VPN 而是在容器内运行的话，不需要在 ufw-user-input chain 中打开 UDP 500 4500 1701 等端口。
> 
> 对于同一个局域网的多台win10的静态 IP 分配问题，首先检查是否定义了正确的 rightid 值。参见[VPN 内网 IP 和流量](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#vpn-%E5%86%85%E7%BD%91-ip-%E5%92%8C%E6%B5%81%E9%87%8F)中的说明，"对于 Windows 7/8/10/11 和 RouterOS 客户端，你必须对 rightid= 使用不同的语法..."。

好的，感谢大佬的回复，我试试。
