### ISSUE TITLE
XAuth

### ISSUE THREAD

**Issue by phate82** [hwdsl2/docker-ipsec-vpn-server#46]
Hi,
is it possible to force L2TP clients to use XAuth Authentication Method?
Thanks

**Comment by hwdsl2** [comment]
@phate82 Hello! Unfortunately L2TP clients cannot be forced to use the XAuth method.

For how to configure VPN clients to connect to the server using IPsec/XAuth, see [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md
