### ISSUE TITLE
Cannot disable IKEv2 in Docker Environment

### ISSUE THREAD

**Issue by hartundweich** [hwdsl2/docker-ipsec-vpn-server#460]
**Describe the issue**
I want to disable the IKEv2 feature as it is not needed in my environment.
I'm running on docker and deleteed already all files in the mounted docker volume and removed IKEv2 by running
ikev2.sh --removeikev2
Environment variable VPN_SKIP_IKEV2 is set to yes
Restarting the docker image is still showing in logs 
IKEv2 setup successful. Details for IKEv2 mode:
And certificates are generated

**To Reproduce**
Always

**Expected behavior**
IKEv2 should be disabled permanent

**Logs**

Setting up IKEv2. This may take a few moments...

IKEv2 setup successful. Details for IKEv2 mode:
VPN server address: vpn.hartundweich.at
VPN client name: vpnclient
Client configuration is available inside the
Docker container at:
/etc/ipsec.d/vpnclient.p12 (for Windows & Linux)
/etc/ipsec.d/vpnclient.sswan (for Android)
/etc/ipsec.d/vpnclient.mobileconfig (for iOS & macOS)
Next steps: Configure IKEv2 clients. See:
https://vpnsetup.net/clients2

**Server (please complete the following information)**
- Docker host OS: Gentoo Lilnux

**Client (please complete the following information)**
n/a

**Additional context**
n/a

**Comment by hwdsl2** [comment]
@hartundweich Hello! For your use case, the `VPN_SKIP_IKEV2` variable is only applicable to [hwdsl2/setup-ipsec-vpn](https://github.com/hwdsl2/setup-ipsec-vpn), but not this project. The correct way to disable IKEv2 is to NOT mount the `ikev2-vpn-data` volume when creating the Docker container. For more details, see [Start the IPsec VPN server](https://github.com/hwdsl2/docker-ipsec-vpn-server#start-the-ipsec-vpn-server). Quote:

> It is recommended to enable IKEv2 when using this image. However, if you prefer not to enable IKEv2 and use only the IPsec/L2TP and IPsec/XAuth ("Cisco IPsec") modes to connect to the VPN, remove the first -v option from the docker run command above.

Alternatively, you may also build a customized Docker image. See "Build from source code" in project README.

**Comment by hartundweich** [comment]
OK sorry my fault - i thought I checked everything twice and was sure to have everything searched for a solution. 
Thank you for your support
