### ISSUE TITLE
请教大佬

### ISSUE THREAD

**Issue by HUA616436641** [hwdsl2/docker-ipsec-vpn-server#463]
大佬，想问下用docker部署的vpn可以正常使用，不过用系统代理工具要怎么连，协议是选socks5还是http，端口是多少

**Comment by hwdsl2** [comment]
@HUA616436641 你好！本项目中的 Docker 镜像不支持使用 Surge 代理工具连接，只能使用 IPsec VPN 客户端连接。对于你的用例，你可以尝试一下 IPsec VPN 以外的其他解决方案。
