### ISSUE TITLE
The L2TP Connection attempt failed because the security layer encountered a processing error during initial negotiations with the remote computer.

### ISSUE THREAD

**Issue by raychan907** [hwdsl2/docker-ipsec-vpn-server#465]
**Server (please complete the following information)**
- OS: 
Operating System: Ubuntu 24.04.1 LTS
Kernel: Linux 6.8.0-1017-raspi
Architecture: arm64

- Hosting provider (if applicable): [e.g. GCP, AWS]
Raspberry Pi 5 

**Client (please complete the following information)**
- Device: PC
- OS: Windows 11 Pro
- VPN mode: [IPsec/L2TP and IKEv2]

**Additional context**
VPN client name 是預設
這是env file 我設置過的.
VPN_IPSEC_PSK=
VPN_DNS_NAME=
VPN_USER=
VPN_PASSWORD=
VPN_ADDL_USERS=
VPN_ADDL_PASSWORDS=

[VPN log.txt](https://github.com/user-attachments/files/18230114/VPN.log.txt)
[docker compose.txt](https://github.com/user-attachments/files/18230262/docker.compose.txt)

![Screenshot 2024-12-23 090354](https://github.com/user-attachments/assets/258e081f-32e4-4855-9857-03f5e9a9e2b9)

1. Windows regedit 已經設定好
REG ADD HKLM\SYSTEM\CurrentControlSet\Services\PolicyAgent /v AssumeUDPEncapsulationContextOnSendRule /t REG_DWORD /d 0x2 /f
REG ADD HKLM\SYSTEM\CurrentControlSet\Services\RasMan\Parameters /v ProhibitIpSec /t REG_DWORD /d 0x0 /f
2. 用過iKEv2 和L2TP 一樣是有問題 連不上.
3. 已將port 500 1701 4500 UDP forward到Pi5上. TNC hostname -P 是連得上. port 是沒問題的
4. 除了L2TP 安全問題之外, 我也遇過 這個問題.
![Screenshot 2024-12-18 085522](https://github.com/user-attachments/assets/940cd0d6-286a-4225-988f-c6a3cfe14547)
5. VPN 設定上 我試過把它改成允許PAP. 一樣是有相同問題
 ![Screenshot 2024-12-23 090503](https://github.com/user-attachments/assets/3ae0dcd8-4873-4766-bfb6-197eb96ddc03)
6. 暫時試過兩部電腦 雖然都是Windows 11, 但是一樣是連不上, 之前是試過用router 設定IPSec VPN. 但只成功1天, 之後還是連不上, 跟第4是一樣問題. 
7. Linux 上 ufw 已經允許500 1701 4500 udp, windows 上也做了. 
請問我是做少了哪一個步驟?

**Comment by hwdsl2** [comment]
@raychan907 你好！你的 VPN 服务器配置和日志以及客户端注册表改动看起来基本正常。Docker compose 中 /lib/modules 目录应该映射到主机上的/lib/modules目录，而不是/opt/ipsec。另外，UDP 1701端口不需要打开或转发。

你可以启用 Docker 容器内的 Libreswan 日志，然后重新尝试连接，最后检查日志是否有错误。请参见：
https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E5%90%AF%E7%94%A8-libreswan-%E6%97%A5%E5%BF%97

如果尝试连接后没有新的日志，说明连接请求没有到达服务器，你可以自己继续进行故障排除。另外，如果日志中有 retransmission 相关错误，则说明可能是 VPN 客户端和服务器之间的网络问题。

**Comment by hwdsl2** [comment]
@raychan907 是的，这样应该就启用 Libreswan 日志成功了。如果你把 /lib/modules 内容复制到别的目录的话，映射这个别的目录可能也可以。

**Comment by raychan907** [comment]
謝謝, 問題已解決.
