### ISSUE TITLE
怎么创建多个用户呢

### ISSUE THREAD

**Issue by yuyc** [hwdsl2/docker-ipsec-vpn-server#5]
如题，我ipsec的vpn想给多个人用，怎么创建多个用户呢，谢谢

**Comment by hwdsl2** [comment]
@yuyc To add more users, first get a shell inside the container:

```
docker exec -it ipsec-vpn-server /bin/bash
```

Then edit `/etc/ppp/chap-secrets` (for IPsec/L2TP) and `/etc/ipsec.d/passwd` (for IPsec/XAuth):

```
export TERM=xterm
apt-get update && apt-get -y install nano
nano /etc/ppp/chap-secrets
nano /etc/ipsec.d/passwd
```

Refer to [1] for the format of those files. When finished, `exit` the container. Then restart it:

```
docker restart ipsec-vpn-server
```

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users-zh.md

**Comment by hwdsl2** [comment]
@yuyc 刚才忘了说了，在重启 container 之前请运行以下命令，以避免配置文件在重启时被覆盖：

```
chattr +i /etc/ppp/chap-secrets /etc/ipsec.d/passwd
```

如需再次编辑，请先运行 `chattr -i`。

**Comment by yuyc** [comment]
好的，谢谢楼主了，没想到回复速度这么快，已经使用你另外一个项目搭建好了ipsec-vpn，后续再跑docker时用你的方法。

**Comment by hwdsl2** [comment]
:+1:

**Comment by BirkhoffLee** [comment]
Any plans for automating this process?

**Comment by hwdsl2** [comment]
@BirkhoffLee Sorry, not planned at this time.

**Comment by wolfwithsheep** [comment]
Dear, any plans for automating this process recently? And after i created new users, how can i check the users's status?
