### ISSUE TITLE
Cannot connect from macos 10.13.1

### ISSUE THREAD

**Issue by tangramor** [hwdsl2/docker-ipsec-vpn-server#53]
Jan 27 02:52:29 06b48c2bd353 pluto[2257]: loading secrets from "/etc/ipsec.secrets"
Jan 27 02:53:11 06b48c2bd353 pluto[2257]: "xauth-psk"[1] 220.211.132.209 #1: responding to Main Mode from unknown peer 220.211.132.209 on port 500
Jan 27 02:53:11 06b48c2bd353 pluto[2257]: "xauth-psk"[1] 220.211.132.209 #1: STATE_MAIN_R1: sent MR1, expecting MI2
Jan 27 02:53:14 06b48c2bd353 pluto[2257]: "xauth-psk"[1] 220.211.132.209 #2: responding to Main Mode from unknown peer 220.211.132.209 on port 500
Jan 27 02:53:14 06b48c2bd353 pluto[2257]: "xauth-psk"[1] 220.211.132.209 #2: STATE_MAIN_R1: sent MR1, expecting MI2
Jan 27 02:53:18 06b48c2bd353 pluto[2257]: "xauth-psk"[1] 220.211.132.209 #3: responding to Main Mode from unknown peer 220.211.132.209 on port 500
Jan 27 02:53:18 06b48c2bd353 pluto[2257]: "xauth-psk"[1] 220.211.132.209 #3: STATE_MAIN_R1: sent MR1, expecting MI2
Jan 27 02:53:21 06b48c2bd353 pluto[2257]: "xauth-psk"[1] 220.211.132.209 #4: responding to Main Mode from unknown peer 220.211.132.209 on port 500
Jan 27 02:53:21 06b48c2bd353 pluto[2257]: "xauth-psk"[1] 220.211.132.209 #4: STATE_MAIN_R1: sent MR1, expecting MI2

I tried to setup with the script on digitalocean VPS, got the same error log in auth.log

**Comment by richardhd** [comment]
I'm running this VPN on an AWS Linux t2.micro instance and I can connect fine from macOS 10.13.3, so it definitely should work. Some more details might help.

**Comment by hwdsl2** [comment]
Hello! I've been using the VPN from macOS successfully so this does not seem an issue with the Docker image. For @tangramor - It looks like your connection is blocked (interfered with) by firewall.
