### ISSUE TITLE
手机和电脑在同一个局域网下连接 VPN 后，先连接的无法使用网络

### ISSUE THREAD

**Issue by ekousp** [hwdsl2/docker-ipsec-vpn-server#54]
* 手机系统：iOS
* 电脑系统：MacOS

分别使用不同的 vpn 账号，使用cisco ipsec模式。

问题：两个设备同时连接 VPN 后，第一个连接的设备无法访问网络。

查看 ipsec 连接信息如下：
```
006 #23: "xauth-psk"[7] 223.89.65.191, username=user2, type=ESP, add_time=0, inBytes=124148, outBytes=212711, lease=192.168.43.10/32
006 #25: "xauth-psk"[7] 223.89.65.191, username=user, type=ESP, add_time=0, inBytes=664727, outBytes=1446150, lease=192.168.43.10/32
```

是不是由于分配了重复的 IP 地址导致的？应该如何解决？

谢谢！

**Comment by hwdsl2** [comment]
@ekousp 你好！你的推测是正确的，目前因为一个在 Libreswan 中的问题，现在还不支持同时连接在同一个 NAT（比如家用路由器）后面的多个设备。参见 [1]。

[1] https://github.com/libreswan/libreswan/issues/166
