### ISSUE TITLE
请问，为什么ikev2模式在iOS和macOS上需要通过docker生成配置文件

### ISSUE THREAD

**Issue by zhangsmallchi** [hwdsl2/docker-ipsec-vpn-server#56]
我看了一下docker生成的配置文件 似乎也只是填写了服务器的预共享密钥和服务器地址
那么我能否不使用docker直接在真机上配置适用于iOS和macOS连接的服务

**Comment by hwdsl2** [comment]
@zhangsmallchi 你好！对于 IKEv2，iOS 和 macOS 上的配置文件需要特定的格式，手动生成比较复杂。而 https://github.com/gaomd/docker-ikev2-vpn-server 提供了一个比较便捷的方式来生成它们。生成的配置文件与这个 Repo 搭建的 VPN 服务器兼容（使用预共享密钥而不是证书），但是与我的 IKEv2 说明文档 [1] 不兼容。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md
