### ISSUE TITLE
`/etc/ipsec.conf` is reverted on restart

### ISSUE THREAD

**Issue by kc1212** [hwdsl2/docker-ipsec-vpn-server#6]
Hi, I've been using `docker-ipsec-vpn-server` with a lot of success, there's only one little hiccup. I'm using Android 6.0, so I followed the step here https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android to change `/etc/ipsec.conf` (using `docker cp`).

However, every time I restart the container or my machine, the `ipsec.conf` file gets reverted back to its original state, and then I have to make the same changes again. I'm not sure whether this is an expected behaviour. What's a good way to persist my changes?

**Comment by hwdsl2** [comment]
@kc1212 Hello. Please try the following solution:

First, get a shell inside the container:

```
docker exec -it ipsec-vpn-server /bin/bash
```

Then edit `/run.sh` to prevent `ipsec.conf` from being overwritten at restart:

```
export TERM=xterm
apt-get update && apt-get install nano
nano /run.sh
```

Comment out these lines:

```
cat > /etc/ipsec.conf <<EOF
... ...
EOF
```

When finished, `exit` the container. Then restart it and check:

```
docker restart ipsec-vpn-server
docker exec -it ipsec-vpn-server cat /etc/ipsec.conf
```

**Comment by kc1212** [comment]
Thanks! That solves my issue.
