### ISSUE TITLE
How to deploy to AWS using Elastic Beanstalk

### ISSUE THREAD

**Issue by GabLeRoux** [hwdsl2/docker-ipsec-vpn-server#61]
Hello, I'm trying to deploy this to AWS using Elastic Beanstalk cli, but I can't manage to get it to start.

I've created the following Q/A with all the details inside: https://serverfault.com/questions/904084/cannotpullcontainererror-when-trying-to-deploy-aws-multicontainer-using-elasticb

But after investigating, I think my problem is more related to using `hwdsl2/ipsec-vpn-server` than Elastic Beanstalk. Anyone had success deploying this to AWS or some other cloud provider?

Edit: I used the non docker way with [hwdsl2/setup-ipsec-vpn](https://github.com/hwdsl2/setup-ipsec-vpn) instead, but I'm still seeking for an answer. 🍻

**Comment by hwdsl2** [comment]
@GabLeRoux Hello! Unfortunately this is not currently supported. I am not really familiar with the Elastic Beanstalk. Happy to hear you got it working the non docker way.
