### ISSUE TITLE
Clients reach each other

### ISSUE THREAD

**Issue by cipherspec** [hwdsl2/docker-ipsec-vpn-server#64]
Thanks for this repo Dockerfile.

I can set up the VPN on all my devices, OSes ..., all connections do work perfectly. Nice one.

But, what I don't understand: is there a possiblity to make the clients reach each other? I set up routes on every client (excepting Android), using the VPNs internal gateway (in default run.sh its 192.168.42.1), and the clients get ip adresses ...42.10, ...42.11, ...42.12, but they can't ping or tcp syn each other.

Is an libreswan / ipsec configuration missing in default config? I read about the client-to-client-directive, but if I remember right, it was in openvpns configuration, not libreswan.

Any hints? Thank you very much!

**Comment by hwdsl2** [comment]
@cipherspec Hello! The default VPN configuration in the Docker image does allow VPN clients to reach each other via their assigned internal VPN IPs (192.168.42.10, 192.168.42.11, etc.) The required IPTables rules are already present [1]. AFAIK there is no client-to-client directive in the Libreswan configuration.

With that said, many VPN clients such as Windows and iOS has built-in firewalls which could disallow pings and other traffic. So VPN client-to-client connections may not work reliably.

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/run.sh#L243-L248
