### ISSUE TITLE
Suggestion - From Google DNS to Cloudflare DNS

### ISSUE THREAD

**Issue by pascalandy** [hwdsl2/docker-ipsec-vpn-server#65]
From the news from Cloudflare - https://twitter.com/Cloudflare/status/980430875258212352

I suggest to move out from Google DNS and use Cloudflare service.

https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/00e3e719b95b73e3e7c7e8ad5e06fdace0873366/run.sh#L109

and use instead:

```
DNS_SRV1=${VPN_DNS_SRV1:-'1.1.1.1'}
DNS_SRV2=${VPN_DNS_SRV2:-'1.0.0.1'}
```

I could do a PR if you prefer :)

**Comment by maltalex** [comment]
I support the suggestion, but just know that you can achieve the same result using environment variables. Just pass these two to docker:

```
VPN_DNS_SRV1=1.1.1.1
VPN_DNS_SRV2=1.0.0.1
```
