### ISSUE TITLE
Please use secure ciphers

### ISSUE THREAD

**Issue by songgao** [hwdsl2/docker-ipsec-vpn-server#66]
In an [old article for openswan](https://wiki.strongswan.org/projects/strongswan/wiki/SecurityRecommendations), some of [these](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/00e3e719b95b73e3e7c7e8ad5e06fdace0873366/run.sh#L134) were specifically marked as broken.

Is there a specific reason why old broken ciphers are included in the `ike=` list? If there are old platforms that this intends to support, and they only support some of these ciphers, perhaps the docs could mention it.

For macOS and iOS, it seems `ike=aes256-sha2;dh14` is a sensible choice, as Apple added DH group 14 for both Cisco IPSec and L2TP/IPSec since iOS 9.3 and OS X 10.11.4 ([link](https://support.apple.com/en-us/HT206154)). I haven't tested on other platforms though.

**Comment by hwdsl2** [comment]
@songgao Thank you for suggesting more secure ciphers for the VPN configuration. The ciphers in your linked article are not really "broken", although they may be less secure than others.

Unfortunately for compatibility with Windows clients, modp1024 must be enabled. The current group of ciphers try to maintain compatibility with VPN clients on different platforms.
