### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by RickyRomero** [hwdsl2/docker-ipsec-vpn-server#71]
Just a simple question about the docs:

---

### Start the IPsec VPN server

**Important:** First, load the IPsec `NETKEY` kernel module on the Docker host:

```
sudo modprobe af_key
```

 ---

Is this step required every time the host is restarted, or just for first run of the container?

**Comment by hwdsl2** [comment]
@RickyRomero Hello! This step is not strictly needed as the Docker container will attempt to run modprobe from inside the container. Try and see if the container works without this step. Otherwise you'll need to run it on every reboot.
