### ISSUE TITLE
container always is in a restart status and is not running

### ISSUE THREAD

**Issue by Alikhll** [hwdsl2/docker-ipsec-vpn-server#72]
I completely followed the instruction but I couldn't figure out how it works
I pulled `docker pull hwdsl2/ipsec-vpn-server` inside Ubuntu server then created a file named vpn.env which is filled by this and I generated Ip sec pre shared key using this address [generator](https://www.pskgen.com/) with password 1 and key 1
```
VPN_IPSEC_PSK=C5seNqcaSl9XshZbeYf5gDtihaMLOtKZWpaFKawhdTVXe7M0WhtY2DlvGpO04vZy
VPN_USER=your_vpn_username
VPN_PASSWORD=your_vpn_password
```
after that, I did this `sudo modprobe af_key` then I ran container by this instruction
```
docker run \
    --name ipsec-vpn-server \
    --env-file ./vpn.env \
    --restart=always \
    -p 500:500/udp \
    -p 4500:4500/udp \
    -v /lib/modules:/lib/modules:ro \
    -d --privileged \
    hwdsl2/ipsec-vpn-server
```
but container is not running and just says it is restarting,  what's wrong?

**Comment by hwdsl2** [comment]
@Alikhll Hello! Cannot reproduce this issue on a Ubuntu 16.04 server. The problem is most likely with your server configuration. Check "docker logs ipsec-vpn-server".
