### ISSUE TITLE
support devices in the same LAN network

### ISSUE THREAD

**Issue by fcbflying** [hwdsl2/docker-ipsec-vpn-server#73]
I have a phone and mac pro in the same LAN network.
But they can not work at the same time.
When the phone connect to the L2TP server, the mac pro will disconnect.
And if I try to connect to the L2TP server with mac pro, the phone will disconnect.

**Comment by hwdsl2** [comment]
@fcbflying Hello! This is a known limitation where only one device behind the same NAT can connect to the VPN server at a time.
