### ISSUE TITLE
Error 789 when connection from Windows 10

### ISSUE THREAD

**Issue by anmiles** [hwdsl2/docker-ipsec-vpn-server#75]
Error 789: The L2TP connection attempt failed because the security layer encountered a processing error during initial negotiations with the remote computer.

Docker image run within ubuntu server (EC2).
Security groups allow any connections between my client and server.
Ports 500 and 4500 are open on the server (udp).
PSK is the same on the client and on the server.
Username and password are double-checked.
One-time registry change is applied on windows.
Both IKEEXT and PolicyAgent services are started on windows.

Here is log (client ip address is changed):

> Apr 26 07:23:32 e0de3bb49b45 pluto[2081]: packet from 1.2.3.4:500: ignoring unknown Vendor ID payload [01528bbbc00696121849ab9a1c5b2a5100000001]
Apr 26 07:23:32 e0de3bb49b45 pluto[2081]: "l2tp-psk"[1] 1.2.3.4 #1: responding to Main Mode from unknown peer 1.2.3.4 on port 500
Apr 26 07:23:32 e0de3bb49b45 pluto[2081]: "l2tp-psk"[1] 1.2.3.4 #1: Oakley Transform [AES_CBC (256), HMAC_SHA1, DH20] refused
Apr 26 07:23:32 e0de3bb49b45 pluto[2081]: "l2tp-psk"[1] 1.2.3.4 #1: Oakley Transform [AES_CBC (128), HMAC_SHA1, DH19] refused
Apr 26 07:23:32 e0de3bb49b45 pluto[2081]: "l2tp-psk"[1] 1.2.3.4 #1: STATE_MAIN_R1: sent MR1, expecting MI2
Apr 26 07:23:33 e0de3bb49b45 pluto[2081]: "l2tp-psk"[1] 1.2.3.4 #1: retransmitting in response to duplicate packet; already STATE_MAIN_R1
Apr 26 07:23:34 e0de3bb49b45 pluto[2081]: "l2tp-psk"[1] 1.2.3.4 #1: retransmitting in response to duplicate packet; already STATE_MAIN_R1
Apr 26 07:23:37 e0de3bb49b45 pluto[2081]: "l2tp-psk"[1] 1.2.3.4 #1: retransmitting in response to duplicate packet; already STATE_MAIN_R1
Apr 26 07:24:32 e0de3bb49b45 pluto[2081]: "l2tp-psk"[1] 1.2.3.4 #1: deleting incomplete state after 60.000 seconds
Apr 26 07:24:32 e0de3bb49b45 pluto[2081]: "l2tp-psk"[1] 1.2.3.4 #1: deleting state (STATE_MAIN_R1)
Apr 26 07:24:32 e0de3bb49b45 pluto[2081]: deleting connection "l2tp-psk"[1] 1.2.3.4 instance with peer 1.2.3.4 {isakmp=#0/ipsec=#0}

**Comment by hwdsl2** [comment]
@anmiles Hello! Your logs indicate that there is some firewall between the VPN server and client which interferes with the connection, or there is a network problem. This is typically not an issue with the VPN server itself.
