### ISSUE TITLE
MultiUser

### ISSUE THREAD

**Issue by Jonnyfencing1** [hwdsl2/docker-ipsec-vpn-server#76]
Is it Possible to have multiple users on the one machine? Or is it just one per VPN setup?

**Comment by wowgamr** [comment]
Hello! You can create few users: https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users.md

**Comment by hwdsl2** [comment]
Thanks @wowgamr!
@Jonnyfencing1 Please refer to the "Important Notes" section [1] of README.

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server#important-notes
