### ISSUE TITLE
[Suggestion]  Access to VPN-hosts from outside the Docker

### ISSUE THREAD

**Issue by zdzichu6969** [hwdsl2/docker-ipsec-vpn-server#82]
Access to VPN-hosts from outside the Docker

iptables rule in run.sh: 

> iptables -I FORWARD 7 -i eth+ -o ppp+ -j ACCEPT

**Comment by hwdsl2** [comment]
@zdzichu6969 Hello! Thanks for the suggestion. However, while the IPTables rule you suggested can enable access to VPN clients from outside Docker, it also exposes VPN clients to potentially malicious traffic initiated from the Internet. Note that by default, the IPTables rules in this image only allow "RELATED, ESTABLISHED" traffic from `eth+` to `ppp+`.
