### ISSUE TITLE
Cannot modprobe af_key

### ISSUE THREAD

**Issue by Imajou** [hwdsl2/docker-ipsec-vpn-server#83]
Good afternoon.

Using this VPN image with Docker 18.03 on CoreOS 1745

Got this error when launching:
`modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.14.48-coreos-r2/modules.dep.bin'
modprobe: FATAL: Module af_key not found in directory /lib/modules/4.14.48-coreos-r2
Redirecting to: /etc/init.d/ipsec start`

That is running configuration:
`docker run \
    --name ipsec-vpn-server \
    --env-file ./vpn.env \
    --restart=unless-stopped \
    -p 500:500/udp \
    -p 4500:4500/udp \
    -v /lib/modules:/lib/modules:ro \
    -d --privileged \
    hwdsl2/ipsec-vpn-server`

I suppose, I should somehow modify the volume exposing with `-v /lib/modules:/lib/modules:ro`
Any obvious modification of exposure does not work.

**Comment by hwdsl2** [comment]
@Imajou Hello! CoreOS is not currently supported.

**Comment by hwdsl2** [comment]
@Imajou Hello! I tried to reproduce this issue under CoreOS 1855.4.0 but the `sudo modprobe af_key` command runs fine both outside and inside the Docker container.

I think there is a problem with your system's kernel modules, perhaps your kernel module folder `/lib/modules/4.14.48-coreos-r2` does not match the version of your kernel (check `uname -r`)?

The latest version of this Docker image is now compatible with CoreOS, with the fix in commit 0d09e01.

**Comment by sudanking** [comment]
I still can not run Docker image in CoreOS even after I remove aes256-sha2_512 ..... any suggestions??

**Comment by hwdsl2** [comment]
@sudanking The error probably means you are mixing IPsec/L2TP clients with IPsec/XAuth clients and connecting them shortly after one another. Try restarting the Docker container.

If still not working, backup your VPN credentials, get the latest version of the Docker image, then re-create your Docker container and try again.
