### ISSUE TITLE
Some sites do not open(for example google.com, youtube.com)

### ISSUE THREAD

**Issue by trochdewei** [hwdsl2/docker-ipsec-vpn-server#86]
Seems like that PMTUD is broken. After some searching i found links that may be related https://github.com/moby/moby/issues/12565 https://www.zeitgeist.se/2013/11/26/mtu-woes-in-ipsec-tunnels-how-to-fix/

**Comment by hwdsl2** [comment]
@trochdewei Hello! The issue you described could be due to DNS caching (clear your DNS cache could help) or as you mentioned, a MTU related bug in your particular VPN client or network.
