### ISSUE TITLE
Provision for adding additional users

### ISSUE THREAD

**Issue by pogzie** [hwdsl2/docker-ipsec-vpn-server#91]
While running this docker container seems to be convenient, adding additional users is troublesome. 

Can you provide a section in the `start.sh` file to accommodate additional users? Perhaps an `env` variable containing the additional users separated by comma: 

```
ADDITIONAL_USERS="bob,bill,jane,mark"
ADDITIONAL_USERS_PW="bobspassword,billspassword,janespassword,markspassword" 
```

Im using this docker image to automate and streamline the deployment of a small home network VPN but its counter-intuitive to `docker exec` and add the other users manually.

**Comment by pogzie** [comment]
One simpler fix would be: 

```
# Create VPN credentials
cat >> /etc/ppp/chap-secrets <<EOF
"$VPN_USER" l2tpd "$VPN_PASSWORD" *
EOF

VPN_PASSWORD_ENC=$(openssl passwd -1 "$VPN_PASSWORD")
cat >> /etc/ipsec.d/passwd <<EOF
$VPN_USER:$VPN_PASSWORD_ENC:xauth-psk
EOF
```

The issue with your original `cat >` is that even if I write the additional users to the `chap-secrets` and to the `passwd` file, running the `start.sh` would just obliterate what I added there. Converting to `cat >>` would preserve what is written there before adding the user from the ENV variable.

**Comment by pogzie** [comment]
@hwdsl2 any thoughts on the possibility of converting `cat >` to `cat >>` ?

**Comment by hwdsl2** [comment]
@pogzie Hello! Thank you for the suggestion. Unfortunately, changing `cat >` to `cat >>` will add a duplicate line every time the container is restarted (e.g. at system boot).

Going forward, we'll look into other ways to enabling multiple users. In the meantime, you may enable multiple users yourself by first entering the container [1], then add multiple users using these instructions [2], and finally, edit `/opt/src/run.sh` inside the container and comment out these lines [3].

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server#bash-shell-inside-container
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users.md
[3] https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/run.sh#L205-L213

**Comment by pogzie** [comment]
Thats what I did. But it defeats the purpose of containerizing it if I would have to manually do it everytime i restart the container. 

Good catch on the `>>` tho. 

One alternative im thinking is comma separating the accounts and just looping through it. Converting the env variable to accept comma separated values (along with the password of course), it would be easier to iterate until all elements are added to the file.
