### ISSUE TITLE
connect my router without re-shared key

### ISSUE THREAD

**Issue by jfernandogt** [hwdsl2/docker-ipsec-vpn-server#92]
Hi, my router only have the user and password option to connect to my server. How can configure your server to allow only user and password?
Thanks.

**Comment by hwdsl2** [comment]
@jfernandogt Hello! The mode you mentioned is not supported. Using username/password without PSK is called "L2TP without IPsec", some routers have this mode for interaction with some special ISPs. It is not intended for use as VPN, as the traffic is not encrypted.
