### ISSUE TITLE
connection failed, how to resolve ?

### ISSUE THREAD

**Issue by liwei00wade** [hwdsl2/docker-ipsec-vpn-server#93]
root@wade-work:/home/wade# ipsec up myvpn
initiating Main Mode IKE_SA myvpn[6] to 192.168.1.188
generating ID_PROT request 0 [ SA V V V V ]
sending packet: from 192.168.1.215[500] to 192.168.1.188[500] (188 bytes)
received packet: from 192.168.1.188[500] to 192.168.1.215[500] (144 bytes)
parsed ID_PROT response 0 [ SA V V V ]
received FRAGMENTATION vendor ID
received DPD vendor ID
received NAT-T (RFC 3947) vendor ID
generating ID_PROT request 0 [ KE No NAT-D NAT-D ]
sending packet: from 192.168.1.215[500] to 192.168.1.188[500] (244 bytes)
received packet: from 192.168.1.188[500] to 192.168.1.215[500] (244 bytes)
parsed ID_PROT response 0 [ KE No NAT-D NAT-D ]
local host is behind NAT, sending keep alives
remote host is behind NAT
generating ID_PROT request 0 [ ID HASH N(INITIAL_CONTACT) ]
sending packet: from 192.168.1.215[4500] to 192.168.1.188[4500] (108 bytes)
received packet: from 192.168.1.188[4500] to 192.168.1.215[4500] (76 bytes)
parsed ID_PROT response 0 [ ID HASH V ]
received unknown vendor ID: 49:4b:45:76:32
IDir '124.64.232.30' does not match to '192.168.1.188'
deleting IKE_SA myvpn[6] between 192.168.1.215[192.168.1.215]...192.168.1.188[%any]
sending DELETE for IKE_SA myvpn[6]
generating INFORMATIONAL_V1 request 2726140425 [ HASH D ]
sending packet: from 192.168.1.215[4500] to 192.168.1.188[4500] (92 bytes)
connection 'myvpn' established successfully

**Comment by hwdsl2** [comment]
@liwei00wade Hello! It looks like you are connecting to the VPN server behind a (home) router using its private IP instead of its public IP. Please set up port forwarding on your router for UDP ports 500 and 4500, then use the VPN server's public IP to connect.
