### ISSUE TITLE
Is there any way to combine this with fail2ban? 

### ISSUE THREAD

**Issue by AnderssonPeter** [hwdsl2/docker-ipsec-vpn-server#96]
Is there any way to combine this with fail2ban?

**Comment by hwdsl2** [comment]
@AnderssonPeter Hello! To my knowledge there is no existing fail2ban filters that work well with IPsec. You may be able to write your own, however.

**Comment by AnderssonPeter** [comment]
Where are the logs stored in the container?

**Comment by hwdsl2** [comment]
@AnderssonPeter Please refer to [1] for how to enable Libreswan logs. For xl2tpd logs, you may check using e.g. `docker logs ipsec-vpn-server`.

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server#enable-libreswan-logs

**Comment by rasodu** [comment]
I just exposed the VPN ports on my router.
I want to understand how easy/difficult is for someone to brute force authenticate.
How long would it take someone to get in? (Assuming it's not an easy password to guess.)
