### ISSUE TITLE
Tags for Older Version

### ISSUE THREAD

**Issue by pogzie** [hwdsl2/docker-ipsec-vpn-server#98]
Hi, since I was having problems with the new build, I was checking if there were other older versions available in Dockerhub, but all I see is the latest version. 

Possible to keep the old releases for when the new version fails to work properly?

**Comment by selim13** [comment]
Not sure why this issue was closed. 
It would be really nice to see proper tagging/versioning of the image.

**Comment by hwdsl2** [comment]
@selim13 Thanks for the suggestion. What is your use case for tagging this image? And what would you suggest that the tags are based on? Libreswan versions?

**Comment by selim13** [comment]
> What is your use case for tagging this image?
It's a good practice to keep image version pinned inside docker-compose file to prevent things breaking on images pulls. Also with github tagging/releases it is easier to keep track on source changes between them (especially on "sensitive" type of image like vpn). And it is simple to setup automated builds from those tags.

> And what would you suggest that the tags are based on? Libreswan versions?
I would suggest libreswan version + numeric postfix like "3.27-1" as there is more interest on versioning image build scripts aside from libreswan.

Thanks for your time and this handy image =)

**Comment by rasodu** [comment]
Not sure how much complexity it would add to current build process, but having tags have a few advantages.
- Allow testing of the image per-production environment before deploying it in production.
- Rollback if someone is having problem in production. Some time not all the users see bugs. A specific configuration could be causing the issue. It would be good to be able to rollback to previously working release.
- If we ever need to release backward incompatible release(Let's say env variables name changes or add a new required env), then people who don't make change can still keep the installation working by using the tag under which their installed works.

**Comment by hwdsl2** [comment]
@rasodu Thank you for the suggestions. I agree that using tags may be beneficial in certain cases. However, for this particular Docker image, the testing in pre-production and/or rollback scenarios may not apply. And backward incompatible changes have been very rare in the history of this project. If you have examples of specific commit(s) which broke backward compatibility or could otherwise benefit from the use of tags, let me know.
