### ISSUE TITLE
Cannot connect to vpn server on macos

### ISSUE THREAD

**Issue by lncan** [hwdsl2/docker-ipsec-vpn-server#99]
Hi guys, I user this repo and run docker-compose but i can't access vpn server. Here is my log. Anyone has solution? Thanks all.
![screen shot 2018-11-16 at 17 12 08](https://user-images.githubusercontent.com/40355589/48615308-2006a100-e9c3-11e8-898c-6ecd7895bc76.png)

**Comment by hwdsl2** [comment]
@lncan Hello! Your logs show that the VPN server is running fine but there is no connection attempts in the logs, which means traffic did not reach your VPN server.

Double check your server’s firewall settings and make sure you use the correct server IP in the VPN client.
